export enum zIndex {
  SPLASH_SCREEN = 10000,
  PLAY_BAR = 5,
  PREMIUM_TRACK_TILE_CORNER_TAG = 3,
  CHAT_REACTIONS_POPUP_DIM_BACKGROUND = 10,
  CHAT_REACTIONS_POPUP_CLOSE_PRESSABLES = 20,
  CHAT_REACTIONS_POPUP_CONTENT = 30
}
