import { Environment } from '@audius/common'

export const env = {
  AAO_ENDPOINT: process.env.VITE_AAO_ENDPOINT,
  EAGER_DISCOVERY_NODES: process.env.VITE_EAGER_DISCOVERY_NODES,
  EXPLORE_CONTENT_URL: process.env.VITE_EXPLORE_CONTENT_URL,
  ENVIRONMENT: process.env.VITE_ENVIRONMENT as Environment,
  ORACLE_ETH_ADDRESSES: process.env.VITE_ORACLE_ETH_ADDRESSES,
  SUGGESTED_FOLLOW_HANDLES: process.env.VITE_SUGGESTED_FOLLOW_HANDLES as string,
  GENERAL_ADMISSION: process.env.VITE_GENERAL_ADMISSION,
  IDENTITY_SERVICE: process.env.VITE_IDENTITY_SERVICE,
  PUBLIC_HOSTNAME: process.env.VITE_PUBLIC_HOSTNAME
}
