import { z } from 'zod';

export const UsersScalarFieldEnumSchema = z.enum([
  'blockhash',
  'user_id',
  'is_current',
  'handle',
  'wallet',
  'name',
  'profile_picture',
  'cover_photo',
  'bio',
  'location',
  'metadata_multihash',
  'creator_node_endpoint',
  'blocknumber',
  'is_verified',
  'created_at',
  'updated_at',
  'handle_lc',
  'cover_photo_sizes',
  'profile_picture_sizes',
  'primary_id',
  'secondary_ids',
  'replica_set_update_signer',
  'has_collectibles',
  'txhash',
  'playlist_library',
  'is_deactivated',
  'slot',
  'user_storage_account',
  'user_authority_account',
  'artist_pick_track_id',
  'is_available',
  'is_storage_v2',
  'allow_ai_attribution',
]);
