begin;
drop table rpc_log cascade;
drop table chat cascade;
drop table chat_blocked_users cascade;
drop table chat_member cascade;
drop table chat_message cascade;
drop table chat_message_reactions cascade;
drop table chat_permissions cascade;
drop table schema_migrations cascade;
commit;
