export enum zIndex {
  CHAT_TAIL = -10,
  PREMIUM_TRACK_TILE_CORNER_TAG = 3,
  PLAY_BAR = 5,
  CHAT_REACTIONS_POPUP_DIM_BACKGROUND = 10,
  HEADER_SHADOW = 10,
  STRIPE_ONRAMP_DRAWER = 10,
  COINFLOW_ONRAMP_DRAWER = 10,
  CHAT_REACTIONS_POPUP_CLOSE_PRESSABLES = 20,
  CHAT_REACTIONS_POPUP_CONTENT = 30,
  SPLASH_SCREEN = 10000,
  TOAST = 10001
}
