/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum zIndex {
  CHAT_TAIL = -10,
  CHAT_BLAST_SUBHEADER = 1,
  NOW_PLAYING_DRAWER = 3,
  DOG_EAR = 4,
  PLAY_BAR = 5,
  CHAT_REACTIONS_POPUP_DIM_BACKGROUND = 10,
  HEADER_SHADOW = 10,
  STRIPE_ONRAMP_DRAWER = 10,
  COINFLOW_ONRAMP_DRAWER = 10,
  CHAT_REACTIONS_POPUP_CLOSE_PRESSABLES = 20,
  CHAT_REACTIONS_POPUP_CONTENT = 30,
  SPLASH_SCREEN = 10000,
  TOAST = 10001,
  PROFILE_PAGE_PROFILE_PICTURE = 100
}
