export enum zIndex {
  SPLASH_SCREEN = 10000,
  PLAY_BAR = 5,
  PREMIUM_TRACK_TILE_CORNER_TAG = 3,
  CHAT_REACTIONS_POPUP_DIM_BACKGROUND = 10,
  CHAT_REACTIONS_POPUP_CLOSE_PRESSABLES = 20,
  CHAT_REACTIONS_POPUP_CONTENT = 30,
  CHAT_TAIL = -10,
  HEADER_SHADOW = 10,
  STRIPE_ONRAMP_DRAWER = 10
}
