"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Order:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Order.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ORDER_UNSPECIFIED: _Order.ValueType  # 0
    ORDER_ASC: _Order.ValueType  # 1
    ORDER_DESC: _Order.ValueType  # 2

class Order(_Order, metaclass=_OrderEnumTypeWrapper): ...

ORDER_UNSPECIFIED: Order.ValueType  # 0
ORDER_ASC: Order.ValueType  # 1
ORDER_DESC: Order.ValueType  # 2
global___Order = Order

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___PingResponse = PingResponse

@typing.final
class GetHealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHealthRequest = GetHealthRequest

@typing.final
class GetHealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHealthResponse = GetHealthResponse

@typing.final
class GetUploadsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    order: global___Order.ValueType
    @property
    def pagination(self) -> global___Pagination: ...
    def __init__(
        self,
        *,
        pagination: global___Pagination | None = ...,
        order: global___Order.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pagination", b"pagination"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["order", b"order", "pagination", b"pagination"]) -> None: ...

global___GetUploadsRequest = GetUploadsRequest

@typing.final
class GetUploadsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPLOADS_FIELD_NUMBER: builtins.int
    @property
    def uploads(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Upload]: ...
    def __init__(
        self,
        *,
        uploads: collections.abc.Iterable[global___Upload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uploads", b"uploads"]) -> None: ...

global___GetUploadsResponse = GetUploadsResponse

@typing.final
class GetUploadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___GetUploadRequest = GetUploadRequest

@typing.final
class GetUploadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPLOAD_FIELD_NUMBER: builtins.int
    @property
    def upload(self) -> global___Upload: ...
    def __init__(
        self,
        *,
        upload: global___Upload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["upload", b"upload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["upload", b"upload"]) -> None: ...

global___GetUploadResponse = GetUploadResponse

@typing.final
class StreamTrackRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___StreamTrackRequest = StreamTrackRequest

@typing.final
class StreamTrackResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___StreamTrackResponse = StreamTrackResponse

@typing.final
class StreamImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___StreamImageRequest = StreamImageRequest

@typing.final
class StreamImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___StreamImageResponse = StreamImageResponse

@typing.final
class Pagination(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIMIT_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    limit: builtins.int
    offset: builtins.int
    def __init__(
        self,
        *,
        limit: builtins.int = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "offset", b"offset"]) -> None: ...

global___Pagination = Pagination

@typing.final
class Upload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    TRACK_ID_FIELD_NUMBER: builtins.int
    FILE_NAME_FIELD_NUMBER: builtins.int
    FILE_TYPE_FIELD_NUMBER: builtins.int
    FILE_SIZE_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    track_id: builtins.str
    file_name: builtins.str
    file_type: builtins.str
    file_size: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
        track_id: builtins.str = ...,
        file_name: builtins.str = ...,
        file_type: builtins.str = ...,
        file_size: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_name", b"file_name", "file_size", b"file_size", "file_type", b"file_type", "id", b"id", "track_id", b"track_id", "user_id", b"user_id"]) -> None: ...

global___Upload = Upload
