export { EntityManagerClient } from './EntityManagerClient'
export type { EntityManagerService } from './types'
export { Action as EntityManagerAction } from './types'
export { EntityType } from './types'
export { getDefaultEntityManagerConfig } from './getDefaultConfig'
