export const DEVICE_TOKEN = '@device-token'
export const IS_MOBILE_USER = 'is-mobile-user'
export const RATE_CTA_STORAGE_KEY = '@rate-cta-response'
export const IP_STORAGE_KEY = 'user-ip-timetstamp'
export const SESSION_COUNT_KEY = '@session-count'
export const ENTROPY_KEY = 'hedgehog-entropy-key'
export const THEME_STORAGE_KEY = 'theme'
export const SEARCH_HISTORY_KEY = '@search-history'
