# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system/v1/service.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'system/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.tasks.core.audiusd_gen.system.v1 import types_pb2 as system_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17system/v1/service.proto\x12\tsystem.v1\x1a\x15system/v1/types.proto2\x94\x01\n\rSystemService\x12\x39\n\x04Ping\x12\x16.system.v1.PingRequest\x1a\x17.system.v1.PingResponse\"\x00\x12H\n\tGetHealth\x12\x1b.system.v1.GetHealthRequest\x1a\x1c.system.v1.GetHealthResponse\"\x00\x42\x34Z2github.com/AudiusProject/audiusd/pkg/api/system/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/AudiusProject/audiusd/pkg/api/system/v1'
  _globals['_SYSTEMSERVICE']._serialized_start=62
  _globals['_SYSTEMSERVICE']._serialized_end=210
# @@protoc_insertion_point(module_scope)
