"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import core.v1.types_pb2
import etl.v1.types_pb2
import google.protobuf.descriptor
import google.protobuf.message
import storage.v1.types_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    CORE_PING_FIELD_NUMBER: builtins.int
    STORAGE_PING_FIELD_NUMBER: builtins.int
    ETL_PING_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def core_ping(self) -> core.v1.types_pb2.PingResponse: ...
    @property
    def storage_ping(self) -> storage.v1.types_pb2.PingResponse: ...
    @property
    def etl_ping(self) -> etl.v1.types_pb2.PingResponse: ...
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        core_ping: core.v1.types_pb2.PingResponse | None = ...,
        storage_ping: storage.v1.types_pb2.PingResponse | None = ...,
        etl_ping: etl.v1.types_pb2.PingResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["core_ping", b"core_ping", "etl_ping", b"etl_ping", "storage_ping", b"storage_ping"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["core_ping", b"core_ping", "etl_ping", b"etl_ping", "message", b"message", "storage_ping", b"storage_ping"]) -> None: ...

global___PingResponse = PingResponse

@typing.final
class GetHealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHealthRequest = GetHealthRequest

@typing.final
class GetHealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    CORE_HEALTH_FIELD_NUMBER: builtins.int
    STORAGE_HEALTH_FIELD_NUMBER: builtins.int
    ETL_HEALTH_FIELD_NUMBER: builtins.int
    status: builtins.str
    @property
    def core_health(self) -> core.v1.types_pb2.GetHealthResponse: ...
    @property
    def storage_health(self) -> storage.v1.types_pb2.GetHealthResponse: ...
    @property
    def etl_health(self) -> etl.v1.types_pb2.GetHealthResponse: ...
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        core_health: core.v1.types_pb2.GetHealthResponse | None = ...,
        storage_health: storage.v1.types_pb2.GetHealthResponse | None = ...,
        etl_health: etl.v1.types_pb2.GetHealthResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["core_health", b"core_health", "etl_health", b"etl_health", "storage_health", b"storage_health"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["core_health", b"core_health", "etl_health", b"etl_health", "status", b"status", "storage_health", b"storage_health"]) -> None: ...

global___GetHealthResponse = GetHealthResponse
