import { useCallback, useMemo } from 'react'

import { useGeneratePlaylistArtwork } from '@audius/common'
import { useField, useFormikContext } from 'formik'
import { capitalize } from 'lodash'
import { View } from 'react-native'
import type { Asset } from 'react-native-image-picker'

import IconImage from 'app/assets/images/iconImage.svg'
import IconPencil from 'app/assets/images/iconPencil.svg'
import { Button, DynamicImage } from 'app/components/core'
import { InputErrorMessage } from 'app/components/core/InputErrorMessage'
import LoadingSpinner from 'app/components/loading-spinner'
import { makeStyles } from 'app/styles'
import type { Image } from 'app/types/image'
import { launchSelectImageActionSheet } from 'app/utils/launchSelectImageActionSheet'
import { useThemeColors } from 'app/utils/theme'

type Error = {
  url: string
}

const useStyles = makeStyles(({ palette, spacing }) => ({
  root: {
    marginTop: spacing(4),
    marginHorizontal: spacing(4),
    marginBottom: spacing(2)
  },
  image: {
    aspectRatio: 1,
    backgroundColor: palette.neutralLight6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.neutralLight9,
    overflow: 'hidden'
  },
  iconPicture: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center'
  },
  button: {
    position: 'absolute',
    bottom: spacing(6),
    left: 0,
    right: 0
  },
  loading: {
    height: 50,
    width: 50
  }
}))

const messages = {
  addArtwork: 'Add Artwork',
  changeArtwork: 'Change Artwork',
  removeArtwork: 'Remove Artwork',
  removingArtwork: 'Removing Artwork',
  updatingArtwork: 'Updating Artwork'
}

type PickArtworkFieldProps = {
  name: string
}

export const PickArtworkField = (props: PickArtworkFieldProps) => {
  const { name } = props
  const styles = useStyles()
  const { neutralLight8 } = useThemeColors()
  const [{ value }, { error, touched }, { setValue: setArtwork }] =
    useField(name)
  const [{ value: existingTrackArtwork }] = useField('trackArtwork')
  const trackArtworkUrl = value?.url ?? existingTrackArtwork
  const [{ value: collectionId }] = useField('playlist_id')
  const [{ value: isImageAutogenerated }, , { setValue: setIsAutogenerated }] =
    useField('is_image_autogenerated')

  const { secondary } = useThemeColors()

  const { status, setStatus } = useFormikContext()

  const handleChangeArtwork = useCallback(() => {
    const handleImageSelected = (_image: Image, rawResponse: Asset) => {
      setArtwork({
        url: rawResponse.uri,
        file: {
          uri: rawResponse.uri,
          name: rawResponse.fileName,
          type: rawResponse.type
        },
        source: 'original'
      })
      setIsAutogenerated(false)
      setStatus({ imageLoading: true })
    }
    launchSelectImageActionSheet(handleImageSelected, secondary)
  }, [secondary, setArtwork, setIsAutogenerated, setStatus])

  const source = useMemo(() => ({ uri: trackArtworkUrl }), [trackArtworkUrl])

  const generatePlaylistArtwork = useGeneratePlaylistArtwork(collectionId)

  const handleRemoveArtwork = useCallback(async () => {
    setStatus({ imageLoading: true, imageGenerating: true })
    const { file, url } = await generatePlaylistArtwork()
    setArtwork({ url, file })
    setIsAutogenerated(true)
  }, [setStatus, generatePlaylistArtwork, setArtwork, setIsAutogenerated])

  return (
    <View style={styles.root}>
      <DynamicImage
        source={source}
        onLoad={() =>
          setStatus({ imageLoading: false, imageGenerating: false })
        }
        style={styles.image}
        noSkeleton
      >
        <View style={styles.iconPicture}>
          {status.imageLoading || status.imageGenerating ? (
            <LoadingSpinner style={styles.loading} />
          ) : trackArtworkUrl ? null : (
            <IconImage height={128} width={128} fill={neutralLight8} />
          )}
        </View>
        <View style={styles.button}>
          <Button
            variant='secondaryAlt'
            size='large'
            title={
              status.imageGenerating && isImageAutogenerated
                ? messages.updatingArtwork
                : trackArtworkUrl && status.imageGenerating
                ? messages.removingArtwork
                : trackArtworkUrl && !isImageAutogenerated
                ? messages.removeArtwork
                : trackArtworkUrl
                ? messages.changeArtwork
                : messages.addArtwork
            }
            icon={IconPencil}
            iconPosition='left'
            onPress={
              trackArtworkUrl && !isImageAutogenerated
                ? handleRemoveArtwork
                : handleChangeArtwork
            }
          />
        </View>
      </DynamicImage>
      {error && touched ? (
        <InputErrorMessage
          message={`${capitalize(name)} ${error as unknown as Error}`}
        />
      ) : null}
    </View>
  )
}
