export { default as imageBlank } from './img/imageBlank2x.png'
export { default as imageCoverPhotoBlank } from './img/imageCoverPhotoBlank.jpg'
export { default as imageProfilePicEmpty } from './img/imageProfilePicEmpty2X.png'
export { default as imageCollectiblePlaceholder } from './img/imageCollectiblePlaceholder2x.webp'
export { default as imageProfilePicEmptyNew } from './img/imageProfilePicEmpty.png'
