/*
API

Audius V1 API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codegen

import (
	"encoding/json"
)

// checks if the Reposts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Reposts{}

// Reposts struct for Reposts
type Reposts struct {
	Data []Activity `json:"data,omitempty"`
}

// NewReposts instantiates a new Reposts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReposts() *Reposts {
	this := Reposts{}
	return &this
}

// NewRepostsWithDefaults instantiates a new Reposts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepostsWithDefaults() *Reposts {
	this := Reposts{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Reposts) GetData() []Activity {
	if o == nil || IsNil(o.Data) {
		var ret []Activity
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Reposts) GetDataOk() ([]Activity, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Reposts) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Activity and assigns it to the Data field.
func (o *Reposts) SetData(v []Activity) {
	o.Data = v
}

func (o Reposts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Reposts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableReposts struct {
	value *Reposts
	isSet bool
}

func (v NullableReposts) Get() *Reposts {
	return v.value
}

func (v *NullableReposts) Set(val *Reposts) {
	v.value = val
	v.isSet = true
}

func (v NullableReposts) IsSet() bool {
	return v.isSet
}

func (v *NullableReposts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReposts(val *Reposts) *NullableReposts {
	return &NullableReposts{value: val, isSet: true}
}

func (v NullableReposts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReposts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


