/*
API

Audius V1 API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codegen

import (
	"encoding/json"
)

// checks if the TrendingPlaylistsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrendingPlaylistsResponse{}

// TrendingPlaylistsResponse struct for TrendingPlaylistsResponse
type TrendingPlaylistsResponse struct {
	Data []Playlist `json:"data,omitempty"`
}

// NewTrendingPlaylistsResponse instantiates a new TrendingPlaylistsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrendingPlaylistsResponse() *TrendingPlaylistsResponse {
	this := TrendingPlaylistsResponse{}
	return &this
}

// NewTrendingPlaylistsResponseWithDefaults instantiates a new TrendingPlaylistsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrendingPlaylistsResponseWithDefaults() *TrendingPlaylistsResponse {
	this := TrendingPlaylistsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TrendingPlaylistsResponse) GetData() []Playlist {
	if o == nil || IsNil(o.Data) {
		var ret []Playlist
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrendingPlaylistsResponse) GetDataOk() ([]Playlist, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TrendingPlaylistsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Playlist and assigns it to the Data field.
func (o *TrendingPlaylistsResponse) SetData(v []Playlist) {
	o.Data = v
}

func (o TrendingPlaylistsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrendingPlaylistsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTrendingPlaylistsResponse struct {
	value *TrendingPlaylistsResponse
	isSet bool
}

func (v NullableTrendingPlaylistsResponse) Get() *TrendingPlaylistsResponse {
	return v.value
}

func (v *NullableTrendingPlaylistsResponse) Set(val *TrendingPlaylistsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTrendingPlaylistsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTrendingPlaylistsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrendingPlaylistsResponse(val *TrendingPlaylistsResponse) *NullableTrendingPlaylistsResponse {
	return &NullableTrendingPlaylistsResponse{value: val, isSet: true}
}

func (v NullableTrendingPlaylistsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrendingPlaylistsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


