/*
API

Audius V1 API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package codegen

import (
	"encoding/json"
)

// checks if the PlaylistResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaylistResponse{}

// PlaylistResponse struct for PlaylistResponse
type PlaylistResponse struct {
	Data []Playlist `json:"data,omitempty"`
}

// NewPlaylistResponse instantiates a new PlaylistResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylistResponse() *PlaylistResponse {
	this := PlaylistResponse{}
	return &this
}

// NewPlaylistResponseWithDefaults instantiates a new PlaylistResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistResponseWithDefaults() *PlaylistResponse {
	this := PlaylistResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PlaylistResponse) GetData() []Playlist {
	if o == nil || IsNil(o.Data) {
		var ret []Playlist
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistResponse) GetDataOk() ([]Playlist, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PlaylistResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Playlist and assigns it to the Data field.
func (o *PlaylistResponse) SetData(v []Playlist) {
	o.Data = v
}

func (o PlaylistResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaylistResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePlaylistResponse struct {
	value *PlaylistResponse
	isSet bool
}

func (v NullablePlaylistResponse) Get() *PlaylistResponse {
	return v.value
}

func (v *NullablePlaylistResponse) Set(val *PlaylistResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylistResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylistResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylistResponse(val *PlaylistResponse) *NullablePlaylistResponse {
	return &NullablePlaylistResponse{value: val, isSet: true}
}

func (v NullablePlaylistResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaylistResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


