import { Environment } from '@audius/common'

export const env = {
  AAO_ENDPOINT: process.env.REACT_APP_AAO_ENDPOINT,
  EAGER_DISCOVERY_NODES: process.env.REACT_APP_EAGER_DISCOVERY_NODES,
  EXPLORE_CONTENT_URL: process.env.REACT_APP_EXPLORE_CONTENT_URL,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT as Environment,
  ORACLE_ETH_ADDRESSES: process.env.REACT_APP_ORACLE_ETH_ADDRESSES,
  SUGGESTED_FOLLOW_HANDLES: process.env
    .REACT_APP_SUGGESTED_FOLLOW_HANDLES as string
}
