import { randomBytes } from 'crypto'
import chalk from 'chalk'
import { Command } from '@commander-js/extra-typings'
import { getCurrentUserId, initializeAudiusSdk, parseBoolean } from '../utils'
import { decodeHashId } from '@audius/sdk'
import { outputFormatOption } from '../common-options'

export const createAlbumCommand = new Command('create')
  .description('Create album')
  .argument('<trackIds...>', 'Tracks to include in album')
  .option('-f, --from <from>', 'The account to upload from')
  .option(
    '-n, --album-name <albumName>',
    'Name of album (chosen randomly if not specified)'
  )
  .option(
    '-d, --description <description>',
    'Description of album (chosen randomly if not specified)'
  )
  .option('-p, --is-private [isPrivate]', 'Make album private', parseBoolean)
  .addOption(outputFormatOption)
  .action(async (trackIds, options) => {
    const rand = randomBytes(2).toString('hex').padStart(4, '0').toUpperCase()
    const {
      albumName = `playlist ${rand}`,
      description = 'playlist generated by audius-cmd',
      isPrivate,
      from
    } = options

    const audiusSdk = await initializeAudiusSdk({ handle: from })
    const userId = await getCurrentUserId()

    const response = await audiusSdk.albums.createAlbum({
      userId,
      trackIds,
      metadata: {
        albumName,
        description,
        isPrivate
      }
    })

    if (options.output === 'json') {
      console.log(JSON.stringify(response))
    } else {
      console.log(chalk.green('Successfully created album'))
      console.log(chalk.yellow.bold('Album ID:  '), response.playlistId)
      console.log(
        chalk.yellow.bold('Album ID #:'),
        decodeHashId(response.playlistId!)
      )
    }
  })
