export COMPOSE_PROJECT_NAME="cn4"
export CREATOR_NODE_HOST_PORT=4003
export CREATOR_NODE_DB_HOST_PORT=4435
export CREATOR_NODE_REDIS_HOST_PORT=4382
export CREATOR_NODE_ENV_OVERRIDE_PATH="./env/override4.env"