export COMPOSE_PROJECT_NAME="cn2"
export CREATOR_NODE_HOST_PORT=4001
export CREATOR_NODE_DB_HOST_PORT=4433
export CREATOR_NODE_REDIS_HOST_PORT=4380
export CREATOR_NODE_ENV_OVERRIDE_PATH="./env/override2.env"