export COMPOSE_PROJECT_NAME="cn1"
export CREATOR_NODE_HOST_PORT=4000
export CREATOR_NODE_DB_HOST_PORT=4432
export CREATOR_NODE_REDIS_HOST_PORT=4379
export CREATOR_NODE_ENV_OVERRIDE_PATH="./env/override1.env"