export COMPOSE_PROJECT_NAME="cn3"
export CREATOR_NODE_HOST_PORT=4002
export CREATOR_NODE_DB_HOST_PORT=4434
export CREATOR_NODE_REDIS_HOST_PORT=4381
export CREATOR_NODE_ENV_OVERRIDE_PATH="./env/override3.env"