"""restart_audio_tx_hist_indexing

Revision ID: 0a6d444d8192
Revises: 959f15b94094
Create Date: 2022-11-20 19:42:21.304552

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a6d444d8192"
down_revision = "959f15b94094"
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    query = """
        delete from audio_transactions_history;
        delete from user_bank_backfill_txs;
        delete from spl_token_backfill_txs;
        delete from rewards_manager_backfill_txs;
        delete from indexing_checkpoints where signature is not null;
        """
    connection.execute(query)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
