"""user bank updates

Revision ID: 273b8bcef694
Revises: 7f4f44a8e880
Create Date: 2021-06-22 17:22:00.102134

"""
import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from src.models import User

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = '273b8bcef694'
down_revision = '7f4f44a8e880'
branch_labels = None
depends_on = None

Session = sessionmaker()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    users_query = (
        session.query(User)
        .filter(
            User.is_current == True
        )
        .all()
    )
    for user in users_query:
        logger.error(user)

    raise Exception('NO COMPLETION')

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
