"""persistent store

Revision ID: 98244215487f
Revises: 8c10373f2615
Create Date: 2022-04-16 00:24:41.662182

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from src.utils.alembic_helpers import table_exists

# revision identifiers, used by Alembic.
revision = "98244215487f"
down_revision = "8c10373f2615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("persistent_store"):
        op.create_table(
            "persistent_store",
            sa.Column("key", sa.String(), nullable=False),
            sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.PrimaryKeyConstraint("key"),
        )


def downgrade():
    op.drop_table("persistent_store")
