"""Add wallet index

Revision ID: d4779ea63753
Revises: dcde0a858682
Create Date: 2018-12-11 16:34:28.221731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4779ea63753"
down_revision = "dcde0a858682"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_wallet"), "users", ["wallet"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_wallet"), table_name="users")
    # ### end Alembic commands ###
