// object that houses hardcoded titles and messages so a change stays the same between push and web
export default {
    addTrackToPlaylist: {},
    announcement: {},
    challengeReward: {},
    cosign: {},
    create: {},
    follow: {},
    message: {},
    messageReaction: {},
    milestone: {},
    reaction: {},
    remix: {},
    repost: {},
    repostOfRepost: {},
    save: {},
    saveOfRepost: {},
    supporterDethroned: {},
    supporterRankUp: {},
    supportingRankUp: {},
    tastemaker: {},
    tierChange: {},
    tipReceive: {},
    tipSend: {},
    trendingPlaylist: {},
    trendingTrack: {},
    trendingUnderground: {},
    userNotificationSettings: {}
}
