/*
 * This file is autogenerated by ./scripts/generateBootstrapConfig.ts.
 * DO NOT EDIT MANUALLY!
 */
/* eslint-disable prettier/prettier */
import type { BootstrapConfig } from './types'
export const bootstrapConfig: BootstrapConfig = {
  "minVersion": "0.0.0",
  "discoveryNodes": [
    "http://audius-protocol-discovery-provider-1"
  ]
}
