/*
 * This file is autogenerated by ./scripts/generateBootstrapConfig.ts.
 * DO NOT EDIT MANUALLY!
 */
/* eslint-disable prettier/prettier */
import type { BootstrapConfig } from './types'
export const bootstrapConfig: BootstrapConfig = {
  "minVersion": "0.3.66",
  "discoveryNodes": [
    "https://discoveryprovider2.staging.audius.co",
    "https://discoveryprovider3.staging.audius.co",
    "https://discoveryprovider.staging.audius.co",
    "https://discoveryprovider5.staging.audius.co"
  ]
}
