reserved_handles = {
    "discover",
    "account",
    "collection",
    "curated",
    "podcast",
    "library",
    "next",
    "suggested",
    "follow",
    "stats",
    "radio",
    "like",
    "repost",
    "share",
    "social",
    "artist",
    "options",
    "billing",
    "support",
    "genre",
    "mood",
    "collections",
    "podcasts",
    "libraries",
    "suggestions",
    "following",
    "stations",
    "likes",
    "reposts",
    "artists",
    "notification",
    "message",
    "inbox",
    "genres",
    "moods",
    "embed",
    "crypto",
    "payment",
    "error",
    "search",
    "api",
    "200",
    "204",
    "400",
    "404",
}


genre_allowlist = {
    "Acoustic",
    "Alternative",
    "Ambient",
    "Audiobooks",
    "Blues",
    "Classical",
    "Comedy",
    "Country",
    "Deep House",
    "Devotional",
    "Disco",
    "Downtempo",
    "Drum & Bass",
    "Dubstep",
    "Electro",
    "Electronic",
    "Experimental",
    "Folk",
    "Funk",
    "Future Bass",
    "Future House",
    "Glitch Hop",
    "Hardstyle",
    "Hip-Hop/Rap",
    "House",
    "Hyperpop",
    "Jazz",
    "Jersey Club",
    "Jungle",
    "Kids",
    "Latin",
    "Lo-Fi",
    "Metal",
    "Moombahton",
    "Podcasts",
    "Pop",
    "Progressive House",
    "Punk",
    "R&B/Soul",
    "Reggae",
    "Rock",
    "Soundtrack",
    "Spoken Word",
    "Tech House",
    "Techno",
    "Trance",
    "Trap",
    "Tropical House",
    "Vaporwave",
    "World",
}


moods = {
    "Peaceful",
    "Romantic",
    "Sentimental",
    "Tender",
    "Easygoing",
    "Yearning",
    "Sophisticated",
    "Sensual",
    "Cool",
    "Gritty",
    "Melancholy",
    "Serious",
    "Brooding",
    "Fiery",
    "Defiant",
    "Aggressive",
    "Rowdy",
    "Excited",
    "Energizing",
    "Empowering",
    "Stirring",
    "Upbeat",
    "Other",
}

reserved_handles_lower = {x.lower() for x in reserved_handles}
genres_lower = {x.lower() for x in genre_allowlist}
moods_lower = {x.lower() for x in moods}
