#!/usr/bin/env bash
set -e

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/compose  # audius-protocol/dev-tools/compose
export COMPOSE_PROJECT_NAME='audius-protocol'

if [[ "$1" == "test" ]]; then
	docker compose exec audius-cmd npm test
	exit
fi

# modify :file args to path inside the container
tmpfiles=()
updated_args=()
for arg in "$@"; do
	if [[ "$arg" == :* ]]; then
		filename="${arg:1}"
		tmpfile="/tmp/$RANDOM.${filename#*.}"
		tmpfiles+=("$tmpfile")
		updated_args+=(":$tmpfile")
		docker compose cp "${arg:1}" audius-cmd:$tmpfile
	else
		updated_args+=("$arg")
	fi
done

docker compose exec audius-cmd node src/index.mjs "${updated_args[@]}" || true

for tmpfile in "${tmpfiles[@]}"; do
	docker compose exec audius-cmd rm $tmpfile
done
