export const MAX_PROFILE_TOP_SUPPORTERS = 5
export const MAX_PROFILE_RELATED_ARTISTS = 5
export const MAX_PROFILE_SUPPORTING_TILES = 3
export const MAX_ARTIST_HOVER_TOP_SUPPORTING = 7

export const MESSAGE_GROUP_THRESHOLD_MINUTES = 2
