/*
 * This file is autogenerated by ./scripts/generateServicesConfig.ts.
 * DO NOT EDIT MANUALLY!
 */
/* eslint-disable prettier/prettier */
import type { ContractBootstrapConfig } from './types'
export const servicesConfig: ContractBootstrapConfig = {
  "minVersion": "0.0.0",
  "discoveryNodes": [
    {
      "delegateOwnerWallet": "0xd09ba371c359f10f22ccda12fd26c598c7921bda3220c9942174562bc6a36fe8",
      "endpoint": "http://audius-protocol-discovery-provider-1",
      "ownerWallet": "0xd09ba371c359f10f22ccda12fd26c598c7921bda3220c9942174562bc6a36fe8"
    }
  ],
  "storageNodes": [
    {
      "delegateOwnerWallet": "0x0D38e653eC28bdea5A2296fD5940aaB2D0B8875c",
      "endpoint": "http://audius-protocol-creator-node-1"
    }
  ],
  "antiAbuseOracleNodeWallets": [
    "0xF0D5BC18421fa04D0a2A2ef540ba5A9f04014BE3"
  ]
}
