export enum StreamTrackAvailabilityType {
  FREE_TO_STREAM = 'FREE_TO_STREAM',
  USDC_PURCHASE = 'USDC_PURCHASE',
  SPECIAL_ACCESS = 'SPECIAL_ACCESS',
  COLLECTIBLE_GATED = 'COLLECTIBLE_GATED',
  HIDDEN = 'HIDDEN'
}

export enum DownloadTrackAvailabilityType {
  PUBLIC = 'PUBLIC',
  FOLLOWERS = 'FOLLOWERS',
  USDC_PURCHASE = 'USDC_PURCHASE'
}
