parameters:
  sdk-release-commit:
    type: string
  sdk-release-version:
    type: string
  sdk-release-preid:
    type: string
resource_class: large
docker:
  - image: cimg/node:18.17
steps:
  - checkout

  - add_ssh_keys:
      fingerprints:
        - 'd0:0b:a0:19:ac:46:58:e4:6c:ac:34:99:f6:1b:31:bb' # github.com

  - run:
      name: npm auth
      command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc

  - create_concatenated_patch_file:
      filename: combined-patch-file.txt

  - restore_cache:
      key: cache-{{ checksum "package-lock.json" }}-{{ checksum "combined-patch-file.txt" }}

  - run:
      name: Release
      command: |
        packages/libs/scripts/release.sh << parameters.sdk-release-commit >> << parameters.sdk-release-version >> << parameters.sdk-release-preid >>
