{
 "title": "Audius - Content Node - Bull Queue",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_jobs_completed_total\"}, queue_name)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   }
  ]
 },
 "panels": [
  { "title": "Queue Success Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Success Rate by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(queue_name) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])) / (sum by(queue_name) (rate(audius_cn_jobs_failed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])) + sum by(queue_name) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])))",
     "legendFormat": "{{queue_name}} "
    }
   ]
  },
  {
   "title": "Queue Success Rate by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])) / (sum by(host) (rate(audius_cn_jobs_failed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])) + sum by(host) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[1h])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Active Queue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(queue_name) (audius_cn_jobs_active_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Active Queue Jobs by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (audius_cn_jobs_active_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Queue Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_jobs_active_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{queue_name}} - {{host}}"
    }
   ]
  },
  { "title": "Waiting Queue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Waiting Queue Jobs by Queue",
   "type": "timeseries",
   "description": "The number of bull jobs waiting to be executed --- if the number of waiting jobs is skyrocketing, it might mean that too many are being created OR that the jobs for that specific queue are taking too long to execute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(queue_name) (audius_cn_jobs_waiting_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Waiting Queue Jobs by Host",
   "type": "timeseries",
   "description": "The number of bull jobs waiting to be executed --- if the number of waiting jobs is skyrocketing, it might mean that too many are being created OR that the jobs for that specific queue are taking too long to execute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (audius_cn_jobs_waiting_total{host=~\"$host\", environment=~\"$env\", queue_name=~\"$queue\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Waiting Queue Jobs",
   "type": "timeseries",
   "description": "The number of bull jobs waiting to be executed.\n\n---\n\nIf the number of waiting jobs is skyrocketing, it might mean:\n\n* Too many are being created.\n* The jobs for that specific queue are taking too long to execute.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_jobs_waiting_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{queue_name}} - {{host}}"
    }
   ]
  },
  { "title": "Queue Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Queue Duration by Queue ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, queue_name) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\", status=\"completed\"}[$__rate_interval])))",
     "legendFormat": "succeeded - {{queue_name}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le, queue_name) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\", status=\"failed\"}[$__rate_interval])))",
     "legendFormat": "failed - {{queue_name}}"
    }
   ]
  },
  {
   "title": "Queue Duration by Host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\", status!=\"failed\"}[1h])))",
     "legendFormat": "95 succeeded - {{host}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\", status=\"failed\"}[$__rate_interval])))",
     "legendFormat": "p95 failed - {{host}}"
    }
   ]
  },
  { "title": "Failed Queue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Failed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(queue_name) (audius_cn_jobs_failed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Failed Queue Jobs by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_jobs_failed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Failed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_jobs_failed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{queue_name}} - {{host}}"
    }
   ]
  },
  { "title": "Completed Queue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Completed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by(queue_name) (audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Completed Queue Jobs by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Completed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "audius_cn_jobs_completed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{queue_name}} - {{host}}"
    }
   ]
  },
  { "title": "Delayed Queue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Delayed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(queue_name) (audius_cn_jobs_delayed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"})",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Delayed Queue Jobs by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(audius_cn_jobs_delayed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}} // {{queue_name}}"
    }
   ]
  },
  {
   "title": "Delayed Queue Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_jobs_delayed_total{environment=~\"$env\", queue_name=~\"$queue\", host=~\"$host\"}",
     "legendFormat": "{{queue_name}} - {{host}}"
    }
   ]
  }
 ]
}