{
 "title": "Audius - Network Monitoring",
 "description": "Network-wide metrics and statuses",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   }
  ]
 },
 "panels": [
  {
   "title": "Users Entirely on Foundation Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Users Entirely on Foundation Nodes %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"} / audius_nm_user_count{environment=~\"$env\"}",
     "legendFormat": "Users Entirely on Foundation Nodes"
    }
   ]
  },
  {
   "title": "Users Entirely on Foundation nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"}",
     "legendFormat": "fully on foundation nodes"
    }
   ]
  },
  {
   "title": "Users Entirely NOT on Foundation Nodes %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_users_with_no_foundation_node_replica_set{environment=~\"$env\"} / audius_nm_user_count{environment=~\"$env\"}",
     "legendFormat": "Users Entirely on Foundation Nodes"
    }
   ]
  },
  {
   "title": "Users entirely on foundation nodes %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum without(run_id,instance) (audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"})) / (sum without(run_id,instance) (audius_nm_user_count{environment=~\"$env\"}))) * 100",
     "legendFormat": "Users entirely on foundation nodes"
    }
   ]
  },
  {
   "title": "Users Entirely on Foundation nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Users entirely NOT on foundation nodes %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without(run_id, instance) (audius_nm_users_with_no_foundation_node_replica_set{environment=~\"$env\"}) * 100) / sum without(run_id, instance) (audius_nm_user_count{environment=~\"$env\"})",
     "legendFormat": "Users entirely on foundation nodes"
    }
   ]
  },
  { "title": "User Node Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "All Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users that have a specific content node in their replica set",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_all_user_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Primary Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users with a specific content node as their primary",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_primary_user_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "All Users Count by Content Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (run_id,instance) (audius_nm_all_user_count{environment=~\"$env\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Primary Users Count by Content Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (run_id,instance) (audius_nm_primary_user_count{environment=~\"$env\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "User Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "User Status Percent (over time)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without (run_id,instance) (audius_nm_fully_synced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Fully synced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_partially_synced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Partially synced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_unsynced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Unsynced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_no_primary_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "No primary %"
    }
   ]
  },
  {
   "title": "User Status (current)",
   "type": "bargauge",
   "description": "The number of users whose content nodes are fully synced (i.e. clock values are all the same), partially synced (i.e. clock values are same one primary and one secondary), or unsynced (i.e. the primary isn't synced with either seondary)",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(audius_nm_fully_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "fully synced user count"
    },
    {
     "expr": "sum(audius_nm_partially_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "partially synced user count"
    },
    {
     "expr": "sum(audius_nm_unsynced_user_count{environment=~\"$env\"})",
     "legendFormat": "unsynced user count"
    },
    {
     "expr": "sum(audius_nm_no_primary_user_count{environment=~\"$env\"})",
     "legendFormat": "users with null primary count"
    }
   ]
  },
  {
   "title": "User Status Percent (current)",
   "type": "bargauge",
   "description": "The number of users whose content nodes are fully synced (i.e. clock values are all the same), partially synced (i.e. clock values are same one primary and one secondary), or unsynced (i.e. the primary isn't synced with either seondary)",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(audius_nm_fully_synced_user_count{environment=~\"$env\"}) / sum(audius_nm_user_count{environment=~\"$env\"}) * 100",
     "legendFormat": "fully synced user %"
    },
    {
     "expr": "sum(audius_nm_partially_synced_user_count{environment=~\"$env\"}) / sum(audius_nm_user_count{environment=~\"$env\"}) * 100",
     "legendFormat": "partially synced user %"
    },
    {
     "expr": "sum(audius_nm_unsynced_user_count{environment=~\"$env\"}) / sum(audius_nm_user_count{environment=~\"$env\"}) * 100",
     "legendFormat": "unsynced user count"
    },
    {
     "expr": "sum(audius_nm_no_primary_user_count{environment=~\"$env\"}) / sum(audius_nm_user_count{environment=~\"$env\"}) * 100",
     "legendFormat": "users with null primary count"
    }
   ]
  },
  {
   "title": "User Status Count by Primary",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (audius_nm_fully_synced_user_by_primary_count{environment=~\"$env\"})",
     "legendFormat": "fully synced - {{endpoint}}"
    },
    {
     "expr": "sum by(endpoint) (audius_nm_partially_synced_user_by_primary_count{environment=~\"$env\"})",
     "legendFormat": "partially synced - {{endpoint}}"
    },
    {
     "expr": "sum by(endpoint) (audius_nm_unsynced_user_by_primary_count{environment=~\"$env\"})",
     "legendFormat": "unsynced - {{endpoint}}"
    }
   ]
  },
  {
   "title": "User Status Count (over time) (linear)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (run_id,instance) (audius_nm_fully_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "Fully synced"
    },
    {
     "expr": "sum without (run_id,instance) (audius_nm_partially_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "Partially synced"
    },
    {
     "expr": "sum without (run_id,instance) (audius_nm_unsynced_user_count{environment=~\"$env\"})",
     "legendFormat": "Unsynced"
    },
    {
     "expr": "sum without (run_id,instance) (audius_nm_no_primary_user_count{environment=~\"$env\"})",
     "legendFormat": "No primary"
    }
   ]
  },
  {
   "title": "User Status Counts (over time) logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(audius_nm_fully_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "fully synced users"
    },
    {
     "expr": "sum(audius_nm_partially_synced_user_count{environment=~\"$env\"})",
     "legendFormat": "partially synced users"
    },
    {
     "expr": "sum(audius_nm_unsynced_user_count{environment=~\"$env\"})",
     "legendFormat": "unsynced users"
    },
    {
     "expr": "sum(audius_nm_no_primary_user_count{environment=~\"$env\"})",
     "legendFormat": "users with null primary"
    }
   ]
  },
  {
   "title": "[Deprecated] User Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Synced Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host) (audius_nm_fully_synced_user_count{environment=~\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Partially Synced Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host) (audius_nm_partially_synced_user_count{environment=~\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unsynced Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host) (audius_nm_unsynced_user_count{environment=~\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Users w/o Primary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host) (audius_nm_no_primary_user_count{environment=~\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Missed Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Latest Missed Users Count by Endpoint",
   "type": "barchart",
   "description": "The number of users skipped because of network monitoring job errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "audius_nm_missed_users_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Missed Users by Job",
   "type": "timeseries",
   "description": "The number of users skipped because of network monitoring job errors.\n\n--- \n\nMissed users can rise above the threshold if:\n\n* A Content Node goes down.\n* There's a bug indexing the content nodes.\n\nPlease check:\n\n* Content Node health status to confirm all nodes are online.\n* Content Node logs for `ERROR` messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(run_id) (audius_nm_missed_users_count{environment=~\"$env\"})",
     "legendFormat": "run {{run_id}}"
    }
   ]
  },
  { "title": "Job Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Durations",
   "type": "barchart",
   "description": "The amount of time it takes for the various steps in a network monitoring job to finish",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "audius_nm_total_job_duration{environment=~\"$env\"}",
     "legendFormat": "total job duration"
    },
    {
     "expr": "audius_nm_indexing_discovery_duration{environment=~\"$env\"}",
     "legendFormat": "indexing discovery duration"
    },
    {
     "expr": "audius_nm_indexing_content_duration{environment=~\"$env\"}",
     "legendFormat": "indexing content duration"
    },
    {
     "expr": "audius_nm_generating_metrics_duration{environment=~\"$env\"}",
     "legendFormat": "generating metrics duration"
    }
   ]
  },
  {
   "title": "Job Durations",
   "type": "timeseries",
   "description": "The amount of time it takes for the various steps in a network monitoring job to finish",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without (run_id) (audius_nm_total_job_duration{environment=~\"$env\"})",
     "legendFormat": "total job duration"
    },
    {
     "expr": "sum without (run_id) (audius_nm_indexing_discovery_duration{environment=~\"$env\"})",
     "legendFormat": "indexing discovery duration"
    },
    {
     "expr": "sum without (run_id) (audius_nm_indexing_content_duration{environment=~\"$env\"})",
     "legendFormat": "indexing content duration"
    },
    {
     "expr": "sum without (run_id) (audius_nm_generating_metrics_duration{environment=~\"$env\"})",
     "legendFormat": "generating metrics duration"
    }
   ]
  },
  {
   "title": "Avg Batch Duration by Endpoint",
   "type": "timeseries",
   "description": "The amount of time it takes for a batch of users to be fetched and saved to the network monitoring database",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(endpoint) (audius_nm_user_batch_duration{environment=~\"$env\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Status over Time (Dheeraj dev, do not use)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "audius_nm_fully_synced_user_count{environment=~\"$env\"}",
       "legendFormat": "fully synced users"
      },
      {
       "expr": "audius_nm_partially_synced_user_count{environment=~\"$env\"}",
       "legendFormat": "partially synced users"
      },
      {
       "expr": "audius_nm_unsynced_user_count{environment=~\"$env\"}",
       "legendFormat": "unsynced users"
      },
      {
       "expr": "audius_nm_no_primary_user_count{environment=~\"$env\"}",
       "legendFormat": "users with null primary"
      }
     ]
    }
   ]
  }
 ]
}