{
 "title": "Audius - Entity Manager",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(audius_dn_flask_route_duration_seconds_count{environment=~\"$env\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Errors by Entity Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "audius_dn_entity_manager_update_num_errors_sum",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "Number of Updates by Entity Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "audius_dn_entity_manager_update_num_changed_sum",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "Update Latency (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "audius_dn_entity_manager_update_latency_sum / audius_dn_entity_manager_update_latency_count",
     "legendFormat": "Latency (seconds)"
    }
   ]
  }
 ]
}