{
 "title": "Audius - Content Node - Syncs",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "sync_mode",
    "label": "Sync Mode",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, sync_mode)"
    }
   },
   {
    "name": "sync_type",
    "label": "Sync Type",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, sync_type)"
    }
   },
   {
    "name": "issue_sync_result",
    "label": "Issue Sync Result",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, result)"
    }
   },
   {
    "name": "process_sync_result",
    "label": "Process Sync Result",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_secondary_sync_from_primary_duration_seconds\", environment=~\"$env\"}, result)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Result for Issuing Outgoing Sync (Past Hour)",
     "type": "piechart",
     "description": "Counts for each result of issuing an outgoing sync request",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\"}[1h]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Hour)",
     "type": "stat",
     "description": "Percent Success for Issuing Outgoing Sync (Past Hour)",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\", sync_type=~\"$sync_type\"}[1h])) / (sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"success.*\"}[1h])) + sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"failure.*\"}[1h])))",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Result for Processing Incoming Sync (Past Hour)",
     "type": "piechart",
     "description": "Counts for each result of processing an incoming sync",
     "gridPos": { "h": 8, "w": 9, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", mode=~\"$sync_mode\"}[1h]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Hour)",
     "type": "stat",
     "description": "Percent Success for Processing Incoming Sync (Past Hour)",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[1h])) / (sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[1h])) + sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"failure.*\"}[1h])))",
       "legendFormat": "Successes"
      }
     ]
    },
    {
     "title": "Result for Issuing Outgoing Sync (Past Day)",
     "type": "piechart",
     "description": "Counts for each result of issuing an outgoing sync request",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\"}[24h]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Day)",
     "type": "stat",
     "description": "Percent Success for Issuing Outgoing Sync (Past Day)",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\", sync_type=~\"$sync_type\"}[24h])) / (sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"success.*\"}[24h])) + sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"failure.*\"}[24h])))",
       "legendFormat": "Successes"
      }
     ]
    },
    {
     "title": "Result for Processing Incoming Sync (Past Day)",
     "type": "piechart",
     "description": "Counts for each result of processing an incoming sync",
     "gridPos": { "h": 7, "w": 9, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", mode=~\"$sync_mode\"}[24h]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Day)",
     "type": "stat",
     "description": "Percent Success for Processing Incoming Sync (Past Day)",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[24h])) / (sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[24h])) + sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"failure.*\"}[24h])))",
       "legendFormat": "Successes"
      }
     ]
    },
    {
     "title": "Result for Issuing Outgoing Sync (Past Week)",
     "type": "piechart",
     "description": "Counts for each result of issuing an outgoing sync request",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\"}[7d]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Week)",
     "type": "stat",
     "description": "Percent Success for Issuing Outgoing Sync (Past Week)",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\", sync_type=~\"$sync_type\"}[7d])) / (sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"success.*\"}[7d])) + sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"failure.*\"}[7d])))",
       "legendFormat": "Successes"
      }
     ]
    },
    {
     "title": "Result for Processing Incoming Sync (Past Week)",
     "type": "piechart",
     "description": "Counts for each result of processing an incoming sync",
     "gridPos": { "h": 7, "w": 9, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", mode=~\"$sync_mode\"}[7d]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Success % (1 Week)",
     "type": "stat",
     "description": "Percent Success for Processing Incoming Sync (Past Week)",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[7d])) / (sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"success.*\"}[7d])) + sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_mode=~\"$sync_mode\", result=~\"failure.*\"}[7d])))",
       "legendFormat": "Successes"
      }
     ]
    }
   ]
  },
  {
   "title": "Syncs Issued vs Processed Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing vs Incoming Sync Successes (Aggregate)",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
      },
      {
       "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Issued Successfully Per Hour (Outgoing)"
      }
     ]
    },
    {
     "title": "Outgoing vs Incoming Sync Failures (Aggregate)",
     "type": "timeseries",
     "description": "Number of times per hour that a node fails when issuing+monitoring an outgoing sync request vs number of times per hour a node fails to process an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are failing for reasons that are tracked when processing syncs.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(le) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result!~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Issued Unsuccessfully Per Hour (Outgoing)"
      },
      {
       "expr": "sum by(le) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"failure_missing_wallet|failure_secondary_failure_count_threshold_met|failure_primary_sync_from_secondary|failure_issue_sync_request|failure_secondary_failed_to_progress\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Processed Unsuccessfully Per Hour (Incoming)"
      }
     ]
    },
    {
     "title": "Outgoing vs Incoming Sync Successes (Outliers)",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "Max Syncs Processed Successfully Per Hour (Incoming)"
      },
      {
       "expr": "min(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "Min Syncs Processed Successfully Per Hour (Incoming)"
      },
      {
       "expr": "max(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h]))",
       "legendFormat": "Max Syncs Issued Successfully Per Hour (Outgoing)"
      },
      {
       "expr": "min(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h]))",
       "legendFormat": "Min Syncs Issued Successfully Per Hour (Outgoing)"
      }
     ]
    }
   ]
  },
  {
   "title": "Syncs Issued vs Processed Per Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing vs Incoming Sync Successes $host",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 56 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success\", host=~\"$host\"}[1h])",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
      },
      {
       "expr": "increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success_clocks_already_match\", host=~\"$host\"}[1h])",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming No-op)"
      },
      {
       "expr": "sum by(host) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Issued Successfully Per Hour (Outgoing)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Sync - Failure Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Failures in the Last Minute",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.+\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Failures in the Last 10 Minutes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.+\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Failures in the Last Hour",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.+\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Failures in the Last Day",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.+\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Sync Failures Per Hour By Reason (Aggregate)",
     "type": "timeseries",
     "description": "Number of times per hour that processing a sync fails for each reason (aggregated across all hosts).",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(le, result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result!~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    },
    {
     "title": "Process Sync Failures Per Hour By Reason (Per Host)",
     "type": "timeseries",
     "description": "Number of times per hour that processing a sync fails for each reason per host.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(host, le, result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result!~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Sync - Duration Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Time Spent Processing (Aggregate)",
   "type": "timeseries",
   "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", result=~\"$process_sync_result\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", result=~\"$process_sync_result\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", result=~\"$process_sync_result\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", result=~\"$process_sync_result\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "$percentile Time Spent Processing (Per Host)",
   "type": "timeseries",
   "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile:raw}, sum by(host, le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", result=~\"$process_sync_result\"}[5m])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Process Sync - Duration by Success/Failure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent Processing Successful Sync (${percentile})",
     "type": "timeseries",
     "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary) that completes successfully.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by(host, le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Time Spent Processing Failed Sync ($percentile)",
     "type": "timeseries",
     "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary) that fails to complete for any reason.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(host, le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", result!~\"succes*\", host=~\"$host\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Time Spent Processing Failed Sync By Failure Reason ($percentile Per Host)",
     "type": "timeseries",
     "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary) that fails to complete for any reason.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(host, le, result) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", result!~\"succes*\", host=~\"$host\"}[5m])))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    },
    {
     "title": "Time Spent Processing Failed Sync By Failure Reason ($percentile Aggregate)",
     "type": "timeseries",
     "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary) that fails to complete for any reason.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(le, result) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", result!~\"succes*\", host=~\"$host\"}[5m])))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Issue and Wait for Outgoing Sync - Failure Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Issue Sync Request Failures Per Hour By Reason (Aggregate)",
     "type": "timeseries",
     "description": "Number of times per hour that Node A issues a sync request to Node B and sees a failure when monitoring Node B for sync completion (aggregated across all hosts)",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(le, result) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"failure_issue_sync_request|failure_secondary_failed_to_progress|failure_primary_sync_from_secondary|failure_missing_wallet|failure_secondary_failure_count_threshold_met\", host=~\"$host\"}[1h]))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    },
    {
     "title": "Issue Sync Request Failures Per Hour By Reason (Per Host)",
     "type": "timeseries",
     "description": "Number of times per hour that Node A issues a sync request to Node B and sees a failure when monitoring Node B for sync completion (aggregated across all hosts)",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(le, result, host) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"failure_issue_sync_request|failure_secondary_failed_to_progress|failure_primary_sync_from_secondary|failure_missing_wallet|failure_secondary_failure_count_threshold_met\", host=~\"$host\"}[1h]))",
       "legendFormat": "{{host}} {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Issue and Wait for Outgoing Sync - Duration Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent Waiting (Aggregate)",
     "type": "timeseries",
     "description": "Time that a node spends waiting for a sync request to be completed after issuing it (either for write quorum or state machine -- this is different from the node actually processing the sync).",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"$sync_mode\", host=~\"$host\", result=~\"$issue_sync_result\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"$sync_mode\", host=~\"$host\", result=~\"$issue_sync_result\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"$sync_mode\", host=~\"$host\", result=~\"$issue_sync_result\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"$sync_mode\", host=~\"$host\", result=~\"$issue_sync_result\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "$percentile Time Spent Waiting (Per Host)",
     "type": "timeseries",
     "description": "Time that a node spends waiting for a sync request to be completed after issuing it (either for write quorum or state machine -- this is different from the node actually processing the sync).",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(host, le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"$sync_mode\", host=~\"$host\", result=~\"$issue_sync_result\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Issue and Wait for Outgoing Sync - Duration By Success/Failure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent Waiting For Successful Sync ($percentile)",
     "type": "timeseries",
     "description": "Time that state machine jobs (recurring syncs) or write quorum (manual syncs) wait for a sync request to be completed on the secondary that they issued it to. This only counts when the sync was successful, including if another sync was required (e.g., the sync completed but the clock value on the secondary didn't fully catch up to the primary).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(host, le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", result=~\"success_mode_disabled|success_secondary_caught_up|success|success_secondary_partially_caught_up\", sync_mode=~\"$sync_mode\", host=~\"$host\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Time Spent Waiting For Failed Sync ($percentile)",
     "type": "timeseries",
     "description": "Time that state machine jobs (recurring syncs) or write quorum (manual syncs) wait for a sync request to be completed on the secondary that they issued it to. This only counts when the sync was unsuccessful.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(${percentile:raw}, sum by(host, le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", result=~\"failure_secondary_failure_count_threshold_met|failure_primary_sync_from_secondary|failure_issue_sync_request|failure_secondary_failed_to_progress|failure_missing_wallet\", sync_mode=~\"$sync_mode\", host=~\"$host\", sync_type=~\"$sync_type\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General Sync Count and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Issue Sync Request Counts by Host & Result",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", sync_type=~\"$sync_type\", sync_mode=~\"$sync_mode\"}[10m])",
     "legendFormat": "{{host}} // {{result}}"
    }
   ]
  },
  {
   "title": "issue_sync_request counts by host",
   "type": "timeseries",
   "description": "Count of all issue_sync_request jobs by Host, excluding success_mode_disabled",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(host) (increase(audius_cn_issue_sync_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\"}[10m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "issue_sync_request counts by result",
   "type": "timeseries",
   "description": "Count of all issue_sync_request jobs by Host, excluding success_mode_disabled",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by(result) (increase(audius_cn_issue_sync_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", sync_mode=~\"$sync_mode\", sync_type=~\"$sync_type\", result=~\"$issue_sync_result\"}[10m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Sync request duration by host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{host=~\"$host\", environment=~\"$env\", mode=~\"$sync_mode\", result=~\"$process_sync_result\"}[$__rate_interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Sync request duration by result ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, result) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{host=~\"$host\", environment=~\"$env\", mode=~\"$sync_mode\", result=~\"$process_sync_result\"}[$__rate_interval])))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Orphaned Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Orphaned Users By Node",
   "type": "timeseries",
   "description": "Number of wallets with orphaned data on each node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "audius_cn_recover_orphaned_data_wallet_counts{host=~\"$host\", environment=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hourly Syncs Issued to Recover Orphaned Data by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "increase(audius_cn_recover_orphaned_data_sync_counts{host=~\"$host\", environment=\"$env\"}[1h])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}