{
 "title": "Audius - Content Node - Profiling",
 "description": "Nodejs profiling and performance information",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$env\"}, path)"
    }
   },
   {
    "name": "method",
    "label": "Http Method",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$env\"}, method)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   },
   {
    "name": "status_code",
    "label": "HTTP Status Code",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$env\"}, status_code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage space total vs used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(audius_cn_storage_path_size_bytes{type=\"total\", environment=~\"$env\", host=~\"$host\"})",
     "legendFormat": "Total Storage"
    },
    {
     "expr": "sum(audius_cn_storage_path_size_bytes{type=\"used\", environment=~\"$env\", host=~\"$host\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Utilization %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(audius_cn_storage_path_size_bytes{type=\"used\", environment=~\"$env\", host=~\"$host\"}) / sum(audius_cn_storage_path_size_bytes{type=\"total\", environment=~\"$env\", host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent Disk Used by host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "audius_cn_storage_path_size_bytes{type=\"used\", environment=~\"$env\", host=~\"$host\"} / on(host) audius_cn_storage_path_size_bytes{type=\"total\", environment=~\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status Code Ratio Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"5.+\"}[1h]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"4.+\"}[1h]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"3.+\"}[1h]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"2.+\"}[1h]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Status Code Ratio in the Last Hour",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"5.+\"}[1h]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"4.+\"}[1h]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"3.+\"}[1h]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", method=~\"$method\", path=~\"$path\", host=~\"$host\", status_code=~\"2.+\"}[1h]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Http Status: 2XX Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_http_request_duration_seconds_sum{environment=~\"$env\", path=~\"$path\", host=~\"$host\", method=~\"$method\", status_code=~\"2.+\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Status: 4XX Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", method=~\"$method\", status_code=~\"4.+\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Status: 5XX Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", method=~\"$method\", status_code=~\"5.+\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Request counts by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (increase(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by Path ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, path) (rate(audius_cn_http_request_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", path=~\"$path\", status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request counts by Path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host, path) (increase(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{host}} -- '{{path}}'"
    }
   ]
  },
  {
   "title": "Latency by Host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, host) (rate(audius_cn_http_request_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", path=~\"$path\", status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request counts by Host, Path, and Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host, path, status_code) (increase(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", path=~\"$path\", status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{host}} -- '{{path}}' -- {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency by Host & Path ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, host, path) (rate(audius_cn_http_request_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\", path=~\"$path\", status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{host}} -- {{path}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage by Host (!!Assumes 16 cores!!)",
   "type": "timeseries",
   "description": "CPU-second is one second of time on a CPU.\nProcess execution time has two measurements:\nCPU time, or the amount of time that the CPU spent actively running the process; and\nWall time, or the amount of time that passes between you starting the process and the process ending.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(audius_cn_default_process_cpu_seconds_total{environment=~\"$env\", host=~\"$host\"}[$__rate_interval]) / 16",
     "legendFormat": "{{host}} - seconds"
    }
   ]
  },
  { "title": "Event Loop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "NodeJS Event Loop Lag by Host",
   "type": "timeseries",
   "description": "The lag in the nodejs event loop --- this is usually caused by blocking code taking too long e.g. job processors",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_eventloop_lag_mean_seconds{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "Mean - {{host}}"
    },
    {
     "expr": "audius_cn_default_nodejs_eventloop_lag_p99_seconds{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "P99 - {{host}}"
    }
   ]
  },
  { "title": "Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "NodeJS Heap % Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_heap_size_used_bytes{host=~\"$host\", environment=~\"$env\"} / 4000000000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NodeJS Heap Size Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_heap_size_used_bytes{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Open File Descriptors % by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "audius_cn_default_process_open_fds{environment=~\"$env\", host=~\"$host\"} / audius_cn_default_process_max_fds{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_cn_default_process_open_fds{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Garbage Collector Duration by Host (logarithmic) ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_default_nodejs_gc_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Garbage Collector Duration by Host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_default_nodejs_gc_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[$__rate_interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}