{
 "title": "Audius - Content Node - Update Replica Set",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   { "name": "issuedReconfig", "label": "Issued Reconfig", "query": "true,false" },
   {
    "name": "reconfigType",
    "label": "Reconfig Type",
    "query": {
     "query": "label_values(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count, reconfigType)"
    }
   },
   {
    "name": "result",
    "label": "Result",
    "query": {
     "query": "label_values(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count, result)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   }
  ]
 },
 "panels": [
  {
   "title": "Reconfigs in chosen time range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", reconfigType=~\"$reconfigType\", issuedReconfig=~\"$issuedReconfig\", result=~\"$result\", host=~\"$host\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconfigs in the Last Minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", reconfigType=~\"$reconfigType\", issuedReconfig=~\"$issuedReconfig\", result=~\"$result\", host=~\"$host\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconfigs in the Last 10 Minutes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", reconfigType=~\"$reconfigType\", issuedReconfig=~\"$issuedReconfig\", result=~\"$result\", host=~\"$host\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconfigs in the Last Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", reconfigType=~\"$reconfigType\", issuedReconfig=~\"$issuedReconfig\", result=~\"$result\", host=~\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconfigs in the Last Day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", reconfigType=~\"$reconfigType\", issuedReconfig=~\"$issuedReconfig\", result=~\"$result\", host=~\"$host\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IssueUpdateReplicaSet Job Counts by Host",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval]))",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum by(host) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.*\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "IssueUpdateReplicaSet Job Counts by Result",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(result) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "sum by(result) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.*\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "sum by(result) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success_issue_reconfig_disabled\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "IssueUpdateReplicaSet Job Counts by Host, Type, and Error",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval])",
     "legendFormat": "[issuedReconfig = true] {{host}} // {{reconfigType}} // result:{{result}}"
    },
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.*\", issuedReconfig=~\"$issuedReconfig\", reconfigType=~\"$reconfigType\"}[$__rate_interval])",
     "legendFormat": "[issuedReconfig = false] {{host}} // {{reconfigType}} // result:{{result}}"
    }
   ]
  }
 ]
}