{
 "title": "Audius - Content Node - Overview",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$env\"}, path)"
    }
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$env\"}, status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Exporting Content Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count without(host) (audius_cn_default_nodejs_version_info{environment=~\"$env\"}))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Users Entirely on Foundation Nodes %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"} / audius_nm_user_count{environment=~\"$env\"}",
     "legendFormat": "Users Entirely on Foundation Nodes"
    }
   ]
  },
  {
   "title": "Reconfigs in the Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Success for Issuing Outgoing Sync (Past Hour)",
   "type": "stat",
   "description": "Counts for each result of issuing an outgoing sync request",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success.*\"}[1h])) / sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[1h]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Percent Success for Processing Incoming Sync (Past Hour)",
   "type": "stat",
   "description": "Counts for each result of issuing an outgoing sync request",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success.*\"}[1h])) / (sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success.*\"}[1h])) + sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.*\"}[1h])))",
     "legendFormat": "Successes"
    }
   ]
  },
  { "title": "Network Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Users entirely on foundation nodes %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum without(run_id,instance) (audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"})) / (sum without(run_id,instance) (audius_nm_user_count{environment=~\"$env\"}))) * 100",
     "legendFormat": "Users entirely on foundation nodes"
    }
   ]
  },
  {
   "title": "Users Entirely on Foundation nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host) (audius_nm_users_with_all_foundation_node_replica_set{environment=~\"$env\"})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "All Users Count by Content Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (run_id,instance) (audius_nm_all_user_count{environment=~\"$env\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "User Status Percent (over time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without (run_id,instance) (audius_nm_fully_synced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Fully synced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_partially_synced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Partially synced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_unsynced_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "Unsynced %"
    },
    {
     "expr": "(sum without (run_id,instance) (audius_nm_no_primary_user_count{environment=~\"$env\"}) / sum without (run_id,instance) (audius_nm_user_count{environment=~\"$env\"})) * 100",
     "legendFormat": "No primary %"
    }
   ]
  },
  { "title": "Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Percent Disk Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "audius_cn_storage_path_size_bytes{type=\"used\", environment=~\"$env\", host=~\"$host\"} / on(host) audius_cn_storage_path_size_bytes{type=\"total\", environment=~\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Status Code Ratio Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", status_code=~\"5.+\"}[1h]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", status_code=~\"4.+\"}[1h]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", status_code=~\"3.+\"}[1h]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_count{environment=~\"$env\", path=~\"$path\", host=~\"$host\", status_code=~\"2.+\"}[1h]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Open File Descriptors by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "audius_cn_default_process_open_fds{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Host (!!Assumes 16 cores!!)",
   "type": "timeseries",
   "description": "CPU-second is one second of time on a CPU.\nProcess execution time has two measurements:\nCPU time, or the amount of time that the CPU spent actively running the process; and\nWall time, or the amount of time that passes between you starting the process and the process ending.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(audius_cn_default_process_cpu_seconds_total{environment=~\"$env\", host=~\"$host\"}[$__rate_interval]) / 16",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NodeJS Heap Size Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_heap_size_used_bytes{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bull Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Success Rate by Host",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(host) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", host=~\"$host\"}[1h])) / (sum by(host) (rate(audius_cn_jobs_failed_total{environment=~\"$env\", host=~\"$host\"}[1h])) + sum by(host) (rate(audius_cn_jobs_completed_total{environment=~\"$env\", host=~\"$host\"}[1h])))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Syncs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing vs Incoming Sync Successes (Aggregate)",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
      },
      {
       "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Issued Successfully Per Hour (Outgoing)"
      },
      {
       "expr": "sum by(le) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result!~\"success|success_clocks_already_match\", host=~\"$host\"}[1h]))",
       "legendFormat": " Syncs Processed Unsuccessfully Per Hour (Incoming)"
      },
      {
       "expr": "sum by(le) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"failure_missing_wallet|failure_secondary_failure_count_threshold_met|failure_primary_sync_from_secondary|failure_issue_sync_request|failure_secondary_failed_to_progress\", host=~\"$host\"}[1h]))",
       "legendFormat": " Syncs Issued Unsuccessfully Per Hour (Outgoing)"
      }
     ]
    },
    {
     "title": "Outgoing Sync Counts by host",
     "type": "timeseries",
     "description": "Count of all issue_sync_request jobs by Host, excluding success_mode_disabled",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum by(host) (increase(audius_cn_issue_sync_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\"}[10m]))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Incoming Sync Counts by host",
     "type": "timeseries",
     "description": "Count of all incoming syncs by Host",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "sum by(host) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[1h]))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Outgoing Sync Success % by Host",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(host) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success|success_secondary_caught_up|success_secondary_partially_caught_up|success_mode_disabled\", host=~\"$host\"}[1h])) / sum by(host) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
      }
     ]
    },
    {
     "title": "Incoming Sync Success %  by Host",
     "type": "timeseries",
     "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(host) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success|success_clocks_already_match\", host=~\"$host\"}[1h])) / sum by(host) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[1h]))",
       "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
      }
     ]
    },
    {
     "title": "p99 Time Spent Processing (Per Host)",
     "type": "timeseries",
     "description": "Time that a node spends processing a sync (i.e., a secondary syncing from a primary).",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(host, le) (rate(audius_cn_secondary_sync_from_primary_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[5m])))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  { "title": "Update Replica Set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "IssueUpdateReplicaSet Job Counts by Host and Result",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success|success.*\"}[$__rate_interval])",
     "legendFormat": "[issuedReconfig = true] {{host}} // {{reconfigType}} // result:{{result}}"
    },
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.*\"}[$__rate_interval])",
     "legendFormat": "[issuedReconfig = false] {{host}} // {{reconfigType}} // result:{{result}}"
    }
   ]
  },
  {
   "title": "IssueUpdateReplicaSet Success by Host",
   "type": "timeseries",
   "description": "Success rate of users updating their replica set \n\n---\n\nAn issue with this could mean something is wrong with the queues or a performance bottleneck",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success.*\"}[24h])) / (sum by(host) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"failure.+\"}[24h])) + sum by(host) (increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", result=~\"success.*\"}[24h])))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}