{
 "title": "Audius - Governance",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(audius_dn_flask_route_duration_seconds_count{environment=~\"$env\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Proposals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Proposals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_exporters_sdk_proposals{outcome=\"InProgress\"}",
     "legendFormat": "Open Proposals"
    }
   ]
  },
  {
   "title": "Open Proposals",
   "type": "timeseries",
   "description": "The number of open proposals at the moment.\n\n---\n\nThe number open proposals should typically be 2 (upgrading content and discovery versions).\n\n3 opened PRs at the same time will escalate to on-call.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_exporters_sdk_proposals{outcome=\"InProgress\"}",
     "legendFormat": "Open Proposals"
    }
   ]
  },
  {
   "title": "Latest Proposal ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(audius_exporters_sdk_proposals)"
    }
   ]
  },
  {
   "title": "New Proposals",
   "type": "timeseries",
   "description": "The number of new proposals within the last 24 hours.\n\n---\n\n>= 3 should trigger multiple alarms (including this one) since an attacker may be self-signing multiple proposals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(audius_exporters_sdk_proposals) - sum(audius_exporters_sdk_proposals offset 1d OR on() vector(89))",
     "legendFormat": "New Proposals"
    }
   ]
  },
  {
   "title": "Proposals by Unknown Proposers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_exporters_sdk_proposals_by_unknown_proposers",
     "legendFormat": "Unknown Proposers"
    }
   ]
  },
  {
   "title": "Proposals by Unknown Proposers",
   "type": "timeseries",
   "description": "The number of proposals opened by unknown proposers.\n\n---\n\nWe ignore any previous one-off proposers to keep this metric at 0. Anything greater than 0 should be considered to be created by an attacker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "audius_exporters_sdk_proposals_by_unknown_proposers",
     "legendFormat": "Unknown Proposers"
    }
   ]
  },
  { "title": "SDK Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "SDK Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_exporters_sdk_api_failure",
     "legendFormat": "failures"
    }
   ]
  }
 ]
}