{
 "title": "Audius - Content Node - Uploads",
 "tags": [ "content" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.5, p90 : 0.9, p95 : 0.95, p99 : 0.99"
   }
  ]
 },
 "panels": [
  { "title": "Manual Syncs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outgoing vs Incoming Manual Sync Successes (Aggregate)",
   "type": "timeseries",
   "description": "Number of times per hour that a node successfully issues an outgoing sync request vs number of times per hour a node successfully processes an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are processed correctly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result=~\"success.*\", host=~\"$host\"}[1h]))",
     "legendFormat": "Syncs Processed Successfully Per Hour (Incoming)"
    },
    {
     "expr": "sum(increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"success.*\", host=~\"$host\", sync_type=~\"manual\"}[1h]))",
     "legendFormat": "Manual Syncs Issued Successfully Per Hour (Outgoing)"
    }
   ]
  },
  {
   "title": "Outgoing vs Incoming Manual Sync Failures (Aggregate)",
   "type": "timeseries",
   "description": "Number of times per hour that a node fails when issuing+monitoring an outgoing sync request vs number of times per hour a node fails to process an incoming sync request (aggregated across all nodes). These should be very similar to indicate that outgoing syncs are failing for reasons that are tracked when processing syncs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(le) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_count{environment=~\"$env\", result!~\"success.*\", host=~\"$host\"}[1h]))",
     "legendFormat": "Syncs Issued Unsuccessfully Per Hour (Outgoing)"
    },
    {
     "expr": "sum by(le) (increase(audius_cn_issue_sync_request_duration_seconds_count{environment=~\"$env\", result=~\"failure.+\", host=~\"$host\", sync_type=~\"manual\"}[1h]))",
     "legendFormat": "Manual Syncs Processed Unsuccessfully Per Hour (Incoming)"
    }
   ]
  },
  {
   "title": "Time Spent Waiting For Manual Syncs ($percentile) (logarithmic)",
   "type": "timeseries",
   "description": "Time that write quorum (manual syncs) wait for a sync request to be completed on the secondary that they issued it to",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(host, le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"sync_secondary_from_primary\", sync_type=~\"manual\", result=~\"success.*\"}[1h])))",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(host, le) (rate(audius_cn_issue_sync_request_duration_seconds_bucket{environment=~\"$env\", sync_mode=~\"sync_secondary_from_primary\", sync_type=~\"manual\", result=~\"failure.+\"}[1h])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Trancoding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Current Rates of jobs per hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": " jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(audius_cn_jobs_active_total{host=~\"$host\", queue_name=~\"asyncProcessing\", environment=~\"$env\"}[1h]))",
     "legendFormat": "processed / hour"
    }
   ]
  },
  {
   "title": "AsyncProcessingQueue Duration by Host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"asyncProcessing\", host=~\"$host\", status!=\"failed\"}[$__rate_interval])))",
     "legendFormat": "succeeded {{host}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le, host) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"asyncProcessing\", host=~\"$host\", status=\"failed\"}[$__rate_interval])))",
     "legendFormat": "failed - {{host}}"
    }
   ]
  },
  {
   "title": "AsyncProcessingQueue Duration by Job Name ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, job_name) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"asyncProcessing\", host=~\"$host\", status!=\"failed\"}[$__rate_interval])))",
     "legendFormat": "succeeded {{job_name}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le, job_name) (rate(audius_cn_jobs_duration_seconds_bucket{environment=~\"$env\", queue_name=~\"asyncProcessing\", host=~\"$host\", status=\"failed\"}[$__rate_interval])))",
     "legendFormat": "failed - {{job_name}}"
    }
   ]
  },
  { "title": "Write Quorum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Write Quorum Duration by Host ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by(le, host, result) (rate(audius_cn_write_quorum_duration_seconds_bucket{environment=~\"$env\", enforceWriteQuorum=\"true\", host=~\"$host\", result=~\"succeeded\"}[1h])))",
     "legendFormat": "{{result}} - {{host}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum by(le, host, result) (rate(audius_cn_write_quorum_duration_seconds_bucket{environment=~\"$env\", enforceWriteQuorum=\"true\", host=~\"$host\", result=~\"failed.*\"}[1h])))",
     "legendFormat": "{{result}} - {{host}}"
    }
   ]
  }
 ]
}