{
 "title": "Audius - Content Node - Misc - Sid",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$env\"}, host)"
    }
   },
   {
    "name": "sync_mode",
    "label": "Sync Mode",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, sync_mode)"
    }
   },
   {
    "name": "sync_result",
    "label": "Sync Result",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, result)"
    }
   },
   {
    "name": "sync_type",
    "label": "Sync Type",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_issue_sync_request_duration_seconds_bucket\", environment=~\"$env\"}, sync_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NodeJS Heap Size Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_heap_size_used_bytes{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bull Jobs Waiting by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(host) (audius_cn_jobs_waiting_total{host=~\"$host\", environment=~\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS Event Loop Lag by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "audius_cn_default_nodejs_eventloop_lag_mean_seconds{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "Mean - {{host}}"
    },
    {
     "expr": "audius_cn_default_nodejs_eventloop_lag_p99_seconds{host=~\"$host\", environment=~\"$env\"}",
     "legendFormat": "P99 - {{host}}"
    }
   ]
  },
  {
   "title": "CPU Seconds Rate by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(audius_cn_default_process_cpu_seconds_total{environment=~\"$env\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request counts by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(host,path) (rate(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\"}[10m]))",
     "legendFormat": "{{host}} -- '{{path}}'"
    }
   ]
  },
  {
   "title": "Total HTTP request durations by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(host) (rate(audius_cn_http_request_duration_seconds_sum{host=~\"$host\", environment=~\"$env\"}[10m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NodeJS Heap Size Used by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(audius_cn_default_nodejs_heap_size_used_bytes{host=~\"$host\", environment=~\"$env\"}) / 1000 / 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "issue_sync_request counts by host",
   "type": "timeseries",
   "description": "Count of all issue_sync_request jobs by Host, excluding success_mode_disabled",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum without(sync_type, result) (increase(audius_cn_issue_sync_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\", sync_mode=~\"$sync_mode\", result!~\"success_mode_disabled\"}[10m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total HTTP Request counts by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(host) (rate(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$env\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IssueUpdateReplicaSet Job Counts by Node, Type, and Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", issuedReconfig=~\"true\"}[30m])",
     "legendFormat": "[issuedReconfig = true] {{host}} // {{reconfigType}} // result:{{result}}"
    },
    {
     "expr": "increase(audius_cn_state_machine_update_replica_set_queue_job_duration_seconds_count{environment=~\"$env\", host=~\"$host\", issuedReconfig=~\"false\"}[30m])",
     "legendFormat": "[issuedReconfig = false] {{host}} // {{reconfigType}} // result:{{result}}"
    }
   ]
  },
  {
   "title": "Sync request durations by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum without(status_code) (rate(audius_cn_http_request_duration_seconds_sum{host=~\"$host\", environment=~\"$env\", path=~\"/sync\"}[10m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Issue Sync Request Counts by Host & Result",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "increase(audius_cn_issue_sync_request_duration_seconds_count{environment=\"$env\", host=~\"$host\", sync_type=~\"$sync_type\", sync_mode=~\"$sync_mode\"}[3h])",
     "legendFormat": "{{host}} // {{result}}"
    }
   ]
  },
  {
   "title": "Sync request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum without(result) (increase(audius_cn_secondary_sync_from_primary_duration_seconds_sum{host=~\"$host\", environment=~\"$env\"}[10m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Issue Sync Request Counts by Host & Result (Foundation Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(audius_cn_issue_sync_request_duration_seconds_count{environment=\"$env\", host=~\"usermetadata.audius.co|content-node.audius.co|creatornode.audius.co|creatornode2.audius.co|creatornode3.audius.co\", sync_type=~\"$sync_type\", sync_mode=~\"$sync_mode\"}[3h])",
     "legendFormat": "{{host}} ~~ {{result}}"
    }
   ]
  },
  { "title": "Duration Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } }
 ]
}