{
 "title": "Discovery Provider",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(audius_dn_flask_route_latency_seconds_count, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(audius_dn_flask_route_latency_seconds_count, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blockdiff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_dn_health_check_block_difference_current{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latest Indexed Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "audius_dn_health_check_latest_indexed_block_num_current{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Census", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Census (Population)",
   "type": "timeseries",
   "description": "[Census](https://github.com/AudiusProject/load-test-tools/tree/master/census) is a load-test-tool that runs periodically to count the total number of entities that are stored at the database level.\n\nThe population panel shows the total number of entities to date.\n\nThe daily growth panel shows the growth per entity within the past ISO date.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_lt_census_population_current{environment=~\"$env\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Census (Today's Growth)",
   "type": "timeseries",
   "description": "[Census](https://github.com/AudiusProject/load-test-tools/tree/master/census) is a load-test-tool that runs periodically to count the total number of entities that are stored at the database level.\n\nThe population panel shows the total number of entities to date.\n\nThe daily growth panel shows the growth per entity within the past ISO date.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_lt_census_growth_current{environment=~\"$env\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  { "title": "Flask Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Route Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max by (route) (rate(audius_dn_flask_route_latency_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}{{route}}"
    }
   ]
  },
  {
   "title": "Average Flask Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (route) (rate(audius_dn_flask_route_latency_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_flask_route_latency_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Route Requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max by (host, route, code) (rate(audius_dn_flask_route_latency_seconds_count{code!=\"200\", code!=\"\", environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}{{route}} ({{code}})"
    }
   ]
  },
  { "title": "Aggregate Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Aggregate Task Runs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_dn_update_aggregate_table_latency_seconds_count{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Average Aggregate Task Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(audius_dn_update_aggregate_table_latency_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_update_aggregate_table_latency_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m])",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  { "title": "Index Metrics Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Index Metric Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "audius_dn_index_metrics_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Average Index Metrics Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(audius_dn_index_metrics_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_index_metrics_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Average Index Block Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (scope) (rate(audius_dn_index_blocks_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_index_blocks_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}{{scope}}"
    }
   ]
  },
  { "title": "State Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Average Track State Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (scope) (rate(audius_dn_track_state_update_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_track_state_update_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}{{scope}}"
    }
   ]
  },
  {
   "title": "Average User State Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (scope) (rate(audius_dn_user_state_update_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_user_state_update_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}{{scope}}"
    }
   ]
  },
  { "title": "Trending Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Average Index Trending Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (service) (rate(audius_dn_index_trending_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_index_trending_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "index_trending_runtime"
    }
   ]
  },
  {
   "title": "Average Update Trending View Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (mat_view_name) (rate(audius_dn_update_trending_view_runtime_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(audius_dn_update_trending_view_runtime_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
     "legendFormat": "{{mat_view_name}}"
    }
   ]
  },
  { "title": "Celery Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "In Progress Runtimes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "audius_dn_celery_running_tasks{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}