{
 "title": "Joaquin - Discovery Provider",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(audius_dn_flask_route_latency_seconds_count, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(audius_dn_flask_route_latency_seconds_count{environment=~\"$env\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Celery Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Celery Task (Durations)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (func_name) (audius_dn_completed_celery_task_duration_seconds_sum{environment=~\"$env\", host=~\"$host\", success=\"True\"} / audius_dn_completed_celery_task_duration_seconds_count{environment=~\"$env\", host=~\"$host\", success=\"True\"})",
     "legendFormat": "{{func_name}}"
    }
   ]
  },
  {
   "title": "Celery Tasks (Active)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "audius_dn_active_celery_task_duration_seconds{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Last Successful Celery Task Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "audius_dn_last_celery_task_duration_seconds{environment=~\"$env\", host=~\"$host\", success=\"True\"}",
     "legendFormat": "{{func_name}}"
    }
   ]
  }
 ]
}