{
 "title": "Network Monitoring",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Primary Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users with a specific content node as their primary",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "primary_user_count{host=\"discoveryprovider2.staging.audius.co\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "All Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users that have a specific content node in their replica set",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "all_user_count{host=\"discoveryprovider2.staging.audius.co\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Fully Synced User Count",
   "type": "gauge",
   "description": "The number of users whose content nodes are fully synced (i.e. clock values are all the same)",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "full_synced_user_count{host=\"discoveryprovider2.staging.audius.co\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}