{
 "title": "Vickys dashboard",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"audius_dn_flask_route_duration_seconds_count|audius_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_default_nodejs_heap_space_size_total_bytes\", environment=~\"$environment\"}, host)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$environment\"}, path)"
    }
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$environment\"}, status_code)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values({__name__=~\"audius_cn_http_request_duration_seconds_count\", environment=~\"$environment\"}, method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration by Path",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (path, method, status_code) (rate(audius_cn_http_request_duration_seconds_sum{environment=~\"$environment\", host=~\"$host\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}[5m]) / rate(audius_cn_http_request_duration_seconds_count{environment=~\"$environment\", host=~\"$host\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}[5m]))",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    },
    {
     "expr": "sum(rate(audius_cn_http_request_duration_seconds_sum{host=~\"$host\", environment=~\"$environment\", status_code=~\"$status_code\", method=~\"$method\"}[5m])) / sum(rate(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$environment\", status_code=~\"$status_code\", method=~\"$method\"}[5m]))",
     "legendFormat": "AVERAGE"
    }
   ]
  },
  {
   "title": "Health Check Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (path, method, status_code) (rate(audius_cn_http_request_duration_seconds_sum{environment=~\"$environment\", host=~\"$host\", path=~\"(/health_check|/health_check/verbose)\", status_code=~\"$status_code\", method=~\"$method\"}[5m]) / rate(audius_cn_http_request_duration_seconds_count{environment=~\"$environment\", host=~\"$host\", path=~\"(/health_check|/health_check/verbose)\", status_code=~\"$status_code\", method=~\"$method\"}[5m]))",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Bucketing for all Content Node Routes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_cn_http_request_duration_seconds_bucket{host=~\"$host\", environment=~\"$environment\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Routes that take the longest",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max by (path) (rate(audius_cn_http_request_duration_seconds_sum{host=~\"$host\", environment=~\"$environment\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}[5m]) / rate(audius_cn_http_request_duration_seconds_count{host=~\"$host\", environment=~\"$environment\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}[5m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Bucketing for all Content Node Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Bucketing for $path",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "repeat": "path",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audius_cn_http_request_duration_seconds_bucket{host=~\"$host\", environment=~\"$environment\", path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Route durations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{le}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{le}} "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{le}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{le}} "
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(audius_cn_http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\", method=~\"$method\", environment=~\"$environment\", host=~\"$host\"}[5m])) by (le))",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Write Quorum Durations (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(audius_cn_write_quorum_duration_seconds_bucket{environment=~\"$environment\", host=~\"$host\", enforceWriteQuorum=\"true\"}[$__rate_interval])))",
     "legendFormat": "Write Quorum Duration"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "audius_cn_http_request_duration_seconds_bucket{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "active requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "audius_cn_default_process_open_fds{environment=~\"$environment\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}