version: '3'
services:
  discovery-provider-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_discovery
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - audius_dev
  redis-server:
    image: redis:3.0-alpine
    command: redis-server --save '' 
    ports:
      - '5379:6379'
    networks:
      - audius_dev

volumes:
  postgres_data:

networks:
  audius_dev:
    external: true