FROM --platform=linux/amd64 rust:1.60.0 AS bpf-builder

WORKDIR /usr/src/app

ENV PATH="/root/solana-release/bin:${PATH}"
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y build-essential libudev-dev libhidapi-dev pkg-config libssl-dev git nodejs && \
    npm install -g yarn @project-serum/anchor-cli@0.24.1 && \
    curl -SfL https://github.com/solana-labs/solana/releases/download/v1.10.11/solana-release-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf - -C $HOME

ENV CARGO_INCREMENTAL=1

ARG AUDIUS_ETH_REGISTRY_PRIVATE_KEY
ARG TRACK_LISTEN_COUNT_PRIVATE_KEY
ARG CLAIMABLE_TOKENS_PRIVATE_KEY
ARG REWARD_MANAGER_PRIVATE_KEY

COPY . .
RUN --mount=type=cache,target=/usr/src/app/target \
    --mount=type=cache,target=/root/.cache/solana \
    --mount=type=cache,target=/usr/local/cargo/registry \
    ./scripts/update-keys.sh && \
    cargo build-bpf && \
    mkdir -p artifacts/main-target && \
    cp -r target/deploy/ artifacts/main-target && \
    cd anchor/audius-data && anchor build && cd ../.. && \
    mkdir -p artifacts/audius-data-target && \
    cp -r anchor/audius-data/target/deploy artifacts/audius-data-target && \
    cp -r anchor/audius-data/target/idl artifacts/audius-data-target && \
    cp -r anchor/audius-data/target/types artifacts/audius-data-target

# ------

FROM rust:1.60.0

WORKDIR /usr/src/app

ENV CARGO_INCREMENTAL=1

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y clang cmake build-essential libudev-dev libhidapi-dev pkg-config libssl-dev git nodejs && \
    npm install -g yarn @project-serum/anchor-cli@0.24.1

ENV PATH="/root/solana-release/bin:${PATH}"
COPY scripts/install-solana.sh /tmp/install-solana.sh
RUN --mount=type=cache,target=/usr/local/cargo/registry /tmp/install-solana.sh

COPY anchor/audius-data/package.json anchor/audius-data/yarn.lock anchor/audius-data/
RUN cd anchor/audius-data && yarn install

ARG AUDIUS_ETH_REGISTRY_PRIVATE_KEY
ARG TRACK_LISTEN_COUNT_PRIVATE_KEY
ARG CLAIMABLE_TOKENS_PRIVATE_KEY
ARG REWARD_MANAGER_PRIVATE_KEY
ARG AUDIUS_DATA_PRIVATE_KEY
ARG owner_private_key
ARG feepayer_private_key
ARG token_private_key
ARG admin_authority_private_key
ARG admin_account_private_key
ARG signer_group_private_key
ARG valid_signer_private_key
ARG reward_manager_pda_private_key
ARG reward_manager_token_pda_private_key
ARG valid_signer_eth_address

COPY . .
COPY --from=bpf-builder /usr/src/app/artifacts/main-target target
COPY --from=bpf-builder /usr/src/app/artifacts/audius-data-target anchor/audius-data/target

RUN --mount=type=cache,target=/usr/src/app/target \
    --mount=type=cache,target=/root/.cache/solana \
    --mount=type=cache,target=/usr/local/cargo/registry \
    ./scripts/setup-predeployed.sh /usr/db && \
    cp -r anchor/audius-data/target/idl anchor/audius-data/

HEALTHCHECK --interval=5s --timeout=5s --retries=10 \
    CMD solana balance CMRCuQcnbzHzQfDRZfkfAXM9TKce1X6LjHhSLqQc68WU || exit 1

# Used by latest tag (default)
CMD [ "solana-test-validator", "--ledger", "/usr/db" ]

# Used by m1-slow tag. Default slots per epoch is 8192. Default ticks per slot is 64. See https://github.com/solana-labs/solana/blob/master/sdk/program/src/clock.rs
# CMD [ "solana-test-validator", "--ledger", "/usr/db", "--slots-per-epoch", "100", "--ticks-per-slot", "32", "--no-bpf-jit", "--reset" ]
