FROM rust:1.60.0

WORKDIR /usr/src/app

ENV PATH="/root/solana-release/bin:${PATH}"
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y jq build-essential libudev-dev libhidapi-dev pkg-config libssl-dev git nodejs && \
    npm install -g yarn @project-serum/anchor-cli@0.24.1 && \
    curl -SfL https://github.com/solana-labs/solana/releases/download/v1.10.11/solana-release-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf - -C $HOME

COPY anchor/audius-data/package.json anchor/audius-data/yarn.lock anchor/audius-data/
RUN cd anchor/audius-data && yarn install

ENV CARGO_INCREMENTAL=1

ARG AUDIUS_ETH_REGISTRY_PRIVATE_KEY
ARG TRACK_LISTEN_COUNT_PRIVATE_KEY
ARG CLAIMABLE_TOKENS_PRIVATE_KEY
ARG REWARD_MANAGER_PRIVATE_KEY
ARG AUDIUS_DATA_PRIVATE_KEY
ARG owner_private_key
ARG feepayer_private_key
ARG token_private_key
ARG admin_authority_private_key
ARG admin_account_private_key
ARG signer_group_private_key
ARG valid_signer_private_key
ARG reward_manager_pda_private_key
ARG reward_manager_token_pda_private_key
ARG valid_signer_eth_address

COPY . .
RUN --mount=type=cache,target=/usr/src/app/target \
    --mount=type=cache,target=/usr/src/app/anchor/audius-data/target \
    --mount=type=cache,target=/root/.cache/solana \
    --mount=type=cache,target=/usr/local/cargo/registry \
    ./scripts/setup-predeployed.sh /usr/db && \
    cp -r anchor/audius-data/target/idl anchor/audius-data/

HEALTHCHECK --interval=5s --timeout=5s --retries=10 \
    CMD solana balance CMRCuQcnbzHzQfDRZfkfAXM9TKce1X6LjHhSLqQc68WU || exit 1

CMD [ "solana-test-validator", "--ledger", "/usr/db" ]
