// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reads.sql

package db

import (
	"context"
)

const getKey = `-- name: GetKey :one
select id, key, value, tx_hash, created_at, updated_at from core_kvstore where key = $1
`

func (q *Queries) GetKey(ctx context.Context, key string) (CoreKvstore, error) {
	row := q.db.QueryRow(ctx, getKey, key)
	var i CoreKvstore
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
