// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reads.sql

package db

import (
	"context"
)

const getKey = `-- name: GetKey :one
select id, key, value, tx_hash, created_at, updated_at from core_kvstore where key = $1
`

func (q *Queries) GetKey(ctx context.Context, key string) (CoreKvstore, error) {
	row := q.db.QueryRow(ctx, getKey, key)
	var i CoreKvstore
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTx = `-- name: GetTx :one
select rowid, block_id, index, created_at, tx_hash, tx_result from core_tx_results where tx_hash = $1 limit 1
`

func (q *Queries) GetTx(ctx context.Context, txHash string) (CoreTxResult, error) {
	row := q.db.QueryRow(ctx, getTx, txHash)
	var i CoreTxResult
	err := row.Scan(
		&i.Rowid,
		&i.BlockID,
		&i.Index,
		&i.CreatedAt,
		&i.TxHash,
		&i.TxResult,
	)
	return i, err
}
