export const REACTION_LONGPRESS_DELAY = 100
export const REACTION_CONTAINER_HEIGHT = 70
export const REACTION_CONTAINER_TOP_OFFSET = 20
export const BACKGROUND_OPACITY = 0.3
export const MOUNT_ANIMATION_DURATION_MS = 100
export const UNMOUNT_ANIMATION_DURATION_MS = 100
export const END_REACHED_OFFSET = 100
