FROM alpine as certs

RUN apk update && apk add --no-cache ca-certificates

FROM scratch

WORKDIR /bin

COPY ./bin/core-amd64 ./core

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

CMD ["./core"]
