#!/bin/env bash

set -eo pipefail

PRUNE_THRESHOLD=70
FULL_PRUNE_THRESHOLD=50

function disk_usage_above_threshold() {
    threshold="$1"
    disk_usage_pct="$(df | grep /dev/root | awk '{print $5}' | grep -oP "^\d+")"
    echo "Disk usage at ${disk_usage_pct}%"
    [ "$disk_usage_pct" -gt "$threshold" ]
}

if disk_usage_above_threshold $PRUNE_THRESHOLD; then
    echo "Cleaning up docker..."
    docker system prune -f
    if disk_usage_above_threshold $FULL_PRUNE_THRESHOLD; then
        echo "Disk usage exceeds full prune threshold, perfoming full cleanup..."
        docker system prune -af
    fi
fi
