import { SquareSizes } from '@audius/common/models'
import { Id, developmentConfig } from '@audius/sdk'

import { artistUser } from './users'

const { apiEndpoint } = developmentConfig.network

export const testCollection = {
  id: Id.parse(1),
  playlist_name: 'Test Collection',
  user_id: artistUser.id,
  permalink: '/test-user/test-collection',
  repost_count: 10,
  favorite_count: 5,
  total_play_count: 0,
  track_count: 0,
  blocknumber: 0,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  is_album: false,
  is_image_autogenerated: false,
  is_delete: false,
  is_private: false,
  is_stream_gated: false,
  is_scheduled_release: false,
  has_current_user_reposted: false,
  has_current_user_saved: false,
  playlist_contents: [],
  added_timestamps: [],
  followee_reposts: [],
  followee_favorites: [],
  artwork: {
    [SquareSizes.SIZE_150_BY_150]: `${apiEndpoint}/image-collection-small.jpg`,
    [SquareSizes.SIZE_480_BY_480]: `${apiEndpoint}/image-collection-medium.jpg`,
    mirrors: [apiEndpoint]
  },
  access: { stream: true },
  user: artistUser
}
