FROM node:18

WORKDIR /app

COPY package*.json ./
ENV DASHBOARD_BASE_URL="/dashboard/"
RUN npm install

WORKDIR /app/protocol-dashboard
COPY .env* index.html tsconfig.json tsconfig.node.json vite.config.ts ./
COPY src ./src
COPY scripts ./scripts
COPY public ./public
COPY types ./types

CMD npm run start:stage
