FROM node:18

WORKDIR /app

COPY package*.json ./
ENV DASHBOARD_BASE_URL="/dashboard/"
RUN npm install --legacy-peer-deps
COPY .env* index.html tsconfig.json tsconfig.node.json vite.config.ts ./
COPY src ./src
COPY scripts ./scripts
COPY public ./public
COPY types ./types

RUN npm run start:stage
