module.exports = {
  CREATOR_NODE_SERVICE_NAME: 'creator-node',
  DECISION_TREE_STATE: Object.freeze({
    GET_ALL_SERVICES: 'GET ALL SERVICES',
    FILTERED_TO_WHITELIST: 'FILTERED TO WHITELIST',
    FILTERED_FROM_BLACKLIST: 'FILTERED FROM BLACKLIST',
    FILTERED_OUT_UNHEALTHY_AND_OUTDATED: 'FILTERED OUT UNHEALTHY AND OUTDATED',
    FILTERED_OUT_SYNC_IN_PROGRESS: 'FILTERED OUT SYNC IN PROGRESS',
    SELECTED_PRIMARY_AND_SECONDARIES: 'SELECTED PRIMARY AND SECONDARIES'
  })
}
