# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: etl/v1/service.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'etl/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.tasks.core.audiusd_gen.etl.v1 import types_pb2 as etl_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65tl/v1/service.proto\x12\x06\x65tl.v1\x1a\x12\x65tl/v1/types.proto2\xc6\x01\n\nETLService\x12\x33\n\x04Ping\x12\x13.etl.v1.PingRequest\x1a\x14.etl.v1.PingResponse\"\x00\x12\x42\n\tGetHealth\x12\x18.etl.v1.GetHealthRequest\x1a\x19.etl.v1.GetHealthResponse\"\x00\x12?\n\x08GetPlays\x12\x17.etl.v1.GetPlaysRequest\x1a\x18.etl.v1.GetPlaysResponse\"\x00\x42\x31Z/github.com/AudiusProject/audiusd/pkg/api/etl/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'etl.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/AudiusProject/audiusd/pkg/api/etl/v1'
  _globals['_ETLSERVICE']._serialized_start=53
  _globals['_ETLSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
