# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: etl/v1/types.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'etl/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65tl/v1/types.proto\x12\x06\x65tl.v1\"\r\n\x0bPingRequest\"(\n\x0cPingResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"\x12\n\x10GetHealthRequest\"\x13\n\x11GetHealthResponse\"\x9e\x01\n\x0fGetPlaysRequest\x12\x32\n\npagination\x18\x01 \x01(\x0b\x32\x12.etl.v1.PaginationR\npagination\x12#\n\x05order\x18\x02 \x01(\x0e\x32\r.etl.v1.OrderR\x05order\x12\x17\n\x07user_id\x18\x03 \x01(\tR\x06userId\x12\x19\n\x08track_id\x18\x04 \x01(\tR\x07trackId\"A\n\x10GetPlaysResponse\x12-\n\x05plays\x18\x01 \x03(\x0b\x32\x17.etl.v1.GetPlayResponseR\x05plays\"\xe5\x01\n\x0fGetPlayResponse\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12\x19\n\x08track_id\x18\x02 \x01(\tR\x07trackId\x12\x1c\n\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n\x04\x63ity\x18\x04 \x01(\tR\x04\x63ity\x12\x18\n\x07\x63ountry\x18\x05 \x01(\tR\x07\x63ountry\x12\x16\n\x06region\x18\x06 \x01(\tR\x06region\x12!\n\x0c\x62lock_height\x18\x07 \x01(\x03R\x0b\x62lockHeight\x12\x17\n\x07tx_hash\x18\x08 \x01(\tR\x06txHash\":\n\nPagination\x12\x14\n\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n\x06offset\x18\x02 \x01(\x03R\x06offset*=\n\x05Order\x12\x15\n\x11ORDER_UNSPECIFIED\x10\x00\x12\r\n\tORDER_ASC\x10\x01\x12\x0e\n\nORDER_DESC\x10\x02\x42\x31Z/github.com/AudiusProject/audiusd/pkg/api/etl/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'etl.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/AudiusProject/audiusd/pkg/api/etl/v1'
  _globals['_ORDER']._serialized_start=648
  _globals['_ORDER']._serialized_end=709
  _globals['_PINGREQUEST']._serialized_start=30
  _globals['_PINGREQUEST']._serialized_end=43
  _globals['_PINGRESPONSE']._serialized_start=45
  _globals['_PINGRESPONSE']._serialized_end=85
  _globals['_GETHEALTHREQUEST']._serialized_start=87
  _globals['_GETHEALTHREQUEST']._serialized_end=105
  _globals['_GETHEALTHRESPONSE']._serialized_start=107
  _globals['_GETHEALTHRESPONSE']._serialized_end=126
  _globals['_GETPLAYSREQUEST']._serialized_start=129
  _globals['_GETPLAYSREQUEST']._serialized_end=287
  _globals['_GETPLAYSRESPONSE']._serialized_start=289
  _globals['_GETPLAYSRESPONSE']._serialized_end=354
  _globals['_GETPLAYRESPONSE']._serialized_start=357
  _globals['_GETPLAYRESPONSE']._serialized_end=586
  _globals['_PAGINATION']._serialized_start=588
  _globals['_PAGINATION']._serialized_end=646
# @@protoc_insertion_point(module_scope)
