import { Nullable } from '~/utils/typeUtils'

export type Environment = 'development' | 'staging' | 'production'

export type Env = {
  AAO_ENDPOINT: string
  AMPLITUDE_API_KEY: Nullable<string>
  AMPLITUDE_PROXY: Nullable<string>
  AMPLITUDE_WRITE_KEY: Nullable<string>
  APP_NAME: string
  API_KEY: string
  AUDIUS_URL: string
  BITSKI_CALLBACK_URL: string
  BITSKI_CLIENT_ID: string
  CACHE_PRUNE_MIN: string
  CLAIM_DISTRIBUTION_CONTRACT_ADDRESS: Nullable<string>
  CLAIMABLE_TOKEN_PDA: string
  CLAIMABLE_TOKEN_PROGRAM_ADDRESS: string
  COINFLOW_APP_ID: string
  COINFLOW_MERCHANT_ID: string
  COINFLOW_PARTNER_ID: string
  COGNITO_KEY: Nullable<string>
  COGNITO_TEMPLATE_ID: Nullable<string>
  EAGER_DISCOVERY_NODES: string
  ENTITY_MANAGER_ADDRESS: string
  ENVIRONMENT: Environment
  ETH_BRIDGE_ADDRESS: Nullable<string>
  ETH_NETWORK_ID: string
  ETH_OWNER_WALLET: Nullable<string>
  ETH_PROVIDER_URL: string
  ETH_REGISTRY_ADDRESS: string
  ETH_TOKEN_ADDRESS: string
  ETH_TOKEN_BRIDGE_ADDRESS: Nullable<string>
  EXPLORE_CONTENT_URL: string
  FCM_PUSH_PUBLIC_KEY: Nullable<string>
  FINGERPRINT_ENDPOINT: Nullable<string>
  FINGERPRINT_PUBLIC_API_KEY: Nullable<string>
  GA_HOSTNAME: string
  GA_MEASUREMENT_ID: string
  GENERAL_ADMISSION: string
  HCAPTCHA_BASE_URL: string
  HCAPTCHA_SITE_KEY: string
  IDENTITY_SERVICE: string
  INSTAGRAM_APP_ID: string
  INSTAGRAM_REDIRECT_URL: string
  LOOKUP_TABLE_ADDRESS: string
  METADATA_PROGRAM_ID: string
  OPENSEA_API_URL: string
  HELIUS_DAS_API_URL: string
  OPTIMIZELY_KEY: string
  ORACLE_ETH_ADDRESSES: string
  PAYMENT_ROUTER_PROGRAM_ID: string
  STAKING_BRIDGE_PROGRAM_ID: string
  PUBLIC_HOSTNAME: string
  PUBLIC_PROTOCOL: string
  BASENAME: string
  REACHABILITY_URL: string
  STRIPE_CLIENT_PUBLISHABLE_KEY: string
  RECAPTCHA_SITE_KEY: string
  REGISTRY_ADDRESS: string
  REWARDS_MANAGER_PROGRAM_ID: string
  REWARDS_MANAGER_PROGRAM_PDA: string
  REWARDS_MANAGER_TOKEN_PDA: string
  SAFARI_WEB_PUSH_ID: string
  SCHEME: string
  SENTRY_DSN: string
  SOL_BRIDGE_ADDRESS: Nullable<string>
  SOL_TOKEN_BRIDGE_ADDRESS: Nullable<string>
  SOLANA_CLUSTER_ENDPOINT: string
  SOLANA_FEE_PAYER_ADDRESS: string
  SOLANA_RELAY_ENDPOINT: string
  SOLANA_TOKEN_PROGRAM_ADDRESS: string
  SOLANA_WEB3_CLUSTER: string
  SUGGESTED_FOLLOW_HANDLES: string
  TIKTOK_APP_ID: string
  USDC_MINT_ADDRESS: string
  USER_NODE: string
  USE_HASH_ROUTING: boolean
  WAUDIO_MINT_ADDRESS: string
  WEB3_NETWORK_ID: string
  WEB3_PROVIDER_URL: string
  WORMHOLE_ADDRESS: Nullable<string>
  WORMHOLE_RPC_HOSTS: Nullable<string>
}
