FROM golang:alpine

RUN apk add build-base make ffmpeg

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod graph | awk '{if ($1 !~ "@") print $2}' | xargs go get

COPY . .
RUN go build
RUN go build -o mediorum-cmd cmd/main.go

VOLUME ["/mediorum_data"]
EXPOSE 1991
ENTRYPOINT ["air"]
