CREATE OR REPLACE FUNCTION country_to_iso_alpha2(country_name TEXT)
RETURNS TEXT AS $$
DECLARE
    iso2_code TEXT;
BEGIN
    SELECT INTO iso2_code
    CASE
        -- standards
        WHEN country_name ILIKE 'Andorra' THEN 'AD'
        WHEN country_name ILIKE 'United Arab Emirates' THEN 'AE'
        WHEN country_name ILIKE 'Afghanistan' THEN 'AF'
        WHEN country_name ILIKE 'Antigua and Barbuda' THEN 'AG'
        WHEN country_name ILIKE 'Anguilla' THEN 'AI'
        WHEN country_name ILIKE 'Albania' THEN 'AL'
        WHEN country_name ILIKE 'Armenia' THEN 'AM'
        WHEN country_name ILIKE 'Netherlands Antilles' THEN 'AN'
        WHEN country_name ILIKE 'Angola' THEN 'AO'
        WHEN country_name ILIKE 'Antarctica' THEN 'AQ'
        WHEN country_name ILIKE 'Argentina' THEN 'AR'
        WHEN country_name ILIKE 'American Samoa' THEN 'AS'
        WHEN country_name ILIKE 'Austria' THEN 'AT'
        WHEN country_name ILIKE 'Australia' THEN 'AU'
        WHEN country_name ILIKE 'Aruba' THEN 'AW'
        WHEN country_name ILIKE 'Åland' THEN 'AX'
        WHEN country_name ILIKE 'Azerbaijan' THEN 'AZ'
        WHEN country_name ILIKE 'Bosnia and Herzegovina' THEN 'BA'
        WHEN country_name ILIKE 'Barbados' THEN 'BB'
        WHEN country_name ILIKE 'Bangladesh' THEN 'BD'
        WHEN country_name ILIKE 'Belgium' THEN 'BE'
        WHEN country_name ILIKE 'Burkina Faso' THEN 'BF'
        WHEN country_name ILIKE 'Bulgaria' THEN 'BG'
        WHEN country_name ILIKE 'Bahrain' THEN 'BH'
        WHEN country_name ILIKE 'Burundi' THEN 'BI'
        WHEN country_name ILIKE 'Benin' THEN 'BJ'
        WHEN country_name ILIKE 'Saint Barthélemy' THEN 'BL'
        WHEN country_name ILIKE 'Bermuda' THEN 'BM'
        WHEN country_name ILIKE 'Brunei Darussalam' THEN 'BN'
        WHEN country_name ILIKE 'Bolivia' THEN 'BO'
        WHEN country_name ILIKE 'Brazil' THEN 'BR'
        WHEN country_name ILIKE 'Bahamas' THEN 'BS'
        WHEN country_name ILIKE 'Bhutan' THEN 'BT'
        WHEN country_name ILIKE 'Bouvet Island' THEN 'BV'
        WHEN country_name ILIKE 'Botswana' THEN 'BW'
        WHEN country_name ILIKE 'Belarus' THEN 'BY'
        WHEN country_name ILIKE 'Belize' THEN 'BZ'
        WHEN country_name ILIKE 'Canada' THEN 'CA'
        WHEN country_name ILIKE 'Cocos (Keeling) Islands' THEN 'CC'
        WHEN country_name ILIKE 'Congo (Kinshasa)' THEN 'CD'
        WHEN country_name ILIKE 'Central African Republic' THEN 'CF'
        WHEN country_name ILIKE 'Congo (Brazzaville)' THEN 'CG'
        WHEN country_name ILIKE 'Switzerland' THEN 'CH'
        WHEN country_name ILIKE 'Côte d''Ivoire' THEN 'CI'
        WHEN country_name ILIKE 'Cook Islands' THEN 'CK'
        WHEN country_name ILIKE 'Chile' THEN 'CL'
        WHEN country_name ILIKE 'Cameroon' THEN 'CM'
        WHEN country_name ILIKE 'China' THEN 'CN'
        WHEN country_name ILIKE 'Colombia' THEN 'CO'
        WHEN country_name ILIKE 'Costa Rica' THEN 'CR'
        WHEN country_name ILIKE 'Cuba' THEN 'CU'
        WHEN country_name ILIKE 'Cape Verde' THEN 'CV'
        WHEN country_name ILIKE 'Christmas Island' THEN 'CX'
        WHEN country_name ILIKE 'Cyprus' THEN 'CY'
        WHEN country_name ILIKE 'Czech Republic' THEN 'CZ'
        WHEN country_name ILIKE 'Germany' THEN 'DE'
        WHEN country_name ILIKE 'Djibouti' THEN 'DJ'
        WHEN country_name ILIKE 'Denmark' THEN 'DK'
        WHEN country_name ILIKE 'Dominica' THEN 'DM'
        WHEN country_name ILIKE 'Dominican Republic' THEN 'DO'
        WHEN country_name ILIKE 'Algeria' THEN 'DZ'
        WHEN country_name ILIKE 'Ecuador' THEN 'EC'
        WHEN country_name ILIKE 'Estonia' THEN 'EE'
        WHEN country_name ILIKE 'Egypt' THEN 'EG'
        WHEN country_name ILIKE 'Western Sahara' THEN 'EH'
        WHEN country_name ILIKE 'Eritrea' THEN 'ER'
        WHEN country_name ILIKE 'Spain' THEN 'ES'
        WHEN country_name ILIKE 'Ethiopia' THEN 'ET'
        WHEN country_name ILIKE 'Finland' THEN 'FI'
        WHEN country_name ILIKE 'Fiji' THEN 'FJ'
        WHEN country_name ILIKE 'Falkland Islands' THEN 'FK'
        WHEN country_name ILIKE 'Micronesia' THEN 'FM'
        WHEN country_name ILIKE 'Faroe Islands' THEN 'FO'
        WHEN country_name ILIKE 'France' THEN 'FR'
        WHEN country_name ILIKE 'Gabon' THEN 'GA'
        WHEN country_name ILIKE 'United Kingdom' THEN 'GB'
        WHEN country_name ILIKE 'Grenada' THEN 'GD'
        WHEN country_name ILIKE 'Georgia' THEN 'GE'
        WHEN country_name ILIKE 'French Guiana' THEN 'GF'
        WHEN country_name ILIKE 'Guernsey' THEN 'GG'
        WHEN country_name ILIKE 'Ghana' THEN 'GH'
        WHEN country_name ILIKE 'Gibraltar' THEN 'GI'
        WHEN country_name ILIKE 'Greenland' THEN 'GL'
        WHEN country_name ILIKE 'Gambia' THEN 'GM'
        WHEN country_name ILIKE 'Guinea' THEN 'GN'
        WHEN country_name ILIKE 'Guadeloupe' THEN 'GP'
        WHEN country_name ILIKE 'Equatorial Guinea' THEN 'GQ'
        WHEN country_name ILIKE 'Greece' THEN 'GR'
        WHEN country_name ILIKE 'South Georgia and South Sandwich Islands' THEN 'GS'
        WHEN country_name ILIKE 'Guatemala' THEN 'GT'
        WHEN country_name ILIKE 'Guam' THEN 'GU'
        WHEN country_name ILIKE 'Guinea-Bissau' THEN 'GW'
        WHEN country_name ILIKE 'Guyana' THEN 'GY'
        WHEN country_name ILIKE 'Hong Kong' THEN 'HK'
        WHEN country_name ILIKE 'Heard and McDonald Islands' THEN 'HM'
        WHEN country_name ILIKE 'Honduras' THEN 'HN'
        WHEN country_name ILIKE 'Croatia' THEN 'HR'
        WHEN country_name ILIKE 'Haiti' THEN 'HT'
        WHEN country_name ILIKE 'Hungary' THEN 'HU'
        WHEN country_name ILIKE 'Indonesia' THEN 'ID'
        WHEN country_name ILIKE 'Ireland' THEN 'IE'
        WHEN country_name ILIKE 'Israel' THEN 'IL'
        WHEN country_name ILIKE 'Isle of Man' THEN 'IM'
        WHEN country_name ILIKE 'India' THEN 'IN'
        WHEN country_name ILIKE 'British Indian Ocean Territory' THEN 'IO'
        WHEN country_name ILIKE 'Iraq' THEN 'IQ'
        WHEN country_name ILIKE 'Iran' THEN 'IR'
        WHEN country_name ILIKE 'Iceland' THEN 'IS'
        WHEN country_name ILIKE 'Italy' THEN 'IT'
        WHEN country_name ILIKE 'Jersey' THEN 'JE'
        WHEN country_name ILIKE 'Jamaica' THEN 'JM'
        WHEN country_name ILIKE 'Jordan' THEN 'JO'
        WHEN country_name ILIKE 'Japan' THEN 'JP'
        WHEN country_name ILIKE 'Kenya' THEN 'KE'
        WHEN country_name ILIKE 'Kyrgyzstan' THEN 'KG'
        WHEN country_name ILIKE 'Cambodia' THEN 'KH'
        WHEN country_name ILIKE 'Kiribati' THEN 'KI'
        WHEN country_name ILIKE 'Comoros' THEN 'KM'
        WHEN country_name ILIKE 'Saint Kitts and Nevis' THEN 'KN'
        WHEN country_name ILIKE 'Korea, North' THEN 'KP'
        WHEN country_name ILIKE 'Korea, South' THEN 'KR'
        WHEN country_name ILIKE 'Kuwait' THEN 'KW'
        WHEN country_name ILIKE 'Cayman Islands' THEN 'KY'
        WHEN country_name ILIKE 'Kazakhstan' THEN 'KZ'
        WHEN country_name ILIKE 'Laos' THEN 'LA'
        WHEN country_name ILIKE 'Lebanon' THEN 'LB'
        WHEN country_name ILIKE 'Saint Lucia' THEN 'LC'
        WHEN country_name ILIKE 'Liechtenstein' THEN 'LI'
        WHEN country_name ILIKE 'Sri Lanka' THEN 'LK'
        WHEN country_name ILIKE 'Liberia' THEN 'LR'
        WHEN country_name ILIKE 'Lesotho' THEN 'LS'
        WHEN country_name ILIKE 'Lithuania' THEN 'LT'
        WHEN country_name ILIKE 'Luxembourg' THEN 'LU'
        WHEN country_name ILIKE 'Latvia' THEN 'LV'
        WHEN country_name ILIKE 'Libya' THEN 'LY'
        WHEN country_name ILIKE 'Morocco' THEN 'MA'
        WHEN country_name ILIKE 'Monaco' THEN 'MC'
        WHEN country_name ILIKE 'Moldova' THEN 'MD'
        WHEN country_name ILIKE 'Montenegro' THEN 'ME'
        WHEN country_name ILIKE 'Saint Martin (French part)' THEN 'MF'
        WHEN country_name ILIKE 'Madagascar' THEN 'MG'
        WHEN country_name ILIKE 'Marshall Islands' THEN 'MH'
        WHEN country_name ILIKE 'Macedonia' THEN 'MK'
        WHEN country_name ILIKE 'Mali' THEN 'ML'
        WHEN country_name ILIKE 'Myanmar' THEN 'MM'
        WHEN country_name ILIKE 'Mongolia' THEN 'MN'
        WHEN country_name ILIKE 'Macau' THEN 'MO'
        WHEN country_name ILIKE 'Northern Mariana Islands' THEN 'MP'
        WHEN country_name ILIKE 'Martinique' THEN 'MQ'
        WHEN country_name ILIKE 'Mauritania' THEN 'MR'
        WHEN country_name ILIKE 'Montserrat' THEN 'MS'
        WHEN country_name ILIKE 'Malta' THEN 'MT'
        WHEN country_name ILIKE 'Mauritius' THEN 'MU'
        WHEN country_name ILIKE 'Maldives' THEN 'MV'
        WHEN country_name ILIKE 'Malawi' THEN 'MW'
        WHEN country_name ILIKE 'Mexico' THEN 'MX'
        WHEN country_name ILIKE 'Malaysia' THEN 'MY'
        WHEN country_name ILIKE 'Mozambique' THEN 'MZ'
        WHEN country_name ILIKE 'Namibia' THEN 'NA'
        WHEN country_name ILIKE 'New Caledonia' THEN 'NC'
        WHEN country_name ILIKE 'Niger' THEN 'NE'
        WHEN country_name ILIKE 'Norfolk Island' THEN 'NF'
        WHEN country_name ILIKE 'Nigeria' THEN 'NG'
        WHEN country_name ILIKE 'Nicaragua' THEN 'NI'
        WHEN country_name ILIKE 'Netherlands' THEN 'NL'
        WHEN country_name ILIKE 'Norway' THEN 'NO'
        WHEN country_name ILIKE 'Nepal' THEN 'NP'
        WHEN country_name ILIKE 'Nauru' THEN 'NR'
        WHEN country_name ILIKE 'Niue' THEN 'NU'
        WHEN country_name ILIKE 'New Zealand' THEN 'NZ'
        WHEN country_name ILIKE 'Oman' THEN 'OM'
        WHEN country_name ILIKE 'Panama' THEN 'PA'
        WHEN country_name ILIKE 'Peru' THEN 'PE'
        WHEN country_name ILIKE 'French Polynesia' THEN 'PF'
        WHEN country_name ILIKE 'Papua New Guinea' THEN 'PG'
        WHEN country_name ILIKE 'Philippines' THEN 'PH'
        WHEN country_name ILIKE 'Pakistan' THEN 'PK'
        WHEN country_name ILIKE 'Poland' THEN 'PL'
        WHEN country_name ILIKE 'Saint Pierre and Miquelon' THEN 'PM'
        WHEN country_name ILIKE 'Pitcairn' THEN 'PN'
        WHEN country_name ILIKE 'Puerto Rico' THEN 'PR'
        WHEN country_name ILIKE 'Palestine' THEN 'PS'
        WHEN country_name ILIKE 'Portugal' THEN 'PT'
        WHEN country_name ILIKE 'Palau' THEN 'PW'
        WHEN country_name ILIKE 'Paraguay' THEN 'PY'
        WHEN country_name ILIKE 'Qatar' THEN 'QA'
        WHEN country_name ILIKE 'Reunion' THEN 'RE'
        WHEN country_name ILIKE 'Romania' THEN 'RO'
        WHEN country_name ILIKE 'Serbia' THEN 'RS'
        WHEN country_name ILIKE 'Russian Federation' THEN 'RU'
        WHEN country_name ILIKE 'Rwanda' THEN 'RW'
        WHEN country_name ILIKE 'Saudi Arabia' THEN 'SA'
        WHEN country_name ILIKE 'Solomon Islands' THEN 'SB'
        WHEN country_name ILIKE 'Seychelles' THEN 'SC'
        WHEN country_name ILIKE 'Sudan' THEN 'SD'
        WHEN country_name ILIKE 'Sweden' THEN 'SE'
        WHEN country_name ILIKE 'Singapore' THEN 'SG'
        WHEN country_name ILIKE 'Saint Helena' THEN 'SH'
        WHEN country_name ILIKE 'Slovenia' THEN 'SI'
        WHEN country_name ILIKE 'Svalbard and Jan Mayen Islands' THEN 'SJ'
        WHEN country_name ILIKE 'Slovakia' THEN 'SK'
        WHEN country_name ILIKE 'Sierra Leone' THEN 'SL'
        WHEN country_name ILIKE 'San Marino' THEN 'SM'
        WHEN country_name ILIKE 'Senegal' THEN 'SN'
        WHEN country_name ILIKE 'Somalia' THEN 'SO'
        WHEN country_name ILIKE 'Suriname' THEN 'SR'
        WHEN country_name ILIKE 'Sao Tome and Principe' THEN 'ST'
        WHEN country_name ILIKE 'El Salvador' THEN 'SV'
        WHEN country_name ILIKE 'Syria' THEN 'SY'
        WHEN country_name ILIKE 'Swaziland' THEN 'SZ'
        WHEN country_name ILIKE 'Turks and Caicos Islands' THEN 'TC'
        WHEN country_name ILIKE 'Chad' THEN 'TD'
        WHEN country_name ILIKE 'French Southern Lands' THEN 'TF'
        WHEN country_name ILIKE 'Togo' THEN 'TG'
        WHEN country_name ILIKE 'Thailand' THEN 'TH'
        WHEN country_name ILIKE 'Tajikistan' THEN 'TJ'
        WHEN country_name ILIKE 'Tokelau' THEN 'TK'
        WHEN country_name ILIKE 'Timor-Leste' THEN 'TL'
        WHEN country_name ILIKE 'Turkmenistan' THEN 'TM'
        WHEN country_name ILIKE 'Tunisia' THEN 'TN'
        WHEN country_name ILIKE 'Tonga' THEN 'TO'
        WHEN country_name ILIKE 'Turkey' THEN 'TR'
        WHEN country_name ILIKE 'Trinidad and Tobago' THEN 'TT'
        WHEN country_name ILIKE 'Tuvalu' THEN 'TV'
        WHEN country_name ILIKE 'Taiwan' THEN 'TW'
        WHEN country_name ILIKE 'Tanzania' THEN 'TZ'
        WHEN country_name ILIKE 'Ukraine' THEN 'UA'
        WHEN country_name ILIKE 'Uganda' THEN 'UG'
        WHEN country_name ILIKE 'United States Minor Outlying Islands' THEN 'UM'
        WHEN country_name ILIKE 'United States of America' THEN 'US'
        WHEN country_name ILIKE 'Uruguay' THEN 'UY'
        WHEN country_name ILIKE 'Uzbekistan' THEN 'UZ'
        WHEN country_name ILIKE 'Vatican City' THEN 'VA'
        WHEN country_name ILIKE 'Saint Vincent and the Grenadines' THEN 'VC'
        WHEN country_name ILIKE 'Venezuela' THEN 'VE'
        WHEN country_name ILIKE 'Virgin Islands, British' THEN 'VG'
        WHEN country_name ILIKE 'Virgin Islands, U.S.' THEN 'VI'
        WHEN country_name ILIKE 'Vietnam' THEN 'VN'
        WHEN country_name ILIKE 'Vanuatu' THEN 'VU'
        WHEN country_name ILIKE 'Wallis and Futuna Islands' THEN 'WF'
        WHEN country_name ILIKE 'Samoa' THEN 'WS'
        WHEN country_name ILIKE 'Yemen' THEN 'YE'
        WHEN country_name ILIKE 'Mayotte' THEN 'YT'
        WHEN country_name ILIKE 'South Africa' THEN 'ZA'
        WHEN country_name ILIKE 'Zambia' THEN 'ZM'
        WHEN country_name ILIKE 'Zimbabwe' THEN 'ZW'
        WHEN country_name ILIKE 'Bonaire' THEN 'BQ'
        WHEN country_name ILIKE 'Curaçao' THEN 'CW'
        WHEN country_name ILIKE 'South Sudan' THEN 'SS'
        WHEN country_name ILIKE 'Sint Maarten' THEN 'SX'
        WHEN country_name ILIKE 'Kosovo' THEN 'XK'
        -- audius exceptions
        WHEN country_name ILIKE 'Aland Islands' THEN 'AX'
        WHEN country_name ILIKE 'Bonaire, Saint Eustatius and Saba ' THEN 'BQ'
        WHEN country_name ILIKE 'British Virgin Islands' THEN 'VG'
        WHEN country_name ILIKE 'Brunei' THEN 'BN'
        WHEN country_name ILIKE 'Cabo Verde' THEN 'CV'
        WHEN country_name ILIKE 'Cocos Islands' THEN 'CC'
        WHEN country_name ILIKE 'Curacao' THEN 'CW'
        WHEN country_name ILIKE 'Czechia' THEN 'CZ'
        WHEN country_name ILIKE 'Democratic Republic of the Congo' THEN 'CD'
        WHEN country_name ILIKE 'Eswatini' THEN 'SZ'
        WHEN country_name ILIKE 'Ivory Coast' THEN 'CI'
        WHEN country_name ILIKE 'Macao' THEN 'MO'
        WHEN country_name ILIKE 'North Macedonia' THEN 'MK'
        WHEN country_name ILIKE 'Palestinian Territory' THEN 'PS'
        WHEN country_name ILIKE 'Republic of the Congo' THEN 'CG'
        WHEN country_name ILIKE 'Russia' THEN 'RU'
        WHEN country_name ILIKE 'Saint Barthelemy' THEN 'BL'
        WHEN country_name ILIKE 'Saint Martin' THEN 'MF'
        WHEN country_name ILIKE 'South Korea' THEN 'KR'
        WHEN country_name ILIKE 'The Netherlands' THEN 'NL'
        WHEN country_name ILIKE 'Timor Leste' THEN 'TL'
        WHEN country_name ILIKE 'U.S. Virgin Islands' THEN 'VI'
        WHEN country_name ILIKE 'Wallis and Futuna' THEN 'WF'
        WHEN country_name ILIKE 'United States' THEN 'US'
        ELSE NULL
    END;

    IF iso2_code IS NULL THEN
        RETURN '';
    END IF;

    RETURN iso2_code;
END;
$$ LANGUAGE plpgsql;
