CREATE OR REPLACE FUNCTION is_country_eur(
    country TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    RETURN
        country = 'Afghanistan' OR
        country = 'Albania' OR
        country = 'Algeria' OR
        country = 'American Samoa' OR
        country = 'Andorra' OR
        country = 'Angola' OR
        country = 'Antigua and Barbuda' OR
        country = 'Arab Emirates' OR
        country = 'Armenia' OR
        country = 'Aruba' OR
        country = 'Australia' OR
        country = 'Austria' OR
        country = 'Azerbaijan' OR
        country = 'Bahamas' OR
        country = 'Bahrain' OR
        country = 'Bangladesh' OR
        country = 'Barbados' OR
        country = 'Belarus' OR
        country = 'Belgium' OR
        country = 'Belize' OR
        country = 'Benin' OR
        country = 'Bermuda' OR
        country = 'Bhutan' OR
        country = 'Bolivia' OR
        country = 'Bosnia and Herzegovina' OR
        country = 'Botswana' OR
        country = 'Brunei' OR
        country = 'Bulgaria' OR
        country = 'Burkina Faso' OR
        country = 'Burma' OR
        country = 'Burundi' OR
        country = 'Cambodia' OR
        country = 'Cameroon' OR
        country = 'Cape Verde' OR
        country = 'Cayman Islands' OR
        country = 'Central African Republic' OR
        country = 'Chad' OR
        country = 'Channel Islands' OR
        country = 'Chile' OR
        country = 'China' OR
        country = 'Colombia' OR
        country = 'Comoros' OR
        country = 'Congo' OR
        country = 'Costa Rica' OR
        country = 'Cote d''Ivoire' OR
        country = 'Côte d''Ivoire' OR
        country = 'Croatia' OR
        country = 'Cuba' OR
        country = 'Curacao' OR
        country = 'Cyprus' OR
        country = 'Czech Republic' OR
        country = 'Czechia' OR
        country = 'Democratic People''s Republic of Korea' OR
        country = 'Democratic Republic of the Congo' OR
        country = 'Denmark' OR
        country = 'Djibouti' OR
        country = 'Dominica' OR
        country = 'Dominican Republic' OR
        country = 'East Timor' OR
        country = 'Ecuador' OR
        country = 'Egypt' OR
        country = 'El Salvador' OR
        country = 'Equatorial Guinea' OR
        country = 'Eritrea' OR
        country = 'Estonia' OR
        country = 'Eswatini' OR
        country = 'Ethiopia' OR
        country = 'Faroe Islands' OR
        country = 'Fiji' OR
        country = 'Finland' OR
        country = 'France' OR
        country = 'French Polynesia' OR
        country = 'Gabon' OR
        country = 'Gambia' OR
        country = 'Gambia' OR
        country = 'Georgia' OR
        country = 'Germany' OR
        country = 'Ghana' OR
        country = 'Gibraltar' OR
        country = 'Greece' OR
        country = 'Guernsey' OR
        country = 'Guinea-Bissau' OR
        country = 'Guinea' OR
        country = 'Holy See' OR
        country = 'Hong Kong' OR
        country = 'Hungary' OR
        country = 'Iceland' OR
        country = 'India' OR
        country = 'Indonesia' OR
        country = 'Iran' OR
        country = 'Iraq' OR
        country = 'Ireland' OR
        country = 'Israel' OR
        country = 'Italy' OR
        country = 'Ivory Coast' OR
        country = 'Japan' OR
        country = 'Jersey' OR
        country = 'Jordan' OR
        country = 'Kazakhstan' OR
        country = 'Kenya' OR
        country = 'Kiribati' OR
        country = 'Kosovo' OR
        country = 'Kuwait' OR
        country = 'Kyrgyzstan' OR
        country = 'Laos' OR
        country = 'Latvia' OR
        country = 'Lebanon' OR
        country = 'Lesotho' OR
        country = 'Liberia' OR
        country = 'Libya' OR
        country = 'Liechtenstein' OR
        country = 'Lithuania' OR
        country = 'Lituania' OR
        country = 'Luxembourg' OR
        country = 'Macau' OR
        country = 'Macedonia' OR
        country = 'Madagascar' OR
        country = 'Malawi' OR
        country = 'Malaysia' OR
        country = 'Maldives' OR
        country = 'Mali' OR
        country = 'Malta' OR
        country = 'Marshall Islands' OR
        country = 'Mauritania' OR
        country = 'Mauritius' OR
        country = 'Micronesia' OR
        country = 'Monaco' OR
        country = 'Mongolia' OR
        country = 'Montenegro' OR
        country = 'Morocco' OR
        country = 'Mozambique' OR
        country = 'Myanmar' OR
        country = 'Namibia' OR
        country = 'Nauru' OR
        country = 'Nepal' OR
        country = 'Netherlands' OR
        country = 'New Zealand' OR
        country = 'Niger' OR
        country = 'Nigeria' OR
        country = 'Niue' OR
        country = 'North Korea' OR
        country = 'North Macedonia' OR
        country = 'Norway' OR
        country = 'Oman' OR
        country = 'Pakistan' OR
        country = 'Palau' OR
        country = 'Palestine' OR
        country = 'Palestinian Territory' OR
        country = 'Papua New Guinea' OR
        country = 'Paraguay' OR
        country = 'Peru' OR
        country = 'Philippines' OR
        country = 'Poland' OR
        country = 'Portugal' OR
        country = 'Qatar' OR
        country = 'Reunion' OR
        country = 'Romania' OR
        country = 'Rwanda' OR
        country = 'Samoa' OR
        country = 'San Marino' OR
        country = 'Sao Tome and Principe' OR
        country = 'Saudi Arabia' OR
        country = 'Senegal' OR
        country = 'Serbia' OR
        country = 'Seychelles' OR
        country = 'Sierra Leone' OR
        country = 'Singapore' OR
        country = 'Slovakia' OR
        country = 'Slovenia' OR
        country = 'Solomon Islands' OR
        country = 'Somalia' OR
        country = 'South Africa' OR
        country = 'South Korea' OR
        country = 'South Sudan' OR
        country = 'Spain' OR
        country = 'Sri Lanka' OR
        country = 'Sudan' OR
        country = 'Suriname' OR
        country = 'Swaziland' OR
        country = 'Sweden' OR
        country = 'Switzerland' OR
        country = 'Syria' OR
        country = 'Taiwan' OR
        country = 'Tajikistan' OR
        country = 'Tanzania' OR
        country = 'Thailand' OR
        country = 'Timor Leste' OR
        country = 'Togo' OR
        country = 'Tonga' OR
        country = 'Trinidad and Tobago' OR
        country = 'Tunisia' OR
        country = 'Turkey' OR
        country = 'Turkmenistan' OR
        country = 'Turks and Caicos Islands' OR
        country = 'Tuvalu' OR
        country = 'Uganda' OR
        country = 'Ukraine' OR
        country = 'United Arab Emirates' OR
        country = 'United Kingdom' OR
        country = 'United States' OR
        country = 'Uruguay' OR
        country = 'Uzbekistan' OR
        country = 'Vanuatu' OR
        country = 'Vatican City' OR
        country = 'Venezuela' OR
        country = 'Vietnam' OR
        country = 'Virgin Islands' OR
        country = 'Western Sahara' OR
        country = 'Yemen' OR
        country = 'Zambia' OR
        country = 'Zimbabwe' OR

        -- country codes
        country = 'AD' OR
        country = 'AE' OR
        country = 'AF' OR
        country = 'AG' OR
        country = 'AL' OR
        country = 'AM' OR
        country = 'AO' OR
        country = 'AS' OR
        country = 'AT' OR
        country = 'AU' OR
        country = 'AW' OR
        country = 'AZ' OR
        country = 'BA' OR
        country = 'BB' OR
        country = 'BD' OR
        country = 'BE' OR
        country = 'BF' OR
        country = 'BG' OR
        country = 'BH' OR
        country = 'BI' OR
        country = 'BJ' OR
        country = 'BM' OR
        country = 'BN' OR
        country = 'BO' OR
        country = 'BS' OR
        country = 'BT' OR
        country = 'BW' OR
        country = 'BY' OR
        country = 'BZ' OR
        country = 'CF' OR
        country = 'CG' OR
        country = 'CH' OR
        country = 'CI' OR
        country = 'CL' OR
        country = 'CM' OR
        country = 'CN' OR
        country = 'CO' OR
        country = 'CR' OR
        country = 'CU' OR
        country = 'CV' OR
        country = 'CW' OR
        country = 'CY' OR
        country = 'CZ' OR
        country = 'DE' OR
        country = 'DJ' OR
        country = 'DK' OR
        country = 'DM' OR
        country = 'DO' OR
        country = 'DZ' OR
        country = 'EC' OR
        country = 'EE' OR
        country = 'EG' OR
        country = 'EH' OR
        country = 'ER' OR
        country = 'ES' OR
        country = 'ET' OR
        country = 'FI' OR
        country = 'FJ' OR
        country = 'FO' OR
        country = 'FR' OR
        country = 'GA' OR
        country = 'GB' OR
        country = 'GD' OR
        country = 'GE' OR
        country = 'GG' OR
        country = 'GH' OR
        country = 'GI' OR
        country = 'GM' OR
        country = 'GN' OR
        country = 'GQ' OR
        country = 'GR' OR
        country = 'GT' OR
        country = 'GU' OR
        country = 'GW' OR
        country = 'GY' OR
        country = 'HK' OR
        country = 'HN' OR
        country = 'HR' OR
        country = 'HT' OR
        country = 'HU' OR
        country = 'ID' OR
        country = 'IE' OR
        country = 'IL' OR
        country = 'IM' OR
        country = 'IN' OR
        country = 'IQ' OR
        country = 'IS' OR
        country = 'IT' OR
        country = 'JE' OR
        country = 'JM' OR
        country = 'JO' OR
        country = 'JP' OR
        country = 'KE' OR
        country = 'KG' OR
        country = 'KH' OR
        country = 'KI' OR
        country = 'KM' OR
        country = 'KN' OR
        country = 'KP' OR
        country = 'KR' OR
        country = 'KW' OR
        country = 'KY' OR
        country = 'KZ' OR
        country = 'LA' OR
        country = 'LB' OR
        country = 'LC' OR
        country = 'LI' OR
        country = 'LK' OR
        country = 'LR' OR
        country = 'LS' OR
        country = 'LT' OR
        country = 'LU' OR
        country = 'LV' OR
        country = 'LY' OR
        country = 'MA' OR
        country = 'MC' OR
        country = 'MD' OR
        country = 'ME' OR
        country = 'MG' OR
        country = 'MH' OR
        country = 'MK' OR
        country = 'ML' OR
        country = 'MM' OR
        country = 'MN' OR
        country = 'MO' OR
        country = 'MR' OR
        country = 'MS' OR
        country = 'MT' OR
        country = 'MU' OR
        country = 'MV' OR
        country = 'MW' OR
        country = 'MX' OR
        country = 'MY' OR
        country = 'MZ' OR
        country = 'NA' OR
        country = 'NE' OR
        country = 'NG' OR
        country = 'NI' OR
        country = 'NL' OR
        country = 'NO' OR
        country = 'NP' OR
        country = 'NR' OR
        country = 'NU' OR
        country = 'NZ' OR
        country = 'OM' OR
        country = 'PA' OR
        country = 'PE' OR
        country = 'PF' OR
        country = 'PG' OR
        country = 'PH' OR
        country = 'PK' OR
        country = 'PL' OR
        country = 'PM' OR
        country = 'PN' OR
        country = 'PR' OR
        country = 'PS' OR
        country = 'PT' OR
        country = 'PW' OR
        country = 'PY' OR
        country = 'QA' OR
        country = 'RE' OR
        country = 'RO' OR
        country = 'RS' OR
        country = 'RW' OR
        country = 'SA' OR
        country = 'SB' OR
        country = 'SC' OR
        country = 'SD' OR
        country = 'SE' OR
        country = 'SG' OR
        country = 'SI' OR
        country = 'SK' OR
        country = 'SL' OR
        country = 'SM' OR
        country = 'SN' OR
        country = 'SO' OR
        country = 'SR' OR
        country = 'SS' OR
        country = 'ST' OR
        country = 'SV' OR
        country = 'SX' OR
        country = 'SY' OR
        country = 'SZ' OR
        country = 'TC' OR
        country = 'TD' OR
        country = 'TG' OR
        country = 'TH' OR
        country = 'TJ' OR
        country = 'TK' OR
        country = 'TL' OR
        country = 'TM' OR
        country = 'TN' OR
        country = 'TO' OR
        country = 'TR' OR
        country = 'TT' OR
        country = 'TV' OR
        country = 'TW' OR
        country = 'TZ' OR
        country = 'UA' OR
        country = 'UG' OR
        country = 'US' OR
        country = 'UY' OR
        country = 'UZ' OR
        country = 'VA' OR
        country = 'VC' OR
        country = 'VE' OR
        country = 'VG' OR
        country = 'VI' OR
        country = 'VN' OR
        country = 'VU' OR
        country = 'WS' OR
        country = 'XK' OR
        country = 'YE' OR
        country = 'ZA' OR
        country = 'ZM' OR
        country = 'ZW'
        ;
END;
$$ LANGUAGE plpgsql;
