CREATE OR REPLACE FUNCTION is_country_eur(
    country TEXT
) RETURNS BOOLEAN AS $$
BEGIN
    RETURN
        country = 'Afghanistan' OR
        country = 'Albania' OR
        country = 'Algeria' OR
        country = 'Andorra' OR
        country = 'Angola' OR
        country = 'Arab Emirates' OR
        country = 'Armenia' OR
        country = 'Australia' OR
        country = 'Austria' OR
        country = 'Azerbaijan' OR
        country = 'Bahrain' OR
        country = 'Bangladesh' OR
        country = 'Belarus' OR
        country = 'Belgium' OR
        country = 'Benin' OR
        country = 'Bhutan' OR
        country = 'Bosnia and Herzegovina' OR
        country = 'Botswana' OR
        country = 'Brunei' OR
        country = 'Bulgaria' OR
        country = 'Burkina Faso' OR
        country = 'Burma' OR
        country = 'Burundi' OR
        country = 'Cambodia' OR
        country = 'Cameroon' OR
        country = 'Cape Verde' OR
        country = 'Central African Republic' OR
        country = 'Chad' OR
        country = 'Channel Islands' OR
        country = 'China' OR
        country = 'Comoros' OR
        country = 'Congo' OR
        country = 'Democratic Republic of the Congo' OR
        country = 'Côte d''Ivoire' OR
        country = 'Croatia' OR
        country = 'Cyprus' OR
        country = 'Czech Republic' OR
        country = 'Czechia' OR
        country = 'Denmark' OR
        country = 'Djibouti' OR
        country = 'East Timor' OR
        country = 'Egypt' OR
        country = 'Equatorial Guinea' OR
        country = 'Eritrea' OR
        country = 'Estonia' OR
        country = 'Eswatini' OR
        country = 'Ethiopia' OR
        country = 'Fiji' OR
        country = 'Finland' OR
        country = 'France' OR
        country = 'Gabon' OR
        country = 'Gambia' OR
        country = 'Georgia' OR
        country = 'Germany' OR
        country = 'Ghana' OR
        country = 'Gibraltar' OR
        country = 'Greece' OR
        country = 'Guinea' OR
        country = 'Guinea-Bissau' OR
        country = 'Hong Kong' OR
        country = 'Hungary' OR
        country = 'Iceland' OR
        country = 'India' OR
        country = 'Indonesia' OR
        country = 'Iran' OR
        country = 'Iraq' OR
        country = 'Ireland' OR
        country = 'Israel' OR
        country = 'Italy' OR
        country = 'Ivory Coast' OR
        country = 'Japan' OR
        country = 'Jordan' OR
        country = 'Kazakhstan' OR
        country = 'Kenya' OR
        country = 'Kiribati' OR
        country = 'Kosovo' OR
        country = 'Kuwait' OR
        country = 'Kyrgyzstan' OR
        country = 'Laos' OR
        country = 'Latvia' OR
        country = 'Lebanon' OR
        country = 'Lesotho' OR
        country = 'Liberia' OR
        country = 'Libya' OR
        country = 'Liechtenstein' OR
        country = 'Lithuania' OR
        country = 'Lituania' OR
        country = 'Luxembourg' OR
        country = 'Macau' OR
        country = 'Macedonia' OR
        country = 'Madagascar' OR
        country = 'Malawi' OR
        country = 'Malaysia' OR
        country = 'Maldives' OR
        country = 'Mali' OR
        country = 'Malta' OR
        country = 'Marshall Islands' OR
        country = 'Mauritania' OR
        country = 'Mauritius' OR
        country = 'Micronesia' OR
        country = 'Monaco' OR
        country = 'Mongolia' OR
        country = 'Montenegro' OR
        country = 'Morocco' OR
        country = 'Mozambique' OR
        country = 'Myanmar' OR
        country = 'Namibia' OR
        country = 'Nauru' OR
        country = 'Nepal' OR
        country = 'Netherlands' OR
        country = 'New Zealand' OR
        country = 'Niger' OR
        country = 'Nigeria' OR
        country = 'Niue' OR
        country = 'North Korea' OR
        country = 'North Macedonia' OR
        country = 'Norway' OR
        country = 'Oman' OR
        country = 'Pakistan' OR
        country = 'Palau' OR
        country = 'Palestine' OR
        country = 'Palestinian Territory' OR
        country = 'Papua New Guinea' OR
        country = 'Philippines' OR
        country = 'Poland' OR
        country = 'Portugal' OR
        country = 'Qatar' OR
        country = 'Reunion' OR
        country = 'Romania' OR
        country = 'Rwanda' OR
        country = 'Samoa' OR
        country = 'San Marino' OR
        country = 'Sao Tome and Principe' OR
        country = 'Saudi Arabia' OR
        country = 'Senegal' OR
        country = 'Serbia' OR
        country = 'Seychelles' OR
        country = 'Sierra Leone' OR
        country = 'Singapore' OR
        country = 'Slovakia' OR
        country = 'Slovenia' OR
        country = 'Solomon Islands' OR
        country = 'Somalia' OR
        country = 'South Africa' OR
        country = 'South Korea' OR
        country = 'South Sudan' OR
        country = 'Spain' OR
        country = 'Sri Lanka' OR
        country = 'Sudan' OR
        country = 'Swaziland' OR
        country = 'Sweden' OR
        country = 'Switzerland' OR
        country = 'Syria' OR
        country = 'Taiwan' OR
        country = 'Tajikistan' OR
        country = 'Tanzania' OR
        country = 'Thailand' OR
        country = 'Timor Leste' OR
        country = 'Gambia' OR
        country = 'Togo' OR
        country = 'Tonga' OR
        country = 'Tunisia' OR
        country = 'Turkey' OR
        country = 'Turkmenistan' OR
        country = 'Tuvalu' OR
        country = 'Uganda' OR
        country = 'Ukraine' OR
        country = 'United Arab Emirates' OR
        country = 'United Kingdom' OR
        country = 'Uzbekistan' OR
        country = 'Vanuatu' OR
        country = 'Vietnam' OR
        country = 'Vatican City' OR
        country = 'Western Sahara' OR
        country = 'Yemen' OR
        country = 'Zambia' OR
        country = 'Zimbabwe';
END;
$$ LANGUAGE plpgsql;