  ##########
  # prod.yml
  ##########

  #############################################
  # monitor custom exporters produced by audius
  #############################################

  # monitor data growth using containers running colocated on prometheus-grafana-metrics

  - job_name: 'census-prod'
    metrics_path: '/metrics'
    scrape_interval: 30m
    static_configs:
      - targets: ['host.docker.internal:8002']
        labels:
          host: 'host.docker.internal'
          environment: 'prod'
          service: 'audius'
          component: 'monitoring'
          job: 'census'

  ##################
  # monitor canaries
  ##################

  # monitor canary nodes, which are not listed as part of getServiceProviderList

  - job_name: 'discoveryprovider4-audius-co'
    scheme: https
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['discoveryprovider4.audius.co']
        labels:
          host: 'discoveryprovider4.audius.co'
          environment: 'prod'
          service: 'audius'
          component: 'discover-provider'
          canary: true
