// Two Tone / Special Styling
export { default as IconArtistBadge } from '../assets/icons/ArtistBadge.svg'
export { default as IconCosign } from '../assets/icons/Cosign.svg'
export { default as IconMultiselectAdd } from '../assets/icons/MultiselectAdd.svg'
export { default as IconMultiselectRemove } from '../assets/icons/MultiselectRemove.svg'

// VIP Tier Badges
export { default as IconVerified } from '../assets/icons/Verified.svg'
export { default as IconTokenBronze } from '../assets/icons/TokenBronze.svg'
export { default as IconTokenGold } from '../assets/icons/TokenGold.svg'
export { default as IconTokenPlatinum } from '../assets/icons/TokenPlatinum.svg'
export { default as IconTokenSilver } from '../assets/icons/TokenSilver.svg'
export { default as IconTokenNoTier } from '../assets/icons/TokenNoTier.svg'

// File Types
export { default as IconFile3GA } from '../assets/icons/file3GA.svg'
export { default as IconFile3GP } from '../assets/icons/file3GP.svg'
export { default as IconFileAAC } from '../assets/icons/fileAAC.svg'
export { default as IconFileAIF } from '../assets/icons/fileAIF.svg'
export { default as IconFileAIFF } from '../assets/icons/fileAIFF.svg'
export { default as IconFileAMR } from '../assets/icons/fileAMR.svg'
export { default as IconFileAWB } from '../assets/icons/fileAWB.svg'
export { default as IconFileFLAC } from '../assets/icons/fileFLAC.svg'
export { default as IconFileM4A } from '../assets/icons/fileM4A.svg'
export { default as IconFileM4B } from '../assets/icons/fileM4B.svg'
export { default as IconFileM4P } from '../assets/icons/fileM4P.svg'
export { default as IconFileM4R } from '../assets/icons/fileM4R.svg'
export { default as IconFileM4V } from '../assets/icons/fileM4V.svg'
export { default as IconFileMP2 } from '../assets/icons/fileMP2.svg'
export { default as IconFileMP3 } from '../assets/icons/fileMP3.svg'
export { default as IconFileMP4 } from '../assets/icons/fileMP4.svg'
export { default as IconFileMPGA } from '../assets/icons/fileMPGA.svg'
export { default as IconFileOGA } from '../assets/icons/fileOGA.svg'
export { default as IconFileOGG } from '../assets/icons/fileOGG.svg'
export { default as IconFileOGM } from '../assets/icons/fileOGM.svg'
export { default as IconFileOGV } from '../assets/icons/fileOGV.svg'
export { default as IconFileOGX } from '../assets/icons/fileOGX.svg'
export { default as IconFileAIFC } from '../assets/icons/fileAIFC.svg'
export { default as IconFileOPUS } from '../assets/icons/fileOPUS.svg'
export { default as IconFileSPX } from '../assets/icons/fileSPX.svg'
export { default as IconFileTS } from '../assets/icons/fileTS.svg'
export { default as IconFileTSA } from '../assets/icons/fileTSA.svg'
export { default as IconFileTSV } from '../assets/icons/fileTSV.svg'
export { default as IconFileUnknown } from '../assets/icons/fileUnknown.svg'
export { default as IconFileWAV } from '../assets/icons/fileWAV.svg'
export { default as IconFileWAVE } from '../assets/icons/fileWAVE.svg'
export { default as IconFileWEBM } from '../assets/icons/fileWEBM.svg'
export { default as IconFileXWMA } from '../assets/icons/fileXWMA.svg'

// Creative Commons
export { default as IconCcBy } from '../assets/icons/ccBy.svg'
export { default as IconCcCC } from '../assets/icons/ccCC.svg'
export { default as IconCcNC_EU } from '../assets/icons/ccNC-EU.svg'
export { default as IconCcNC_JP } from '../assets/icons/ccNC-JP.svg'
export { default as IconCcNC } from '../assets/icons/ccNC.svg'
export { default as IconCcND } from '../assets/icons/ccND.svg'
export { default as IconCcPD } from '../assets/icons/ccPD.svg'
export { default as IconCcRemix } from '../assets/icons/ccRemix.svg'
export { default as IconCcSA } from '../assets/icons/ccSA.svg'
export { default as IconCcSampling } from '../assets/icons/ccSampling.svg'
export { default as IconCcSamplingPlus } from '../assets/icons/ccSamplingPlus.svg'
export { default as IconCcShare } from '../assets/icons/ccShare.svg'
export { default as IconCcZero } from '../assets/icons/ccZero.svg'

// Playback Rate Icons
export { default as IconPlaybackRate0_5x } from '../assets/icons/iconPlaybackRate0_5x.svg'
export { default as IconPlaybackRate0_8x } from '../assets/icons/iconPlaybackRate0_8x.svg'
export { default as IconPlaybackRate0_9x } from '../assets/icons/iconPlaybackRate0_9x.svg'
export { default as IconPlaybackRate1x } from '../assets/icons/iconPlaybackRate1x.svg'
export { default as IconPlaybackRate1_1x } from '../assets/icons/iconPlaybackRate1_1x.svg'
export { default as IconPlaybackRate1_2x } from '../assets/icons/iconPlaybackRate1_2x.svg'
export { default as IconPlaybackRate1_5x } from '../assets/icons/iconPlaybackRate1_5x.svg'
export { default as IconPlaybackRate2x } from '../assets/icons/iconPlaybackRate2x.svg'
export { default as IconPlaybackRate2_5x } from '../assets/icons/iconPlaybackRate2_5x.svg'
export { default as IconPlaybackRate3x } from '../assets/icons/iconPlaybackRate3x.svg'
