FROM golang:alpine AS builder

ENV GO111MODULE=on
ENV CGO_ENABLED=0

RUN go install github.com/cosmtrek/air@v1.52.1

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod graph | awk '{if ($1 !~ "@") print $2}' | xargs go get

COPY . .

