ALTER TYPE delist_track_reason ADD VALUE IF NOT EXISTS 'ACR_COUNTER_NOTICE';
ALTER TYPE delist_track_reason ADD VALUE IF NOT EXISTS 'DMCA_RETRACTION';
ALTER TYPE delist_track_reason ADD VALUE IF NOT EXISTS 'DMCA_COUNTER_NOTICE';
ALTER TYPE delist_track_reason ADD VALUE IF NOT EXISTS 'DMCA_AND_ACR_COUNTER_NOTICE';
