begin;
do $$ begin
-- stage gate
if exists (select * from "blocks" where "blockhash" = '0x65a3243860511ed28a933c3a113dea7df368ad53f721cc9d0034c0c75f996afb') then

  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JBMKGTTKFC3QBJCF7A94HC5A' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JBMK5YVKC75HZSVXNBTRCWEH' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01J9VGBCHF3S4AHHND2DWF3YQN' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01J9VK53SM6970N33S1GARQRG7' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01J9VE6ZYJV39F964SBXAXPKES' and (bpm is null or musical_key is null);
  update tracks set bpm = 164, musical_key = 'A minor' where audio_upload_id = '01J9SBQ6P9ZBDR4ZTK1EE2BV22' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.8, musical_key = 'A flat minor' where audio_upload_id = '01J9PBG46NEAH5RDWJJYWV1NP0' and (bpm is null or musical_key is null);
  update tracks set bpm = 117.1, musical_key = 'C major' where audio_upload_id = '01J9MC3XRPHZK6QGHHRDJ8BVHQ' and (bpm is null or musical_key is null);
  update tracks set bpm = 95.8, musical_key = 'A major' where audio_upload_id = '01J9M146YQA0NBX8Y9EDR070C7' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.8, musical_key = 'A flat minor' where audio_upload_id = '01J9PC04NZCBY5Z8JRAMNTJE6V' and (bpm is null or musical_key is null);
  update tracks set bpm = 90, musical_key = 'D flat major' where audio_upload_id = '01J9M3AVGGJPF9KNKT1FVRK9B5' and (bpm is null or musical_key is null);
  update tracks set bpm = 90, musical_key = 'D flat major' where audio_upload_id = '01J7XMTDX1CEWJKHTVDHATA9CY' and (bpm is null or musical_key is null);
  update tracks set bpm = 117.1, musical_key = 'C major' where audio_upload_id = '01J9M7R4AYHZY8XRJZEMZWWN91' and (bpm is null or musical_key is null);
  update tracks set bpm = 92.9, musical_key = 'D flat minor' where audio_upload_id = '01J9VZ3BFEYRDDB44C5KCSVRJQ' and (bpm is null or musical_key is null);
  update tracks set bpm = 96.9, musical_key = 'C minor' where audio_upload_id = '01J9SDPMW1NR4PEFCVXA10KEPD' and (bpm is null or musical_key is null);
  update tracks set bpm = 134, musical_key = 'B minor' where audio_upload_id = '01JBYZM7YBEQ99M738A9C9JT1W' and (bpm is null or musical_key is null);
  update tracks set bpm = 95.8, musical_key = 'A major' where audio_upload_id = '01J9M32FRRQVPMZSBV2F6ER1X8' and (bpm is null or musical_key is null);
  update tracks set bpm = 95, musical_key = 'C minor' where audio_upload_id = '01J9Q0HN7D9NTD4QS18F7B6THX' and (bpm is null or musical_key is null);
  update tracks set bpm = 164, musical_key = 'G major' where audio_upload_id = '01J9MC3YYCP2SXV0HS380TTQMB' and (bpm is null or musical_key is null);
  update tracks set bpm = 96.9, musical_key = 'C minor' where audio_upload_id = '01J9MC3YAFXSPV5MXPZRC34AQ7' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JAWVAE7SZ1NEX81KPZTR9RQK' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JARG2WS5K9KD1G0PJHK7VS63' and (bpm is null or musical_key is null);
  update tracks set bpm = 85, musical_key = 'A flat major' where audio_upload_id = '01JA8P1WFAG0Z09HS1DV8BYTVK' and (bpm is null or musical_key is null);
  update tracks set bpm = 84, musical_key = 'G flat minor' where audio_upload_id = '01JARFYDAR7253JE28PNJX9Z83' and (bpm is null or musical_key is null);
  update tracks set bpm = 129.9, musical_key = 'G minor' where audio_upload_id = '01JB02588WD83VZK1M4PN301J8' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.8, musical_key = 'A flat minor' where audio_upload_id = '01JA8NCNC8VH1AV90MBHCJZYMV' and (bpm is null or musical_key is null);
  update tracks set bpm = 154.9, musical_key = 'B flat minor' where audio_upload_id = '01JB029RXJ7JEJB9ZFR6ZABAPD' and (bpm is null or musical_key is null);
  update tracks set bpm = 106.7, musical_key = 'E flat minor' where audio_upload_id = '01JADWEYV502WDA71V5G3PRG69' and (bpm is null or musical_key is null);
  update tracks set bpm = 84, musical_key = 'G flat minor' where audio_upload_id = '01JARBPH92B9JABKC34NGSR7R8' and (bpm is null or musical_key is null);
  update tracks set bpm = 111.6, musical_key = 'E major' where audio_upload_id = '01JB0269FHQN9TRN7WSKF37Q6W' and (bpm is null or musical_key is null);
  update tracks set bpm = 162.8, musical_key = 'G minor' where audio_upload_id = '01JB2A7Q0WQ1K03G9PDJTEASBM' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JB12HV6383A59PACKPCW8WW9' and (bpm is null or musical_key is null);
  update tracks set bpm = 164, musical_key = 'A minor' where audio_upload_id = '01JB251C09PWC64N2ZFHX4MR64' and (bpm is null or musical_key is null);
  update tracks set bpm = 91.9, musical_key = 'B minor' where audio_upload_id = '01JA8PMS72RB482F1MCYYCD4QZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 91.9, musical_key = 'B minor' where audio_upload_id = '01JA8Q8SBTJRPMZZN1KVVXWTX4' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JAZJEJ7APRJWBGTRWE6J978H' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.9, musical_key = 'B major' where audio_upload_id = '01JA8PTEKXX7EX58NZY26S3ZQR' and (bpm is null or musical_key is null);
  update tracks set bpm = 95, musical_key = 'B flat minor' where audio_upload_id = '01JA8PBGR1MSTPF46FVTMP0HVX' and (bpm is null or musical_key is null);
  update tracks set bpm = 134.6, musical_key = 'F minor' where audio_upload_id = '01JB2BBVS4G5M7F2W5X5S03XHD' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JB2A41Y2RNHYW4G1QRF0WC0M' and (bpm is null or musical_key is null);
  update tracks set bpm = 191.4, musical_key = 'A minor' where audio_upload_id = '01JBD0F51NSQ294S37FSJ6HWCB' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JB6YVDV5R90ZW2TF2TXTA8VT' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JB6ZCTWRD17AD4CE66YFBN94' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JB2YRD83KPGZ2WVXTRW0FD1X' and (bpm is null or musical_key is null);
  update tracks set bpm = 139.9, musical_key = 'E minor' where audio_upload_id = '01JBFAWDCPR8K19JY6XZHJTBHJ' and (bpm is null or musical_key is null);
  update tracks set bpm = 103.3, musical_key = 'A major' where audio_upload_id = '01JBMBXGCZNY6DR6SARQ77F4VB' and (bpm is null or musical_key is null);
  update tracks set bpm = 152.3, musical_key = 'E minor' where audio_upload_id = '01JBMBXGS8JZEZRAWFG7M9QQ28' and (bpm is null or musical_key is null);
  update tracks set bpm = 95.4, musical_key = 'D flat major' where audio_upload_id = '01JBHSXFN9AH98PR93GBEXGPMW' and (bpm is null or musical_key is null);
  update tracks set bpm = 94.2, musical_key = 'B minor' where audio_upload_id = '01JBMBXJQ71VRC5M679RYP8B2W' and (bpm is null or musical_key is null);
  update tracks set bpm = 135.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMBXG7YFYSC5AST27WS5CH1' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'B minor' where audio_upload_id = '01JBMBXHH7ZJZ88B03ZFKM0135' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'A minor' where audio_upload_id = '01JBMBXF4D4ST1EAYA2G6373ZZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 111, musical_key = 'A minor' where audio_upload_id = '01JBMBXG3RCRFTY9RQ4RKHYRWF' and (bpm is null or musical_key is null);
  update tracks set bpm = 164.9, musical_key = 'D major' where audio_upload_id = '01JBMBXHQWCYCA3XZRG9G1ZKKH' and (bpm is null or musical_key is null);
  update tracks set bpm = 139.9, musical_key = 'E minor' where audio_upload_id = '01JBFGQDWHMM2QVDPBN91E6BB9' and (bpm is null or musical_key is null);
  update tracks set bpm = 97, musical_key = 'G major' where audio_upload_id = '01JBMBXFA6SEN656MNY6GKFRTE' and (bpm is null or musical_key is null);
  update tracks set bpm = 103.1, musical_key = 'B minor' where audio_upload_id = '01JBMBXGF4CTZG0WV8NKXWA8CQ' and (bpm is null or musical_key is null);
  update tracks set bpm = 117.1, musical_key = 'E minor' where audio_upload_id = '01JBMBXHQRATJ7XW9Q1YTQG4BQ' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.3, musical_key = 'A major' where audio_upload_id = '01JBMBXHWPA6GT6FMVR8SNCZ2P' and (bpm is null or musical_key is null);
  update tracks set bpm = 139.9, musical_key = 'E minor' where audio_upload_id = '01JBFNGDX0300C0KPA92JDMYJ5' and (bpm is null or musical_key is null);
  update tracks set bpm = 135.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMBZPPAYB1TJ5V9GX57GATV' and (bpm is null or musical_key is null);
  update tracks set bpm = 117.1, musical_key = 'E minor' where audio_upload_id = '01JBMBZRPDGSEB0M8XY09AF5FX' and (bpm is null or musical_key is null);
  update tracks set bpm = 103.3, musical_key = 'A major' where audio_upload_id = '01JBMBZQEFWTFKT1B6K6AYN824' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMG957QTFZNG4RWDE9P3JNV' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMC8SKE6PXNTWPA2BQR5B6W' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'A minor' where audio_upload_id = '01JBMBZPPNPBP6E1AJ6PVWADX9' and (bpm is null or musical_key is null);
  update tracks set bpm = 152.3, musical_key = 'E minor' where audio_upload_id = '01JBMBZQTEFQT9PXQRDRA7613C' and (bpm is null or musical_key is null);
  update tracks set bpm = 111, musical_key = 'A minor' where audio_upload_id = '01JBMBZRDKN1D1G7XHD0Y85HBZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.3, musical_key = 'A major' where audio_upload_id = '01JBMBZNC1H26QNTME835C8ETH' and (bpm is null or musical_key is null);
  update tracks set bpm = 103.1, musical_key = 'B minor' where audio_upload_id = '01JBMBZQ1K608YQTEZ9TN9MZC1' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMCWNZJ0ZJ3JE8QYB5A9Z92' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMCDDRWWSY83PS9SMHQEFC3' and (bpm is null or musical_key is null);
  update tracks set bpm = 102, musical_key = 'C major' where audio_upload_id = '01JBMHBSAMDPDJZ7JQ383SNTZZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'B minor' where audio_upload_id = '01JBMBZR5MYMB74G9T9Q1AKBYT' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMG339YZB02G6QRQCERV94A' and (bpm is null or musical_key is null);
  update tracks set bpm = 97, musical_key = 'G major' where audio_upload_id = '01JBMBZNEQA5ZZYYZS2YAXMJTK' and (bpm is null or musical_key is null);
  update tracks set bpm = 94.2, musical_key = 'B minor' where audio_upload_id = '01JBMBZQ85YW4EZYRNG3JF6F0W' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMFYHGH53BHFY2FXHQC1EQV' and (bpm is null or musical_key is null);
  update tracks set bpm = 164.9, musical_key = 'D major' where audio_upload_id = '01JBMBZQYD3YGAX4RZGHPD5BZB' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMGJT5ZM1RG3DCHRHF5AP83' and (bpm is null or musical_key is null);
  update tracks set bpm = 110.1, musical_key = 'D minor' where audio_upload_id = '01JBMRRFRZ08R913S6TN9CM9W1' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMRA8QXWZPMSG27TA4YQ27S' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMHKSYCYNJ6GC0ZWDD9QQ0R' and (bpm is null or musical_key is null);
  update tracks set bpm = 108.2, musical_key = 'A flat major' where audio_upload_id = '01JBMHKTXGTX0MYCG8SQ6MGSX3' and (bpm is null or musical_key is null);
  update tracks set bpm = 129.9, musical_key = 'C minor' where audio_upload_id = '01JBMH1SKY55MH203HHDPRAB8G' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMR0CH7YZBZ651WH7RJXDX0' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.1, musical_key = 'E minor' where audio_upload_id = '01JBMHBRHVMDTPW16JVJ837VDE' and (bpm is null or musical_key is null);
  update tracks set bpm = 93.9, musical_key = 'G flat minor' where audio_upload_id = '01JBMHKVFJ2AWTMEDJEK2QXK42' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'E major' where audio_upload_id = '01JBMHBQ8ANBFNF5TR4RTH276P' and (bpm is null or musical_key is null);
  update tracks set bpm = 108.2, musical_key = 'A flat major' where audio_upload_id = '01JBMP291310H3MBNE7VSGWD0K' and (bpm is null or musical_key is null);
  update tracks set bpm = 93.9, musical_key = 'G flat minor' where audio_upload_id = '01JBMR0D2J9HTEANDVC5SYZSM6' and (bpm is null or musical_key is null);
  update tracks set bpm = 93.9, musical_key = 'G flat minor' where audio_upload_id = '01JBMP29YXM7E100TKSDA5HVBT' and (bpm is null or musical_key is null);
  update tracks set bpm = 93.9, musical_key = 'G flat minor' where audio_upload_id = '01JBMRAB2TVX1PXAW5RZ12GA5S' and (bpm is null or musical_key is null);
  update tracks set bpm = 129.9, musical_key = 'C minor' where audio_upload_id = '01JBMH7V8SV0Q00JNY97AS7Z87' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'B flat minor' where audio_upload_id = '01JBMGQ8QH1H5ZMK1WYVAS2GTP' and (bpm is null or musical_key is null);
  update tracks set bpm = 108.2, musical_key = 'A flat major' where audio_upload_id = '01JBMR08W0DXAJ70XFWD4V52ET' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.6, musical_key = 'A flat minor' where audio_upload_id = '01JBMP2APGKEZ7BMTMRR2VCM6C' and (bpm is null or musical_key is null);
  update tracks set bpm = 137.1, musical_key = 'G flat minor' where audio_upload_id = '01JBMRQHJGNFYJ1YMZ9JZ1A5SP' and (bpm is null or musical_key is null);
  update tracks set bpm = 108.2, musical_key = 'A flat major' where audio_upload_id = '01JBMRA6GGXNFE9X8CF9YQBF46' and (bpm is null or musical_key is null);
  update tracks set bpm = 142.5, musical_key = 'D major' where audio_upload_id = '01JBMHBPFF1R19QGFWD5G2WM2R' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JBSA3DYJD84D91ZPAQP3Z3EY' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'E major' where audio_upload_id = '01JBVX32PQ5Y1MM98CE35X3JFH' and (bpm is null or musical_key is null);
  update tracks set bpm = 99.8, musical_key = 'A flat minor' where audio_upload_id = '01JBVXMK8T0A13NNVA06QZTHXK' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBVWQFJCB3C495VJTMD7NGNY' and (bpm is null or musical_key is null);
  update tracks set bpm = 142.5, musical_key = 'D major' where audio_upload_id = '01JBVX315AXDSVS5R0EXPSA5JT' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBVWQFZA0CGTJAAAAJC8JXE0' and (bpm is null or musical_key is null);
  update tracks set bpm = 130.1, musical_key = 'E flat major' where audio_upload_id = '01JBVXMKQVYQHMVXMZQ749RTK7' and (bpm is null or musical_key is null);
  update tracks set bpm = 90.2, musical_key = 'A minor' where audio_upload_id = '01JBMS1DV69GWN1ZA8YNVD7ZSQ' and (bpm is null or musical_key is null);
  update tracks set bpm = 126.6, musical_key = 'G flat minor' where audio_upload_id = '01JBMS1GT6T95E8D37X5ZY39C8' and (bpm is null or musical_key is null);
  update tracks set bpm = 102, musical_key = 'C major' where audio_upload_id = '01JBVX34X10AEXTVRMQ1TGKS9M' and (bpm is null or musical_key is null);
  update tracks set bpm = 106.4, musical_key = 'D minor' where audio_upload_id = '01JBMS1H98ZZRJE4SR91MQGG5E' and (bpm is null or musical_key is null);
  update tracks set bpm = 100.4, musical_key = 'C minor' where audio_upload_id = '01JBMRRHDCFM054W8ECA7QZW6T' and (bpm is null or musical_key is null);
  update tracks set bpm = 90.8, musical_key = 'B minor' where audio_upload_id = '01JBMRRKGHDR1P4V1CERS7Z0R0' and (bpm is null or musical_key is null);
  update tracks set bpm = 120.1, musical_key = 'E major' where audio_upload_id = '01JBMS1DZ334AFPXHZZKSB0423' and (bpm is null or musical_key is null);
  update tracks set bpm = 124.1, musical_key = 'E minor' where audio_upload_id = '01JBMRRM53NXNAKVVTF6QC024R' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBVWQF9SBVJC8EASTS4120WA' and (bpm is null or musical_key is null);
  update tracks set bpm = 92.7, musical_key = 'A major' where audio_upload_id = '01JBMS1BQ768RMN6BX8VC1XTV5' and (bpm is null or musical_key is null);
  update tracks set bpm = 103.5, musical_key = 'B major' where audio_upload_id = '01JBMS1GXG33AFYVPCC1DK1871' and (bpm is null or musical_key is null);
  update tracks set bpm = 64.9, musical_key = 'B minor' where audio_upload_id = '01JBMS1E9ZPKB2WMSP8CNGHR54' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.1, musical_key = 'E minor' where audio_upload_id = '01JBVX34DQJCYTVE1MV5BSY63P' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBW2D9P51S5ZKDHY57HH1CHK' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBW286Y92GV4XP7CJAVEJJV0' and (bpm is null or musical_key is null);
  update tracks set bpm = 98.6, musical_key = 'F minor' where audio_upload_id = '01JBVY9ZR81TBDWHVWJ9ZNN3E9' and (bpm is null or musical_key is null);
  update tracks set bpm = 146.7, musical_key = 'E minor' where audio_upload_id = '01JBVYA00RTJ3F9CX9AC0DBV4E' and (bpm is null or musical_key is null);
  update tracks set bpm = 130.5, musical_key = 'D major' where audio_upload_id = '01JBVY9ZHKRF4830SBPXV9TPRB' and (bpm is null or musical_key is null);
  update tracks set bpm = 90.1, musical_key = 'E minor' where audio_upload_id = '01JBVZEEAZTPZJ9RZ8R4R2C3SE' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBW2X71YT4P6JY8541JKVVZ3' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBW39T95DZYVZW48MRQ2B9KZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBW2X7A8PPW1WN31Q39DDGXD' and (bpm is null or musical_key is null);
  update tracks set bpm = 91.3, musical_key = 'E major' where audio_upload_id = '01JBVY9ZJZKRVWF24M9PFQECKT' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBW2D9CBG0TXQFZJYECDZKBV' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.9, musical_key = 'C major' where audio_upload_id = '01JBVY9Z39JX0YTE2V39QVGKDA' and (bpm is null or musical_key is null);
  update tracks set bpm = 105.6, musical_key = 'C minor' where audio_upload_id = '01JBVY9ZSG67SZ850F2T86RECT' and (bpm is null or musical_key is null);
  update tracks set bpm = 91, musical_key = 'C minor' where audio_upload_id = '01JBVYA07PZCP6YQ9M498AP9AS' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'D flat minor' where audio_upload_id = '01JBVY3AE17XSQCHS3N2QSMGFR' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBW287SKWVPETXNWPP743WWH' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBW2X823E2DVWQH8QREH35JP' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBW2D9HT9DJT0JEC1X70VPT1' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBW286M2JJCJZ2W8A2RA0RA4' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'B minor' where audio_upload_id = '01JBVY9ZXZ35XDXQAA55MSXXQR' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JBYE68CHQ7ZVEF45Z7BX4G8D' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JBYCW8TY35G00SW3JAZZKVDK' and (bpm is null or musical_key is null);
  update tracks set bpm = 154.5, musical_key = 'G flat major' where audio_upload_id = '01JBWSET08CA4P8AM2H0DENGKW' and (bpm is null or musical_key is null);
  update tracks set bpm = 153.1, musical_key = 'G flat major' where audio_upload_id = '01JBYJHE1KJ02NQ83W5RK9P95A' and (bpm is null or musical_key is null);
  update tracks set bpm = 163.3, musical_key = 'C minor' where audio_upload_id = '01JBYAH8SBGHTE02A0Q5ZTBNTY' and (bpm is null or musical_key is null);
  update tracks set bpm = 102.9, musical_key = 'B flat major' where audio_upload_id = '01JBYAH9QP5GZD8H6JJN4NDKCR' and (bpm is null or musical_key is null);
  update tracks set bpm = 94.9, musical_key = 'G flat major' where audio_upload_id = '01JBYSCDP5J10BTDCKR2JHGN2S' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JBYVJFXH2V75AXE43762HTCG' and (bpm is null or musical_key is null);
  update tracks set bpm = 108.2, musical_key = 'A flat major' where audio_upload_id = '01JBW5EFE8XV520G4XKAZC8B5M' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBW39VGVZFBB5B5534MJ2VTT' and (bpm is null or musical_key is null);
  update tracks set bpm = 81.4, musical_key = 'G flat major' where audio_upload_id = '01JBYAH7S9P0X61SE84F45NF98' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBW4TFNJ11BDPV054AACBQE9' and (bpm is null or musical_key is null);
  update tracks set bpm = 67.4, musical_key = 'E flat major' where audio_upload_id = '01JBW39TPKZ8AZ4JJ2K519F8J5' and (bpm is null or musical_key is null);
  update tracks set bpm = 141.9, musical_key = 'G flat minor' where audio_upload_id = '01JBYEQ0AAZY52YKRET8F9A36W' and (bpm is null or musical_key is null);
  update tracks set bpm = 145, musical_key = 'G minor' where audio_upload_id = '01JBYC7TCXWZT25GZW25YVGN46' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.6, musical_key = 'A flat minor' where audio_upload_id = '01JBW5EFJ7PWAQBM90E9K080Y5' and (bpm is null or musical_key is null);
  update tracks set bpm = 136.1, musical_key = 'D flat minor' where audio_upload_id = '01JBW4TGCR86JP35C6TJTAQJ9K' and (bpm is null or musical_key is null);
  update tracks set bpm = 104.9, musical_key = 'E major' where audio_upload_id = '01JBYCYZY9406FP1D5JZKB4QBM' and (bpm is null or musical_key is null);
  update tracks set bpm = 88.6, musical_key = 'B major' where audio_upload_id = '01JBW4TG7DQ1BR3NJFM3TCZ2H8' and (bpm is null or musical_key is null);
  update tracks set bpm = 93.9, musical_key = 'G flat minor' where audio_upload_id = '01JBW5EH7CRNSTPPD1A3H6M7VV' and (bpm is null or musical_key is null);
  update tracks set bpm = 132.6, musical_key = 'E flat minor' where audio_upload_id = '01JBYWEFM1ZPZJV1J85KNZSJ1R' and (bpm is null or musical_key is null);
  update tracks set bpm = 83, musical_key = 'B major' where audio_upload_id = '01JBYVV0RKVZQ7C3F6978YHVY2' and (bpm is null or musical_key is null);
  update tracks set bpm = 79.9, musical_key = 'G minor' where audio_upload_id = '01JBYWDQD1TBZBDR2404ZQ9B0K' and (bpm is null or musical_key is null);
  update tracks set bpm = 172.3, musical_key = 'A major' where audio_upload_id = '01JBYVV3Q39B5R61YQEBF3X2FD' and (bpm is null or musical_key is null);
  update tracks set bpm = 130, musical_key = 'D flat major' where audio_upload_id = '01JBZ88F68CE2J50Z1W3RQBS3T' and (bpm is null or musical_key is null);
  update tracks set bpm = 94.9, musical_key = 'G flat major' where audio_upload_id = '01JBYY51BMCC08N2DXBNQ3H2BN' and (bpm is null or musical_key is null);
  update tracks set bpm = 124, musical_key = 'B flat minor' where audio_upload_id = '01JBZ8EJR75FAW4NJBRPYPS7SF' and (bpm is null or musical_key is null);
  update tracks set bpm = 126, musical_key = 'F minor' where audio_upload_id = '01JBZ88ESY95TXRYETJ646SZVN' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.9, musical_key = 'D minor' where audio_upload_id = '01JBZ88EVG68QWFWX29JG4HA9C' and (bpm is null or musical_key is null);
  update tracks set bpm = 111.1, musical_key = 'F minor' where audio_upload_id = '01JBZ886XWZ7643GSA9Y29TPRE' and (bpm is null or musical_key is null);
  update tracks set bpm = 143.9, musical_key = 'A flat major' where audio_upload_id = '01JBZ88EYY1D9YNQTZS91ADA0V' and (bpm is null or musical_key is null);
  update tracks set bpm = 92.9, musical_key = 'D flat minor' where audio_upload_id = '01JBYWATHD79SCGPHMPJ6GH801' and (bpm is null or musical_key is null);
  update tracks set bpm = 122, musical_key = 'F major' where audio_upload_id = '01JBZ88GBTGG0WEBQP0ACB4SZR' and (bpm is null or musical_key is null);
  update tracks set bpm = 79.5, musical_key = 'E flat minor' where audio_upload_id = '01JBZ885ZBHZPFSV0DS6E4GPHG' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'D minor' where audio_upload_id = '01JBZ88F0WFCC49GFCGS78FS5Y' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'F minor' where audio_upload_id = '01JBZ88CY19K4V6J7WWWR5M2JZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'B flat minor' where audio_upload_id = '01JBZ88FMSYWP1R305Q9HAV7A8' and (bpm is null or musical_key is null);
  update tracks set bpm = 124, musical_key = 'B flat minor' where audio_upload_id = '01JBZ88FP601GVMZXWC53KVGS9' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.2, musical_key = 'G minor' where audio_upload_id = '01JBZ88FXRTCJ7FFSFQWQZPAJP' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'A minor' where audio_upload_id = '01JBZ88DFK57PTA06M4FM02598' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.2, musical_key = 'G minor' where audio_upload_id = '01JBZ8EKW3SH2H06CHDPX5JR8M' and (bpm is null or musical_key is null);
  update tracks set bpm = 79.5, musical_key = 'E flat minor' where audio_upload_id = '01JBZKE73R8XBANAH8F0SMD9ZM' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'A minor' where audio_upload_id = '01JBZ8EKM7JWZ5B2FQG9YSF72R' and (bpm is null or musical_key is null);
  update tracks set bpm = 143.9, musical_key = 'A flat major' where audio_upload_id = '01JBZ8EJS49NQTDC4TB9GMGWES' and (bpm is null or musical_key is null);
  update tracks set bpm = 124, musical_key = 'B flat minor' where audio_upload_id = '01JBZKEAA2P4GBQ75NQ5F5YEDC' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'A minor' where audio_upload_id = '01JBZKEA149WV0AF0CFX7XNTE5' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'B flat minor' where audio_upload_id = '01JBZ8EJZ0NE5T1SDVE9D40MFM' and (bpm is null or musical_key is null);
  update tracks set bpm = 111.1, musical_key = 'F minor' where audio_upload_id = '01JBZKE86DQNR5WV5TPC27Q0M0' and (bpm is null or musical_key is null);
  update tracks set bpm = 79.5, musical_key = 'E flat minor' where audio_upload_id = '01JBZ8EFQHYG21GH3HP2610RPC' and (bpm is null or musical_key is null);
  update tracks set bpm = 111.1, musical_key = 'F minor' where audio_upload_id = '01JBZ8EH9RTW228XR6XAX7DDAH' and (bpm is null or musical_key is null);
  update tracks set bpm = 130, musical_key = 'D flat major' where audio_upload_id = '01JBZ8EMXJNQ8N9P84V2SZ5GE4' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.9, musical_key = 'D minor' where audio_upload_id = '01JBZKE91GXEA4DT8TQM8BB8EB' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'F minor' where audio_upload_id = '01JBZKE9V7XVTNZWJPWKRWXQD6' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'D minor' where audio_upload_id = '01JBZ8EKWCBTW7SXKWWX8BACF6' and (bpm is null or musical_key is null);
  update tracks set bpm = 122, musical_key = 'F major' where audio_upload_id = '01JBZ8EMASHQR426ZS96J11YJA' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.9, musical_key = 'D minor' where audio_upload_id = '01JBZ8EKMMRA7V5AT6DW9JTXRA' and (bpm is null or musical_key is null);
  update tracks set bpm = 143.9, musical_key = 'A flat major' where audio_upload_id = '01JBZKE8P72EE4YKSQ9R510PAK' and (bpm is null or musical_key is null);
  update tracks set bpm = 126, musical_key = 'F minor' where audio_upload_id = '01JBZ8EKPS6JZGMM613HVGM9YH' and (bpm is null or musical_key is null);
  update tracks set bpm = 126, musical_key = 'F minor' where audio_upload_id = '01JBZKE9QSZW1J45GBK83A83RM' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'F minor' where audio_upload_id = '01JBZ8EKQ341PHYXRZ0FH1QYWF' and (bpm is null or musical_key is null);
  update tracks set bpm = 149.8, musical_key = 'C major' where audio_upload_id = '01JC99QDPCEX1NMQY6KMD9RJGW' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.4, musical_key = 'G minor' where audio_upload_id = '01JCEKYVE7XQ3VF35JQX1K54FC' and (bpm is null or musical_key is null);
  update tracks set bpm = 118.1, musical_key = 'F minor' where audio_upload_id = '01JC49SFD3N8CJZRA0JS6DXYJW' and (bpm is null or musical_key is null);
  update tracks set bpm = 118.1, musical_key = 'F minor' where audio_upload_id = '01JC49SFBYNR3GZSD0DPEDTVS3' and (bpm is null or musical_key is null);
  update tracks set bpm = 118.1, musical_key = 'F minor' where audio_upload_id = '01JC49SFBE4ST9BNWP1QK7XXY2' and (bpm is null or musical_key is null);
  update tracks set bpm = 172.3, musical_key = 'A major' where audio_upload_id = '01JC99R2Y8ZRVJMRERS06BBD2V' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'B minor' where audio_upload_id = '01JC6QZ217GXFQDAH30MD6H23M' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'D flat minor' where audio_upload_id = '01JC15FCR7Z3Z6E01BT0Q8BK34' and (bpm is null or musical_key is null);
  update tracks set bpm = 164.4, musical_key = 'A major' where audio_upload_id = '01JC15FCNT6E1WBDTMDX87QD2G' and (bpm is null or musical_key is null);
  update tracks set bpm = 94.9, musical_key = 'G flat major' where audio_upload_id = '01JC6GNF13YT74NM94VQACK64A' and (bpm is null or musical_key is null);
  update tracks set bpm = 130, musical_key = 'D flat major' where audio_upload_id = '01JBZKEA2H1RP4M6WZC9FX6AJ4' and (bpm is null or musical_key is null);
  update tracks set bpm = 118.7, musical_key = 'G minor' where audio_upload_id = '01JC3WC4D4B19F5ZHV7CVK245F' and (bpm is null or musical_key is null);
  update tracks set bpm = 122, musical_key = 'F major' where audio_upload_id = '01JBZKE9VCC1TZCNS2CCVS0GPK' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.6, musical_key = 'B flat minor' where audio_upload_id = '01JBZKE91A8H12SD8P5SYEW2W3' and (bpm is null or musical_key is null);
  update tracks set bpm = 139.9, musical_key = 'E minor' where audio_upload_id = '01JBFN8049C7K8FZ0KE62PZ67N' and (bpm is null or musical_key is null);
  update tracks set bpm = 122.2, musical_key = 'G minor' where audio_upload_id = '01JBZKEAB9W919JCJAR1XJAPVH' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.1, musical_key = 'E flat minor' where audio_upload_id = '01JC3WBNES2ZTJBYZ6GA9EX1DB' and (bpm is null or musical_key is null);
  update tracks set bpm = 109.4, musical_key = 'D flat minor' where audio_upload_id = '01JC15FCHV72Z8A6TRDW2SRCQC' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JBZMPQF81H9CEYBKXZTYE2WD' and (bpm is null or musical_key is null);
  update tracks set bpm = 120, musical_key = 'D minor' where audio_upload_id = '01JBZKEAFDW376VR66G50NKTES' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JCKEYC22FJ9RDPH7AM9615NK' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.4, musical_key = 'G minor' where audio_upload_id = '01JCGHJAHVPQ0PJFFXJHSPCW8Y' and (bpm is null or musical_key is null);
  update tracks set bpm = 129.2, musical_key = 'C minor' where audio_upload_id = '01JCGHJBQ5K2VB7KZHNS7QQ41J' and (bpm is null or musical_key is null);
  update tracks set bpm = 129.2, musical_key = 'C minor' where audio_upload_id = '01JCEKYW2NNEZT8C5B7WG47183' and (bpm is null or musical_key is null);
  update tracks set bpm = 95, musical_key = 'F minor' where audio_upload_id = '01JCEKYV5R271DEJS6E99BCM8P' and (bpm is null or musical_key is null);
  update tracks set bpm = 95, musical_key = 'F minor' where audio_upload_id = '01JCGHJA3X9FBEDNATJCGTC2AT' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.4, musical_key = 'F minor' where audio_upload_id = '01JCEKYWNVBR9CGGNZCN0ZJF85' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.4, musical_key = 'F minor' where audio_upload_id = '01JCGHJC6TH0C8S9XP1FBF8863' and (bpm is null or musical_key is null);
  update tracks set bpm = 153.1, musical_key = 'G flat major' where audio_upload_id = '01JCEM9EYBW4EJ8HJ68KMTRD95' and (bpm is null or musical_key is null);
  update tracks set bpm = 139.9, musical_key = 'E minor' where audio_upload_id = '01JCHA5KF0YFJV8QJ4KZ5HAM3E' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCK7GYZHDGZNF3N8T8G0A6A1' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCKQZFD25N7Y869V5PTF700V' and (bpm is null or musical_key is null);
  update tracks set bpm = 153.1, musical_key = 'G flat major' where audio_upload_id = '01JCHA2W73CM1D5PZKFB8E76F9' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCKE9F39128CDZPEAPR03YMS' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH3932M02X7Z4RB7WP7CB86' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH5DEW907KCZ5MGQ5DJDJBE' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH3RJTW171WZGJM5PBEA3NJ' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH55M9PYC695HPFTG4WPXTV' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH51XYMSPBA9DNSKZJS6AEV' and (bpm is null or musical_key is null);
  update tracks set bpm = 84.8, musical_key = 'D major' where audio_upload_id = '01JCH6KEQX277H8XX62FFS9JC4' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD36RKCRMA12NWD30WBESKZ1' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD3B507SS4PZP2QPZPCK2K2H' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD3BNWET2VW2AC1KYCDW79XW' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD7T9HFD5DB3X1P6458CD61Y' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD3B8E1XW0WYFJWP918JW0EW' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5NW4KY32BNDVD4DEEYYDNG' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN1NV5FY2DSDAATZDMHC' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5P3CD8YRGWA4368Q0GM4J7' and (bpm is null or musical_key is null);
  update tracks set bpm = 114.4, musical_key = 'F minor' where audio_upload_id = '01JCRS35Y3X4RWSME4XV6VB57J' and (bpm is null or musical_key is null);
  update tracks set bpm = 172.3, musical_key = 'A major' where audio_upload_id = '01JD5B60QXS9K1SGNH34P2QR2M' and (bpm is null or musical_key is null);
  update tracks set bpm = 98.4, musical_key = 'G minor' where audio_upload_id = '01JD57ASY5888PS0YCQVZRSM7Z' and (bpm is null or musical_key is null);
  update tracks set bpm = 154.5, musical_key = 'G flat major' where audio_upload_id = '01JD3C3VN6SSF47ZJJ8E0BR3PV' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCKFV3BZ3A33RAFWERDNPRZB' and (bpm is null or musical_key is null);
  update tracks set bpm = 123.8, musical_key = 'E flat minor' where audio_upload_id = '01JD5781422M42XNWD7BTNGGCM' and (bpm is null or musical_key is null);
  update tracks set bpm = 172.3, musical_key = 'G major' where audio_upload_id = '01JCP9TBH7S89FZFVVJXEH1Z1S' and (bpm is null or musical_key is null);
  update tracks set bpm = 154.5, musical_key = 'G flat major' where audio_upload_id = '01JD5B6TCXR7AE2VS01GGV0YJS' and (bpm is null or musical_key is null);
  update tracks set bpm = 96.4, musical_key = 'D major' where audio_upload_id = '01JCR9Z831DT63XTC4KT8ASMT7' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCKFHKYS4Z0SAERBVCH38404' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JCKQGM146FNBRKB6Q7FMFW09' and (bpm is null or musical_key is null);
  update tracks set bpm = 80, musical_key = 'D flat minor' where audio_upload_id = '01JCKHB7AGFMZ2W2WBEVTRH2CD' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD7WV2JA4APFTCGBW5RTKWZA' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN608A7T2H8M8GW8HHX1' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN6C6WZ0G3JWP28Z8DYJ' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN1R9YTD176253JB09V3' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN7BM0W2D68EZ463WC8J' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'C major' where audio_upload_id = '01JD5WNN0H9XJ4WZHD3F16N6K2' and (bpm is null or musical_key is null);
  update tracks set bpm = 116.1, musical_key = 'G minor' where audio_upload_id = '01JD5ECN7CME8Z9G4AGXJV6RV8' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'C major' where audio_upload_id = '01JD5V0NDN67Z2293FXW2V222N' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'C major' where audio_upload_id = '01JD5QY7AWWV8TVD2VY27SFS8H' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5WSCSBC4E5T5D74VFDB6QZ' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5X7G81HR0TXS0DTXKVJVDJ' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5YRD1ZAQWDKRHX46RH9KDY' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD7X6CT05D6HR0MW9DKYS1FK' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD5XKT8M6JZ3WR1PR7QM2NHP' and (bpm is null or musical_key is null);
  update tracks set bpm = 161.5, musical_key = 'C major' where audio_upload_id = '01JD5VQ3V1YCK1ZCSVQK2QABT3' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JD5GT14PR3AEHAYC36PFNM7N' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JD5GT13DV6BWBQ3BFS6VYGK1' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JD7X6CZ8GK07SE49W0DD11NG' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JD5GNET860TWJX6WBBHZZAA2' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JD5GNEXKPECEZWKYFH2NYWD0' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD8BJQQV3VG2BXKCCMAFSP6X' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD7XEEHD15VR65CBPKTM3GYG' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD8C74K94H98XXV29Y1JET0A' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD8B6J4A99X1DJB30KPG6C72' and (bpm is null or musical_key is null);
  update tracks set bpm = 178.2, musical_key = 'G major' where audio_upload_id = '01JD8BKXDVKYG6A78PA5TYRTQR' and (bpm is null or musical_key is null);
  update tracks set bpm = 110, musical_key = 'G flat minor' where audio_upload_id = '01JD7XEEXRN17TBHWTXHC5HVZX' and (bpm is null or musical_key is null);
  update tracks set bpm = 738.3, musical_key = 'Silence' where audio_upload_id = '01JD89J1GH0RTSMETCYKWK4E9D' and (bpm is null or musical_key is null);

end if;
end $$;
commit;
