BEGIN;

CREATE TABLE IF NOT EXISTS countries (
  iso char(2) NOT NULL,
  name varchar(80) NOT NULL,
  nicename varchar(80) NOT NULL,
  iso3 char(3) DEFAULT NULL,
  numcode smallint DEFAULT NULL,
  phonecode int NOT NULL,
  PRIMARY KEY (iso)
)  ;

truncate countries;

INSERT INTO countries (iso, name, nicename, iso3, numcode, phonecode) VALUES
('AD', 'ANDORRA', 'Andorra', 'AND', 20, 376),
('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 971),
('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 93),
('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 1268),
('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 1264),
('AL', 'ALBANIA', 'Albania', 'ALB', 8, 355),
('AM', 'ARMENIA', 'Armenia', 'ARM', 51, 374),
('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 599),
('AO', 'ANGOLA', 'Angola', 'AGO', 24, 244),
('AQ', 'ANTARCTICA', 'Antarctica', 'ATA', 10, 0),
('AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 54),
('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 1684),
('AT', 'AUSTRIA', 'Austria', 'AUT', 40, 43),
('AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 61),
('AW', 'ARUBA', 'Aruba', 'ABW', 533, 297),
('AX', 'ALAND ISLANDS', 'Aland Islands', 'ALA', '248', '358'),
('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 994),
('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 387),
('BB', 'BARBADOS', 'Barbados', 'BRB', 52, 1246),
('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 880),
('BE', 'BELGIUM', 'Belgium', 'BEL', 56, 32),
('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 226),
('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 359),
('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 973),
('BI', 'BURUNDI', 'Burundi', 'BDI', 108, 257),
('BJ', 'BENIN', 'Benin', 'BEN', 204, 229),
('BL', 'SAINT BARTHELEMY', 'Saint Barthelemy', 'BLM', '652', '590'),
('BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 1441),
('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 673),
('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 591),
('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', '599'),
('BR', 'BRAZIL', 'Brazil', 'BRA', 76, 55),
('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 1242),
('BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 975),
('BV', 'BOUVET ISLAND', 'Bouvet Island', 'BVT', 74, 0),
('BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 267),
('BY', 'BELARUS', 'Belarus', 'BLR', 112, 375),
('BZ', 'BELIZE', 'Belize', 'BLZ', 84, 501),
('CA', 'CANADA', 'Canada', 'CAN', 124, 1),
('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 672),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 243),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 236),
('CG', 'CONGO', 'Congo', 'COG', 178, 242),
('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 41),
('CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384, 225),
('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 682),
('CL', 'CHILE', 'Chile', 'CHL', 152, 56),
('CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 237),
('CN', 'CHINA', 'China', 'CHN', 156, 86),
('CO', 'COLOMBIA', 'Colombia', 'COL', 170, 57),
('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 506),
('CU', 'CUBA', 'Cuba', 'CUB', 192, 53),
('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 238),
('CW', 'CURACAO', 'Curacao', 'CUW', '531', '599'),
('CX', 'CHRISTMAS ISLAND', 'Christmas Island', 'CXR', 162, 61),
('CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 357),
('CZ', 'CZECHIA', 'Czech Republic', 'CZE', 203, 420),
('DE', 'GERMANY', 'Germany', 'DEU', 276, 49),
('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 253),
('DK', 'DENMARK', 'Denmark', 'DNK', 208, 45),
('DM', 'DOMINICA', 'Dominica', 'DMA', 212, 1767),
('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 1),
('DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 213),
('EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 593),
('EE', 'ESTONIA', 'Estonia', 'EST', 233, 372),
('EG', 'EGYPT', 'Egypt', 'EGY', 818, 20),
('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 212),
('ER', 'ERITREA', 'Eritrea', 'ERI', 232, 291),
('ES', 'SPAIN', 'Spain', 'ESP', 724, 34),
('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 251),
('FI', 'FINLAND', 'Finland', 'FIN', 246, 358),
('FJ', 'FIJI', 'Fiji', 'FJI', 242, 679),
('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 500),
('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 691),
('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 298),
('FR', 'FRANCE', 'France', 'FRA', 250, 33),
('GA', 'GABON', 'Gabon', 'GAB', 266, 241),
('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 44),
('GD', 'GRENADA', 'Grenada', 'GRD', 308, 1473),
('GE', 'GEORGIA', 'Georgia', 'GEO', 268, 995),
('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 594),
('GG', 'GUERNSEY', 'Guernsey', 'GGY', '831', '44'),
('GH', 'GHANA', 'Ghana', 'GHA', 288, 233),
('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 350),
('GL', 'GREENLAND', 'Greenland', 'GRL', 304, 299),
('GM', 'GAMBIA', 'Gambia', 'GMB', 270, 220),
('GN', 'GUINEA', 'Guinea', 'GIN', 324, 224),
('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 590),
('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 240),
('GR', 'GREECE', 'Greece', 'GRC', 300, 30),
('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'SGS', 239, 0),
('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 502),
('GU', 'GUAM', 'Guam', 'GUM', 316, 1671),
('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 245),
('GY', 'GUYANA', 'Guyana', 'GUY', 328, 592),
('HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 852),
('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', 'HMD', 334, 0),
('HN', 'HONDURAS', 'Honduras', 'HND', 340, 504),
('HR', 'CROATIA', 'Croatia', 'HRV', 191, 385),
('HT', 'HAITI', 'Haiti', 'HTI', 332, 509),
('HU', 'HUNGARY', 'Hungary', 'HUN', 348, 36),
('ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 62),
('IE', 'IRELAND', 'Ireland', 'IRL', 372, 353),
('IL', 'ISRAEL', 'Israel', 'ISR', 376, 972),
('IM', 'ISLE OF MAN', 'Isle of Man', 'IMN', '833', '44'),
('IN', 'INDIA', 'India', 'IND', 356, 91),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'IOT', 86, 246),
('IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 964),
('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 98),
('IS', 'ICELAND', 'Iceland', 'ISL', 352, 354),
('IT', 'ITALY', 'Italy', 'ITA', 380, 39),
('JE', 'JERSEY', 'Jersey', 'JEY', '832', '44'),
('JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 1876),
('JO', 'JORDAN', 'Jordan', 'JOR', 400, 962),
('JP', 'JAPAN', 'Japan', 'JPN', 392, 81),
('KE', 'KENYA', 'Kenya', 'KEN', 404, 254),
('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 996),
('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 855),
('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 686),
('KM', 'COMOROS', 'Comoros', 'COM', 174, 269),
('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 1869),
('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408, 850),
('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 82),
('KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 965),
('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 1345),
('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 7),
('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418, 856),
('LB', 'LEBANON', 'Lebanon', 'LBN', 422, 961),
('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 1758),
('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 423),
('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 94),
('LR', 'LIBERIA', 'Liberia', 'LBR', 430, 231),
('LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 266),
('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 370),
('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 352),
('LV', 'LATVIA', 'Latvia', 'LVA', 428, 371),
('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 218),
('MA', 'MOROCCO', 'Morocco', 'MAR', 504, 212),
('MC', 'MONACO', 'Monaco', 'MCO', 492, 377),
('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 373),
('ME', 'MONTENEGRO', 'Montenegro', 'MNE', 499, 382),
('MF', 'SAINT MARTIN', 'Saint Martin', 'MAF', '663', '590'),
('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 261),
('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 692),
('MK', 'NORTH MACEDONIA', 'North Macedonia', 'MKD', 807, 389),
('ML', 'MALI', 'Mali', 'MLI', 466, 223),
('MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 95),
('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 976),
('MO', 'MACAO', 'Macao', 'MAC', 446, 853),
('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 1670),
('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 596),
('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 222),
('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 1664),
('MT', 'MALTA', 'Malta', 'MLT', 470, 356),
('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 230),
('MV', 'MALDIVES', 'Maldives', 'MDV', 462, 960),
('MW', 'MALAWI', 'Malawi', 'MWI', 454, 265),
('MX', 'MEXICO', 'Mexico', 'MEX', 484, 52),
('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 60),
('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 258),
('NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 264),
('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 687),
('NE', 'NIGER', 'Niger', 'NER', 562, 227),
('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 672),
('NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 234),
('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 505),
('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 31),
('NO', 'NORWAY', 'Norway', 'NOR', 578, 47),
('NP', 'NEPAL', 'Nepal', 'NPL', 524, 977),
('NR', 'NAURU', 'Nauru', 'NRU', 520, 674),
('NU', 'NIUE', 'Niue', 'NIU', 570, 683),
('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 64),
('OM', 'OMAN', 'Oman', 'OMN', 512, 968),
('PA', 'PANAMA', 'Panama', 'PAN', 591, 507),
('PE', 'PERU', 'Peru', 'PER', 604, 51),
('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 689),
('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 675),
('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 63),
('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 92),
('PL', 'POLAND', 'Poland', 'POL', 616, 48),
('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 508),
('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 0),
('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 1787),
('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 970),
('PT', 'PORTUGAL', 'Portugal', 'PRT', 620, 351),
('PW', 'PALAU', 'Palau', 'PLW', 585, 680),
('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 595),
('QA', 'QATAR', 'Qatar', 'QAT', 634, 974),
('RE', 'REUNION', 'Reunion', 'REU', 638, 262),
('RO', 'ROMANIA', 'Romania', 'ROU', 642, 40),
('RS', 'SERBIA', 'Serbia', 'SRB', 688, 381),
('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 7),
('RW', 'RWANDA', 'Rwanda', 'RWA', 646, 250),
('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 966),
('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 677),
('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 248),
('SD', 'SUDAN', 'Sudan', 'SDN', 736, 249),
('SE', 'SWEDEN', 'Sweden', 'SWE', 752, 46),
('SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 65),
('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 290),
('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 386),
('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 47),
('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 421),
('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 232),
('SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 378),
('SN', 'SENEGAL', 'Senegal', 'SEN', 686, 221),
('SO', 'SOMALIA', 'Somalia', 'SOM', 706, 252),
('SR', 'SURINAME', 'Suriname', 'SUR', 740, 597),
('SS', 'SOUTH SUDAN', 'South Sudan', 'SSD', '728', '211'),
('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 239),
('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 503),
('SX', 'SINT MAARTEN', 'Sint Maarten', 'SXM', '534', '1'),
('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 963),
('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 268),
('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 1649),
('TD', 'CHAD', 'Chad', 'TCD', 148, 235),
('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'ATF', 260, 0),
('TG', 'TOGO', 'Togo', 'TGO', 768, 228),
('TH', 'THAILAND', 'Thailand', 'THA', 764, 66),
('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 992),
('TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 690),
('TL', 'TIMOR-LESTE', 'Timor-Leste', 'TLS', 626, 670),
('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 993),
('TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 216),
('TO', 'TONGA', 'Tonga', 'TON', 776, 676),
('TR', 'TÜRKIYE', 'Türkiye, The Republic of', 'TUR', 792, 90),
('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 1868),
('TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 688),
('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 886),
('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 255),
('UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 380),
('UG', 'UGANDA', 'Uganda', 'UGA', 800, 256),
('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', 'UMI', 581, 1),
('US', 'UNITED STATES', 'United States', 'USA', 840, 1),
('UY', 'URUGUAY', 'Uruguay', 'URY', 858, 598),
('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 998),
('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 39),
('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784),
('VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 58),
('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 1284),
('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 1340),
('VN', 'VIET NAM', 'Vietnam', 'VNM', 704, 84),
('VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 678),
('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 681),
('WS', 'SAMOA', 'Samoa', 'WSM', 882, 684),
('XK', 'KOSOVO', 'Kosovo', 'XKX', 0, 383),
('YE', 'YEMEN', 'Yemen', 'YEM', 887, 967),
('YT', 'MAYOTTE', 'Mayotte', 'MYT', 175, 269),
('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 27),
('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 260),
('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 263)

-- ('WW', 'WORLD WIDE', 'World Wide', 'WWW', -1, -1)
ON CONFLICT DO NOTHING
;

-- audius specific variations
update countries set nicename = 'Bonaire, Saint Eustatius and Saba ' where iso = 'BQ';
update countries set nicename = 'British Virgin Islands' where iso = 'VG';
update countries set nicename = 'Brunei' where iso = 'BN';
update countries set nicename = 'Cabo Verde' where iso = 'CV';
update countries set nicename = 'Cocos Islands' where iso = 'CC';
update countries set nicename = 'Czechia' where iso = 'CZ';
update countries set nicename = 'Democratic Republic of the Congo' where iso = 'CD';
update countries set nicename = 'Eswatini' where iso = 'SZ';
update countries set nicename = 'Falkland Islands' where iso = 'FK';
update countries set nicename = 'Iran' where iso = 'IR';
update countries set nicename = 'Ivory Coast' where iso = 'CI';
update countries set nicename = 'Laos' where iso = 'LA';
update countries set nicename = 'Libya' where iso = 'LY';
update countries set nicename = 'Micronesia' where iso = 'FM';
update countries set nicename = 'Moldova' where iso = 'MD';
update countries set nicename = 'Palestinian Territory' where iso = 'PS';
update countries set nicename = 'Republic of the Congo' where iso = 'CG';
update countries set nicename = 'Russia' where iso = 'RU';
update countries set nicename = 'South Korea' where iso = 'KR';
update countries set nicename = 'Syria' where iso = 'SY';
update countries set nicename = 'Taiwan' where iso = 'TW';
update countries set nicename = 'Tanzania' where iso = 'TZ';
update countries set nicename = 'The Netherlands' where iso = 'NL';
update countries set nicename = 'Timor Leste' where iso = 'TL';
update countries set nicename = 'Turkey' where iso = 'TR';
update countries set nicename = 'U.S. Virgin Islands' where iso = 'VI';





COMMIT;

-- a test to find countries that are not in the list
-- create temporary table countries_audius as (select distinct country from plays);
-- select country_to_iso_alpha2(country), country from countries_audius where country not in (select nicename from countries);
