CREATE TABLE IF NOT EXISTS sol_unprocessed_txs (
    signature TEXT NOT NULL PRIMARY KEY,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sol_unprocessed_txs
    ADD COLUMN IF NOT EXISTS slot BIGINT NOT NULL DEFAULT 0;