CREATE TABLE IF NOT EXISTS artist_coin_stats (
    mint TEXT PRIMARY KEY,
    market_cap DOUBLE PRECISION,
    fdv DOUBLE PRECISION,
    liquidity DOUBLE PRECISION,
    last_trade_unix_time BIGINT,
    last_trade_human_time TEXT,
    price DOUBLE PRECISION,
    history_24h_price DOUBLE PRECISION,
    price_change_24h_percent DOUBLE PRECISION,
    unique_wallet_24h INTEGER,
    unique_wallet_history_24h INTEGER,
    unique_wallet_24h_change_percent DOUBLE PRECISION,
    total_supply DOUBLE PRECISION,
    circulating_supply DOUBLE PRECISION,
    holder INTEGER,
    trade_24h INTEGER,
    trade_history_24h INTEGER,
    trade_24h_change_percent DOUBLE PRECISION,
    sell_24h INTEGER,
    sell_history_24h INTEGER,
    sell_24h_change_percent DOUBLE PRECISION,
    buy_24h INTEGER,
    buy_history_24h INTEGER,
    buy_24h_change_percent DOUBLE PRECISION,
    v_24h DOUBLE PRECISION,
    v_24h_usd DOUBLE PRECISION,
    v_history_24h DOUBLE PRECISION,
    v_history_24h_usd DOUBLE PRECISION,
    v_24h_change_percent DOUBLE PRECISION,
    v_buy_24h DOUBLE PRECISION,
    v_buy_24h_usd DOUBLE PRECISION,
    v_buy_history_24h DOUBLE PRECISION,
    v_buy_history_24h_usd DOUBLE PRECISION,
    v_buy_24h_change_percent DOUBLE PRECISION,
    v_sell_24h DOUBLE PRECISION,
    v_sell_24h_usd DOUBLE PRECISION,
    v_sell_history_24h DOUBLE PRECISION,
    v_sell_history_24h_usd DOUBLE PRECISION,
    v_sell_24h_change_percent DOUBLE PRECISION,
    number_markets INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);