FROM alpine:3.14

ENV INSTALL_PATH /audius-discovery-provider
WORKDIR $INSTALL_PATH

ENV PROMETHEUS_MULTIPROC_DIR /prometheus_data
RUN mkdir -p ${PROMETHEUS_MULTIPROC_DIR}

RUN apk update && \
    apk add \
        alpine-sdk \
        bash \
        curl \
        docker \
        libffi-dev \
        libseccomp-dev \
        linux-headers \
        nodejs \
        npm \
        py3-numpy \
        py3-pip \
        py3-scipy \
        py3-wheel \
        python3 \
        python3-dev \
        redis \
        rsyslog \
        sudo \
        gcc \
        musl-dev

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.10/main' >> /etc/apk/repositories && \
    apk update && \
    apk add \
        libpq=11.12-r0 \
        postgresql-client=11.12-r0 \
        postgresql-contrib=11.12-r0 \
        postgresql-dev=11.12-r0 \
        postgresql-libs=11.12-r0 \
        postgresql=11.12-r0

COPY scripts/init-db.sh scripts/init-db.sh
RUN bash scripts/init-db.sh

# Upgrade pip first to accomodate anchor.py installation
COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt --no-cache-dir

ENV audius_redis_url redis://localhost:6379/00

COPY . .
RUN cd es-indexer && npm install && npm run build

CMD ["bash", "scripts/test_setup.sh"]

