// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: setup.sql

package db

import (
	"context"
)

const checkDatabaseExists = `-- name: CheckDatabaseExists :one
select exists (select datname from pg_catalog.pg_database where datname = $1) as exists
`

func (q *Queries) CheckDatabaseExists(ctx context.Context, datname string) (bool, error) {
	row := q.db.QueryRow(ctx, checkDatabaseExists, datname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
