version: '3.9'

services:
  # service that simulates ethereum mainnet
  eth-ganache:
    container_name: eth-ganache
    image: audius/eth-ganache:latest
    ports:
      - "8546:8545"
    networks:
      - devnet
  
  # service that simulates solana mainnet
  sol-validator:
    container_name: solana-test-validator
    image: audius/solana-programs:latest
    ports:
      - "8899:8899"
    networks:
      - devnet

  # service that simulates acdc network
  acdc-ganache:
    container_name: acdc-ganache
    image: audius/acdc-ganache:latest
    ports:
      - "8545:8545"
    networks:
      - devnet

  ingress:
    container_name: ingress
    image: nginx:latest
    volumes:
      - ./nginx_ingress_audiusd.conf:/etc/nginx/conf.d/default.conf
      - ../tls/devnet-cert.pem:/tmp/cert.pem
      - ../tls/devnet-key.pem:/tmp/key.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - devnet

networks:
  devnet:
    name: deployments_devnet
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
